### PR TITLE
Rename Dummy Lv# to Lv #.

### PR DESCRIPTION
**Pull request by Jedzkie**
This is kRO's mob name in prontera.

### CODE REVIEW

**Comment by zackdreaver** [comment]
can you check if kRO's can be knocked back?
last time i remember, herc's dummy are knock back able

**Comment by Jedzkie** [comment]
I don't have character to test it xD

**Comment by zackdreaver** [comment]
i thought you have one, heh

**Comment by MishimaHaruna** [comment]
Merged, thank you!

**Pull request closed without merging**
