### PR TITLE
Split eathena-upgrade.sql in two files

### PR DESCRIPTION
**Pull request by maqc1**
Split eathena-upgrade in two files, one for main and one for logs (as is it for rAthena-upgrade).

This file needs some serious clean up, but it works so whatever =P

### CODE REVIEW

**Comment by dastgir** [comment]
Seems good enough

**Comment by dastgir** [comment]
Have you tested this?
I mean, I guess , there's more SQL tables to be included now, this file is too old and doesn't contain new tables info...

**Comment by maqc1** [comment]
Yup I have just made the transition from eAthena fo Hercules on my server. For the newer tables you just need to run all the hercules upgrade sql files afterwards (as mentionned).

**Comment by dastgir** [comment]
Can you rebase and squash the split commits into 1?
So that this PR will contain 2 commit, one for split and one for Update main.sql

**Comment by maqc1** [comment]
Not quite sure I understand what you mean. To be honest i'm fairly new to github!

**Comment by MishimaHaruna** [comment]
No worries, I'll take care of conflicts and rebasing

**Comment by MishimaHaruna** [comment]
Merged, thank you very much

**Pull request closed without merging**
