### PR TITLE
allow the PC timer buildins to run on another player

### PR DESCRIPTION
**Pull request by mekolat**
### Pull Request Prelude
- [X] I have followed [proper Hercules code styling][code].
- [X] I have read and understood the [contribution guidelines][cont] before making this PR.
- [X] I am aware that this PR will be closed if the above-mentioned criteria are not fulfilled.

### Changes Proposed
- add a new parameter to `addtimer`, `addtimercount`, and `deltimer` to make them usable on another player
- ~~~add new buildin: `areatimer("map", x1, y1, x2, y2, tick, "npc::event")`~~~

**Affected Branches:** `master`

**Issues addressed:** (none)

### Known Issues
(none)

### TODO
- [x] update documentation

---
This change is [Reviewable](https://reviewable.io/reviews/herculesws/hercules/1610)

### CODE REVIEW

**Comment by Emistry** [comment]
`areatimer("map", x1, y1, x2, y2, tick, "npc::event")`
if you added this, perhaps you may consider to add for `delareatimer` to remove the timer also?

normally the old timer will be removed before the new timer is added to player.

**Comment by mekolat** [comment]
@Emistry why would you want to check if the player has a timer before deleting a timer? deltimer doesn't care if you already have it or not.

what I could do is remove `areatimer` and add a `getareaunits("<map>", <x1>, <y1>, <x2>, <y2>, <type>, <array>)` so you'd be able to do the following:

```c
    npctalk("I am the most beautiful being the Universe ever begat!");
    sleep(500);
    npctalk("...and you shall all love me!");

    getareaunits("map", 45, 67, 109, 111, UNITTYPE_PC, .@gid);

    for (.@i = 0; .@i < getarraysize(.@gid); ++.@i)
    {
        deltimer(strnpcinfo(0) + "::OnEvent", .@gid[.@i]); // remove old timer, if any
        addtimer(500, strnpcinfo(0) + "::OnEvent", .@gid[.@i]);
    }
    end;

OnEvent:
    emotion(e_heart); // force everyone in the area to do a heart emote
    end;
```

@MishimaHaruna what would you prefer?

**Comment by Emistry** [comment]
definitely downvote for that `getareaunits` thing.... @AnnieRuru show a better approach for `getmemberaid` previously.

the reason to add the `deltimerarea`, because you added the `areatimer` thing ... 
almost all the time, when you assign the timer in any scripts , you would deltimer any existing timers before you assign it. You commit lack of this script command.

**Comment by mekolat** [comment]
@Emistry what do you mean about `getmemberaid`?

get on IRC please?

**Comment by Emistry** [comment]
hmm
> getunits(AREA, UNITTYPE_PC, 50, .@account_id, "map", x1, y1, x2, y2) which would fill .@account_id with up to 50 players (UNITTYPE_PC) in the area
why need to limit the size? if compare with the `getmemberaid` did by @AnnieRuru  the advantages of `getunits` are just the array assignment + unit type to filter, which are nice to have.
if insist to add the parameter for `size`, perhaps it should be add as the last optional parameter.

anyway, if you insist to add the `getunits` please at least make it meaningful ? something like `getunitsaid` or `getunitsrid` or `getunitsid` ? at least we know the script command return `account_id` or `gid` from the unit by looking at it.

for the `delareatimer` implementation...
> areatimer("map", x1, y1, x2, y2, tick, "npc::event")
> if you added this, perhaps you may consider to add for `delareatimer` to remove the timer also?
> normally the old timer should be removed before the new timer is added to player to avoid duplicate 
> timer running.

You are trying to attach the timer to everyone in that area ... but you didnt have a way to delete their existing timer before you attach a new timer to them, which end up potentially create multiple timers that execute the same event label.
unless you trying to tell me you gonna do it this way...
```
.@size = getunits( AREA, UNITTYPE_PC, .@aid );
for ( .@i = 0; .@i < .@size; .@i++ ) {
	deltimer "npc::event",.@aid[.@i];
}
areatimer("map", x1, y1, x2, y2, tick, "npc::event");
```
and not something like this..
```
deltimer( "npc::event","map",x1,y1,x2,y2 );
areatimer("map", x1, y1, x2, y2, tick, "npc::event");
```
or 
```
.@size = getunits( AREA, UNITTYPE_PC, .@aid );
for ( .@i = 0; .@i < .@size; .@i++ ) {
	deltimer "npc::event",.@aid[.@i];
	addtimer 10000, "npc::event",.@aid[.@i];
}
```
which end up `areatimer()` are kinda useless in this case.

beside, all these new script commands are just extra bonus use in custom scripts, you rarely find any official scripts are using these timer.

**Comment by mekolat** [comment]
@Emistry 

> why need to limit the size? aren't Herc already support array up to 2 Billions index?

>> `<_41444d494e_>` if i not wrong now getunits() get all in area and put into array
`<_41444d494e_>` but it can be slow if here 1k or 10k units
(...)
`<meko>` yeah let's say you just want to execute it on 10 nearby players, it would pointless to fill the whole array if you just want 10
`<meko>` I could make so that if you put 0 as limit then there's no cap besides MAX_ARRAY_SIZE
`<smoke_>` makes sense
`<smoke_>` you could alternatively make the limit an optional entry
`<meko>` nah I want to make that explicit
`<meko>` if you don't want a limit pass false (0), else pass a number
`<smoke_>` Yeah it's not a problem, but I don't see the point of limiting in that case, when you could just reduce the area size.
`<smoke_>` But since 0 is unlimited, it's okay I guess.
`<meko>` you can reduce the area size indeed but while extremely unlikely it's not impossible to have 1k players standing on one single tile
`<smoke_>` true :P

<br><br>

> `getunits` I dont know what it return by looking at it, return id? units struct? aid? gid? cid?

it returns unit id (aka BL_ID, aka GID), which is independent of unit type, so adding the `aid` or `rid` prefix here makes no sense since those are PC-specific and this buildin is type-agnostic
<br><br>

> You are trying to attach the timer to everyone in that area ... but you didnt have a way to delete their existing timer before you attach a new timer to them, which end up potentially create multiple timers that execute the same event label.

didn't you read my earlier comment? or even look at the commits in this PR? this PR is mostly to add the `<account id>` parameter to the existing timer buildins; getunits() is just icing on the cake, and GEEZ, please just forget about `areatimer`, the `getunits` makes it obsolete so I'm not adding it (nor a `delareatimer`)

```c
    for (.@i = 0; .@i < getarraysize(.@gid); ++.@i)
    {
        deltimer(strnpcinfo(0) + "::OnEvent", .@gid[.@i]); // remove old timer, if any
        addtimer(500, strnpcinfo(0) + "::OnEvent", .@gid[.@i]);
    }
```

**Comment by Emistry** [comment]
I do look at the commits, and I still can see the `areatimer`  tho. 
In my point of view `getunits` simply meaningless it should at least `getunitsid` or whatever to represent what it returned from the result in case it get implemented.

anyway, please fix the doc/script_commands.txt why are there almost a empty space modification at every single line.

**Comment by mekolat** [comment]
@Emistry the reason you still see `areatimer` is because I didn't yet remove it, nor start working on `getunits()`, because I'm waiting till we can finalize the buildin name and its arguments, to not end up doing the same work a dozen time, hence the `WIP` in the title. and yes, I'll fix the doc once this PR is done.

**Comment by mekolat** [comment]
@Emistry @MishimaHaruna I'm removing the getunits/areatimer from this PR so we can just merge the timer buildin modifications; gonna make another PR for getunits later on

**Comment by MishimaHaruna** [comment]
Merged, thank you!

**Pull request merged**
