### PR TITLE
Hpmhooking improvements

### PR DESCRIPTION
**Pull request by MishimaHaruna**
- Compile-time checks of the HPMHooking functions. This means that, if a plugin hooks into a function through HPMHooking, and the core function changes, the plugin will show a compile-time warning instead of silently compiling (and crashing at runtime or causing undesired effects).
- Added one level of indirection to pointer variables in pre/post hook functions (previously only non-pointer variables had that). This makes it possible to override const pointers from HPMHooking hooks.

### CODE REVIEW

**Comment by EPuncker** [comment]
hey @MishimaHaruna can you please guide us on how to update our current plugins in order to work with those new changes since it broke every single one :P

**Comment by dastgir** [comment]
Structures will have one more level of indirection in preHook
(struct xyz * will now be struct xyz **)
And all parameters in postHook will be same as the functions in source (no indirection)

**Comment by Emistry** [comment]
just curious ...
i noticed some of it still declared like this
`(struct xyz ** will now be struct xyz *)`
or
`(struct xyz * will now be struct xyz **)`
or
`(struct xyz * will now be struct xyz *)`
or
`(struct xyz ** will now be struct xyz **)`

as you can see the amount of asterisk symbol`*` used are different sometime.

**Comment by dastgir** [comment]
For preHook, 2nd one.
For postHook, 3rd one

**Comment by MishimaHaruna** [comment]
I just posted a topic explaining the changes: http://herc.ws/board/topic/12583-2016-05-01-hpmhooking-improvements/

**Pull request merged**
