### PR TITLE
Added a missing entry into messages.conf and added some comments wher…

### PR DESCRIPTION
**Pull request by EPuncker**
…e missing, ref #1282

---
This change is [Reviewable](https://reviewable.io/reviews/herculesws/hercules/1378)

### CODE REVIEW

**Comment by EPuncker** [comment]
@MishimaHaruna why did it failed to pass the checks?

**Comment by MishimaHaruna** [comment]
@EPuncker it says it's not mergeable. How did you start the pull request? Your fork's master branch doesn't seem up to date with Hercules'

**Comment by EPuncker** [comment]
I've forked it here in the website and then cloned it with git shell, made the changes and used commit -a then git push :'( I'm really a noob at this

**Comment by MishimaHaruna** [comment]
Checking your fork, the issue seems to be that you made your commits on the master branch (which is not really recommended or supported by github). The recommendation is to start a new branch for each pull request (and optionally, delete the branches once each pull request is merged) and to never commit anything on master (so that you can sync master with Hercules before starting new branches)

I can provide instructions on how to bring it back to a clean state, but you'll lose any changes you made to your fork.

**Comment by hemagx** [comment]
@Haru maybe he can just start new branch based on master, then sync
master with hercules or just rebase this branch on top of
Hercules/master

**Comment by MishimaHaruna** [comment]
@hemagx Yes. There might be rebase conflicts though.

My suggestion is:
- Create a new branch with the commit you want to keep: `git checkout -b messagesconf-update`
- Add Hercules a the upstream remote: `git remote add upstream https://github.com/HerculesWS/Hercules.git`
- Fetch the latest changes from Hercules: `git fetch upstream -p`
- Switch to the master branch: `git checkout master`
- Reset the master branch to the clean Hercules master state: `git reset --hard upstream/master`
- Push the master branch to your forked repository, overwriting what's currently there: `git push --force`
- Switch to the branch containing your changes: `git checkout messagesconf-update`
- Rebase your changes on top of master: `git rebase master`
- Pray that there are no conflicts. If there are, solve them (edit the conflicted files, fix them then `git add xxx` for each file, and finally `git rebase --continue`)
- Push the rebased branch: `git push --set-upstream origin messagesconf-update`

Once done, you might need to close this pull request and reopen it from the new branch.

**Comment by EPuncker** [comment]
thanks for the very detailed guide haru

**Pull request closed without merging**
