### PR TITLE
Unify specialeffect, convert legacy scripts

### LINKED ISSUE #1362: Missing Script Commands
Hercules is missing some script commands which are needed for some of the new instances ( e.g. refined or enchanted but unidentified). But they are in general useful and were requested at forums quite often. I saw there are some versions available, but in my opinion it is a must have anyways. 

---

- [x] `makeitem2 <itemid/name>,<amount>,"<map name>",<X>,<Y>,<identify>,<refine>,<attribute>,<card1>,<card2>,<card3>,<card4>;`

just like  getitem2 you can create an item where you can set  several settings, but like makeitem it is dropped on the floor

---

- [x] setunitdata/getunitdata (setmobdata, setmobdir, call it however you want) :name_badge: 
there was a plugin available and I know Anni was working on implementing it. https://trello.com/c/rxxqfcw5/65-setunitdir-getunitdir
http://herc.ws/board/topic/11097-setmobdata-getmobdata/
Again this is quite important for instances because many of the new instances boss's stats depend on the partysize. Here it is important to avoid those:
https://github.com/rathena/rathena/issues/462
https://github.com/rathena/rathena/issues/516
https://github.com/rathena/rathena/issues/751

I think there was a mobcontroller back in eA, but was removed long ago 

---

- [x] specialeffect3
is simple... special effect on specific mob

```
clif->specialeffect(map->id2bl(script_getnum(st,2)), script_getnum(st,3),AREA);
return true;
```

but I bet you can do it better xP

### PR DESCRIPTION
**Pull request by mekolat**
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

[//]: # (Note: Lines beginning with syntax such as this one, are comments and will not be visible in your report!)

### Pull Request Prelude

[//]: # (Thank you for working on improving Hercules!)

[//]: # (Please complete these steps and check the following boxes by putting an `x` inside the brackets _before_ filing your Pull Request.)

- [X] I have followed [proper Hercules code styling][code].
- [X] I have read and understood the [contribution guidelines][cont] before making this PR.
- [X] I am aware that this PR will be closed if the above-mentioned criteria are not fulfilled.

### Changes Proposed

* allow `specialeffect` to take any kind of unit
* allow `specialeffect` to send the effect to any player

This effectively allows us to deprecate all other effect commands in the future.

<br>

**Affected Branches:** `master`
**Issues addressed:** #1362 
**Type:** [enhancement](https://github.com/HerculesWS/Hercules/labels/type%3Aenhancement)
**Compopents:** [script engine](https://github.com/HerculesWS/Hercules/labels/component%3Acore%3Ascriptengine), [documentation](https://github.com/HerculesWS/Hercules/labels/component%3Adocumentation)

<br>

----
closes #1362 

[cont]: https://github.com/HerculesWS/Hercules/blob/master/CONTRIBUTING.md
[code]: https://github.com/HerculesWS/Hercules/wiki/Coding-Style

### CODE REVIEW

**Comment by HerculesWSAPI** [comment]
This change is [Reviewable](https://reviewable.io/reviews/herculesws/hercules/1746)

**Comment by dastgir** [comment]
Maybe we should deprecate specialeffect2 with this PR?

**Comment by mekolat** [comment]
@dastgir if we do that let's also deprecate `misceffect`, and maybe deprecate passing a string to specialeffect, with a `DeprecationWarning()`

**Comment by mekolat** [comment]
@dastgir @MishimaHaruna 
* I automatically (with `sed`) converted `specialeffect2()` to `specialeffect()`
* I manually converted `misceffect()` to `specialeffect()`

There is no longer any script using `specialeffect2()` or `misceffect()`... Do we mark those as deprecated?

**Comment by MishimaHaruna** [comment]
@mekolat yes please, mark them as deprecated in the usual way, in a separate commit. I don't think there's a point in keeping them, since they seem to be completely redundant now.

**Comment by mekolat** [comment]
@MishimaHaruna ok, will do

**Comment by mekolat** [comment]
@MishimaHaruna done & rebased too

**Comment by MishimaHaruna** [comment]
Thank you very much! Merging

**Comment by mekolat** [comment]
@MishimaHaruna why did you squash the commits?

**Comment by MishimaHaruna** [comment]
By accident, sorry. I reverted and re-merged it now, so that the history is preserved in the master branch. Having one large 9000-lines commit was completely useless.

**Pull request merged**
