### PR TITLE
Skill Fix Offertorium/Magnificat

### PR DESCRIPTION
**Pull request by Ridley8819**
Fixed SC_OFFERTORIUM and SC_MAGNIFICAT
They should cancel each other, not prevent the usage (like Kyrie and
Assumptio)

---
This change is [Reviewable](https://reviewable.io/reviews/herculesws/hercules/1222)

### CODE REVIEW

**Comment by Ridley8819** [comment]
wow, sorry, i'm still not used to git with its synch/pull xD
can i somehow remove the test commits?

**Comment by kriansa** [comment]
@Ridley8819 The common flow for feature/hotfix branching using github is:
- You fork the repo
- You create another branch (based on master)
- You push it into your repo
- You create the PR from your new branch to maintainer's master

Maybe it's worth reading: https://guides.github.com/introduction/flow/

**Comment by MishimaHaruna** [comment]
@dastgir or @Jedzkie , can you confirm this? I can merge it while squashing the line-noise commits once it's confirmed.

**Comment by Ridley8819** [comment]
@MishimaHaruna what exactly do you want to have confirmed? If it's about the skill description, Offertorium says the same about  Magnificat as Assumptio says about Kyrie:
http://www.divine-pride.net/database/skill/361/ab-offertorium
http://www.divine-pride.net/database/skill/361/hp-assumptio

**Comment by Ridley8819** [comment]
Wrong link for Offertorium 
http://www.divine-pride.net/database/skill/5011/ab-offertorium

**Comment by Ridley8819** [comment]
@MishimaHaruna 
https://youtu.be/QmMnDfqeHus?t=65
As you can see on his buff he has Magnificat applied. Once he casts Offertorium (1:14) Magnificat is cancled.
On 2:00 he casts Magnificat again, which cancles Offertorium

**Comment by MishimaHaruna** [comment]
Thank you @Ridley8819, merging this now

**Pull request closed without merging**
