### PR TITLE
Move questinfo data from map to npc_data

### PR DESCRIPTION
**Pull request by Asheraf**
### Pull Request Prelude

- [x] I have followed [proper Hercules code styling][code].
- [x] I have read and understood the [contribution guidelines][cont] before making this PR.
- [x] I am aware that this PR may be closed if the above-mentioned criteria are not fulfilled.

### Issues addressed
https://github.com/HerculesWS/Hercules/issues/2431

### Changes Proposed
fix memory leak in setquestinfo

[cont]: https://github.com/HerculesWS/Hercules/blob/master/CONTRIBUTING.md
[code]: https://github.com/HerculesWS/Hercules/wiki/Coding-Style

### CODE REVIEW

**Comment by HerculesWSAPI** [comment]
This change is [Reviewable](https://reviewable.io/reviews/herculesws/hercules/2433)

**Comment by Asheraf** [comment]
@AnnieRuru can you check if this fixes your problem.

**Comment by AnnieRuru** [comment]
no, still the same 
```
Memory manager: Memory leaks found at 2019/04/11 10h36m10s (Git rev 'ab81d4012eac5c2c00c485971fc9b89bf69761be').
0001 : d:\ragnarok\hercules\src\map\map.c line 5986 size 744 address 0x043A1604
0002 : d:\ragnarok\hercules\src\map\script.c line 21344 size 8 address 0x06D0015C
0003 : d:\ragnarok\hercules\src\map\script.c line 21300 size 12 address 0x06D0453C
```
note the line number is different than in the issue, as I have apply your patch

also you can test it yourself by type atcommand `@mapexit`
and open `log/map-server.exe.leaks` file

```
prontera,155,180,5	script	sdfasdf	1_F_MARIA,{
	end;
OnInit:
	questinfo QTYPE_QUEST, 1;
	setquestinfo QINFO_QUEST, 1001, 1;
	questinfo QTYPE_QUEST, 1;
	setquestinfo QINFO_ITEM, Apple, 1, 30000;
	end;
}
```

**Comment by Asheraf** [comment]
@AnnieRuru this should fix the memory leak for now, but seems like I found another "bug" i will try to do an update later, hopefully before next release date.

**Comment by AnnieRuru** [comment]
... urgh ... okay ... because this still doesn't fix the memory leak yet though ...
```
Memory manager: Memory leaks found at 2019/04/12 20h24m31s (Git rev 'ab81d4012eac5c2c00c485971fc9b89bf69761be').
0001 : d:\ragnarok\hercules\src\map\map.c line 6036 size 744 address 0x04EC1624
0002 : d:\ragnarok\hercules\src\map\script.c line 21344 size 8 address 0x0890C53C
0003 : d:\ragnarok\hercules\src\map\script.c line 21300 size 12 address 0x0890C55C
```
but at least I see the code clean up, and know where the responsible code for it

**Comment by Asheraf** [comment]
@AnnieRuru I have moved this around to fix a bug i missed last time, memory leaks should be fixed too, let me know if you find other problems.

**Pull request merged**
