### PR TITLE
Added official effect of Mora Berry.

### PR DESCRIPTION
**Pull request by Jedzkie**

### CODE REVIEW

**Comment by Jedzkie** [comment]
in case curious of mob entry in SC_MORA_BUFF,

Buff "EFST_MORA_BUFF"  // ?? ??
	event OnStartEquip:
		SubDamage_Name User MIMING 50
		SubDamage_Name User LITTLE_FATUM 50
		SubDamage_Name User PARUS 50
		SubDamage_Name User ANGRA_MANTIS 50
		SubDamage_Name User POM_SPIDER 50
	return
	event OnFinishEquip:
		AddDamage_Name User MIMING 50
		AddDamage_Name User LITTLE_FATUM 50
		AddDamage_Name User PARUS 50
		AddDamage_Name User ANGRA_MANTIS 50
		AddDamage_Name User POM_SPIDER 50
	return

**Comment by dastgir** [comment]
I now feel the need of status change documentation :x with descriptions of val1-val4,
Anw, 
Commit seems good

**Comment by AnnieRuru** [comment]
tested and working fine

**Comment by Jedzkie** [comment]
Ill update this tomorrow thank you @annieruru

**Comment by MishimaHaruna** [comment]
Okay, I'll take care of those minor edits while merging, the rest looks good.

**Comment by MishimaHaruna** [comment]
Merged as 8924522fe29079a66f4d9b6d88b50bcdadf7df9a

**Pull request closed without merging**
