### PR TITLE
CR_GRANDCROSS

### PR DESCRIPTION
**Pull request by violetharmony**
### Pull Request Prelude

- [ ] I have followed [proper Hercules code styling][code].
- [ ] I have read and understood the [contribution guidelines][cont] before making this PR.
- [ ] I am aware that this PR may be closed if the above-mentioned criteria are not fulfilled.

### Changes Proposed

**Issues addressed:** 

http://violet-harmony.blogspot.com/2017/

[cont]: https://github.com/HerculesWS/Hercules/blob/master/CONTRIBUTING.md
[code]: https://github.com/HerculesWS/Hercules/wiki/Coding-Style

### CODE REVIEW

**Comment by HerculesWSAPI** [comment]
This change is [Reviewable](https://reviewable.io/reviews/herculesws/hercules/2340)

**Comment by 4144** [comment]
please use one commit for small changes and not split them to many commits.
also please don't add your nick in useless comments.

**Comment by dastgirp** [comment]
Please add proper source too

**Comment by Asheraf** [comment]
closed for the same reason as #2338

**Pull request closed without merging**
