### PR TITLE
Added RG King's Grace cooldown

### PR DESCRIPTION
**Pull request by Ridley8819**
closes #1246
reference:
http://irowiki.org/wiki/King's_Grace

---
This change is [Reviewable](https://reviewable.io/reviews/herculesws/hercules/1466)

### CODE REVIEW

**Comment by dastgir** [comment]
As per IRC talk, we need those extra Level defined. you can just leave those as it is.
@hemagx or @MishimaHaruna would be able to better explain those LvX: lines

**Comment by dastgir** [comment]
@Ridley8819 those lines were added in https://github.com/HerculesWS/Hercules/commit/61a240c20d46c00ee93b6861c1dfcfce5683ff15 from PR https://github.com/HerculesWS/Hercules/pull/1352 , so this one would revert the fix, so, better leave it,
We just need Cooldown thing from this PR

**Comment by Ridley8819** [comment]
From what I talked with @4144 they aren't needed, that's why I removed them in the first place.

**Comment by Ridley8819** [comment]
1st commit removed, this now only adds CD for King's Grace

**Comment by Ridley8819** [comment]
@dastgir

**Pull request merged**
