### PR TITLE
Add support for Ragnarok zero clients, split packets.h again

### PR DESCRIPTION
**Pull request by 4144**
### Pull Request Prelude

- [x] I have followed [proper Hercules code styling][code].
- [x] I have read and understood the [contribution guidelines][cont] before making this PR.
- [x] I am aware that this PR will be closed if the above-mentioned criteria are not fulfilled.

### Changes Proposed

Add fake OTP login packet for support Ragnarok zero clients.
Add shuffle and non shuffle packets for Ragnarok zero clients (for all versions) into packet table.
Add shuffle and non shuffle packets for latest ragexeRE clients.
Split packets.h to packets.h and packets_shuffle.h. It allow simpler add support for other client types. And in future it will allow do better packets validation.
Add configure switch for enable zero clients packets support (--enable-packetver-zero).
Fixed minor issues like missing comments or wrong field sizes.

### CODE REVIEW

**Comment by HerculesWSAPI** [comment]
This change is [Reviewable](https://reviewable.io/reviews/herculesws/hercules/1923)

**Comment by 4144** [comment]
Patches for client will be published bit after.

**Comment by Asheraf** [comment]
Tested the new `2017-11-29aRagexeRE` as well and seems working fine

**Comment by JulioCF** [comment]
thanks!

**Comment by 4144** [comment]
Nemo patches released https://gitlab.com/4144/Nemo
One zero client can be found in herc.ws topic with unpacked clients.

**Comment by 4144** [comment]
for build with zero client support, need run configure like this:
```
./configure --enable-packetver-zero
```

**Comment by OmarAcero** [comment]
@4144  Sir, there is some way to make the new Nemo Patches read also the system/lub or lua files, because almost all the patches are working with the exception of reading iteminfo.lub and the cashshop button.The names and descriptions of the items show out in Korean.
Note: [Working 90%](https://imgur.com/a/vQSBK).

**Comment by 4144** [comment]
@OmarAcero for this exists any non working patches in nemo?

**Comment by 4144** [comment]
From lua files i see in code System/iteminfo_true.lub.
Try translate this file

**Comment by OmarAcero** [comment]
@4144  Only with ragnarok_zero clients are not working the patches  of: "load system/iteminfo.lub or .lua" and "restore cashshop button".

**Comment by 4144** [comment]
@OmarAcero i fixed patch "Load Custom lua file instead of iteminfo*.lub"
Not tested

**Comment by OmarAcero** [comment]
@4144  Thank you very much Sir, everything working correctly ... Now only it would be necessary to adjust the patch of "Restore Cash Shop Icon". And the exe would already be patched as the original exe.

**Pull request merged**
