### PR TITLE
In official, novice don't have job level stat bonus

### PR DESCRIPTION
**Pull request by Jedzkie**
### Pull Request Prelude

- [x] I have followed [proper Hercules code styling][code].
- [x] I have read and understood the [contribution guidelines][cont] before making this PR.
- [x] I am aware that this PR may be closed if the above-mentioned criteria are not fulfilled.

### Changes Proposed

**Issues addressed:** 

[cont]: https://github.com/HerculesWS/Hercules/blob/master/CONTRIBUTING.md
[code]: https://github.com/HerculesWS/Hercules/wiki/Coding-Style

### CODE REVIEW

**Comment by MishimaHaruna** [comment]
Is this true for both renewal and pre-renewal?

**Comment by Jedzkie** [comment]
Yes.

**Comment by Jedzkie** [comment]
@MishimaHaruna screenshot from pre-renewal aegis.
screenRagnarok000

**Comment by MishimaHaruna** [comment]
Alright, thank you! I'm merging this now, ahead of the next release

**Pull request merged**
