### PR TITLE
Fixes Equip Switch Bug for quest shop

### PR DESCRIPTION
**Pull request by SamuelHercules**
as stated at http://herc.ws/board/topic/13459-good-day-preview-bug-quest-shop-npc/

---

This change is [Reviewable](https://reviewable.io/reviews/herculesws/hercules/1475)

### CODE REVIEW

**Comment by Emistry** [comment]
hmm i think the issue would still exist, like this here.
https://github.com/HerculesWS/Hercules/issues/1221

**Comment by Asheraf** [comment]
@emistry then spaming the equipment would break It?

**Comment by SamuelHercules** [comment]
@Asheraf done edit

**Comment by Ridley8819** [comment]
I'll doubt this change will make the script running as intended, it seems it has more flaws, but I'm not sure how we handle scripts from the custom folder?
@MishimaHaruna? We talked about this before

**Comment by Ridley8819** [comment]
Since I'm not sure how are the future plans for support of the custom is handled, I'm closing this. But thank you for your intention to improve this!

**Pull request closed without merging**
