### PR TITLE
Battleground Data to HPM Struct

### PR DESCRIPTION
**Pull request by dastgir**
@MishimaHaruna , Can you review this?

### CODE REVIEW

**Comment by dastgir** [comment]
@shennetsind , hope you could or @MishimaHaruna  could review this :)

**Comment by shennetsind** [comment]
Can you give me a example of where this'd be used/useful?

**Comment by dastgir** [comment]
I have made this for eBG I am currently doing, which like, I can associate BG team Id with a guild Id.
Associate a BG Leader per team.
So I need to add some variables to struct, thus this is important

**Comment by shennetsind** [comment]
Very well. your contribution is much appreciated

**Pull request merged**
