### PR TITLE
Fix script loading via sql in itemdb.c

### PR DESCRIPTION
**Pull request by Smokexyz**
This fixes the script loading issue mentioned here -> http://herc.ws/board/topic/10249-issue-with-item-db-after-update/

### CODE REVIEW

**Comment by dastgir** [comment]
Could you change the commit name according to the fix made?

**Comment by Smokexyz** [comment]
how is it not describing the fix made?

**Comment by dastgir** [comment]
Oops. I am blind. :x

**Comment by dastgir** [comment]
Merged. Thanks for distribution

**Pull request merged**
