### PR TITLE
- Update the Status Icons based in kRO Update 10-21-2015.

### PR DESCRIPTION
**Pull request by Jedzkie**
- Update 2 new costume items:
  • Ljosalfar (ID# 20099)
  • Mermaid Bubbles (ID# 20209)

Signed-off-by: Jedzkie <jedzkie13@rocketmail.com>

### CODE REVIEW

**Comment by Jedzkie** [comment]
<b>Ljosalfar</b>
<a href="http://tinypic.com?ref=35384qo" target="_blank">Image and video hosting by TinyPic</a>

<b>Mermaid Bubbles</b>
<a href="http://tinypic.com?ref=oi516s" target="_blank">Image and video hosting by TinyPic</a>

**Comment by dastgir** [comment]
Squash into one and it will be merged.

**Comment by kyeme** [comment]
@Jedzkie 
Only works in 10-21-2015 client ?

**Comment by dastgir** [comment]
Maybe it should work on 2015 clients(any 2015, might also work on 2014-10, not tested on that), since those status are recent one's

**Comment by Jedzkie** [comment]
@kyeme Nope, I use 2015-05-13aRagexe

**Comment by kyeme** [comment]
Nice... Thanks.

**Comment by dastgir** [comment]
Merged. Thanks for Contribution.

**Pull request merged**
