### PR TITLE
Make IT_CASH not stackable

### PR DESCRIPTION
**Pull request by mekolat**
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

[//]: # (Note: Lines beginning with syntax such as this one, are comments and will not be visible in your report!)

### Pull Request Prelude

- [X] I have followed [proper Hercules code styling][code].
- [X] I have read and understood the [contribution guidelines][cont] before making this PR.
- [X] I am aware that this PR will be closed if the above-mentioned criteria are not fulfilled.

### Changes Proposed

Apparently all box items should be non-stackable. Can anyone confirm?

http://herc.ws/board/topic/14869-how-to-force-boxes-to-non-stackable/

> \<VyLow\>
 its just that in official server all usable boxes dont stack and hopefully herc will have a fix for this heh

[cont]: https://github.com/HerculesWS/Hercules/blob/master/CONTRIBUTING.md
[code]: https://github.com/HerculesWS/Hercules/wiki/Coding-Style

### CODE REVIEW

**Comment by HerculesWSAPI** [comment]
This change is [Reviewable](https://reviewable.io/reviews/herculesws/hercules/1769)

**Comment by dastgir** [comment]
Something related: https://github.com/HerculesWS/Hercules/pull/973

**Comment by Jedzkie** [comment]
Found a bug, when you bought more than 1 of the item, you'll get only 1.

**Comment by Jedzkie** [comment]
@mekolat

**Comment by MishimaHaruna** [comment]
It seems that in official servers, the `IT_CASH` items are normally stackable, but in some cases a per-item setting (equivalent to our `ForceSerial`) is overridden by the administrators (in case they want to track the contents of specific box types).
This, according to official server observation (this is from third party observation, doesn't come from my personal experience), is noticeable with certain Battle Manuals, that appear to stack in batches of 10 (the amount in each box), since they keep their creating box's serial number.

Since the ForceSerial flag already exists and can be used by server administrators to reproduce the desired behavior (may they wish for that kind of clutter in their databases), I'll be closing this PR.

**Pull request closed without merging**
