### PR TITLE
Added official effect for Buche De Noel item. (SC_BUCHEDENOEL)

### PR DESCRIPTION
**Pull request by Jedzkie**

### CODE REVIEW

**Comment by AnnieRuru** [comment]
no good, previously it added the value like this
```
prontera,155,185,5	script	kdjsfhkshf	1_F_MARIA,{
	sc_end SC_ALL;
	sc_start4 SC_BUCHEDENOEL, 600000, 3, 3, 3, 7;
//	sc_start SC_INCMHPRATE,600000,3;
//	sc_start SC_INCMSPRATE,600000,3;
//	sc_start SC_INCHITRATE,600000,3;
//	sc_start SC_CRITICALPERCENT,600000,7;
}
```
in the comment one, I saw my Critical in player status screen from 1 into 8
but when I use yours, the value went from 1 into 2

something not right

**Comment by Jedzkie** [comment]
Thanks for the Report, Going to fix this.

**Comment by Jedzkie** [comment]
@AnnieRuru Done.

**Comment by AnnieRuru** [comment]
still no good
```
	if (sc->data[SC_BUCHEDENOEL]) {
		ShowDebug( "%d", sc->data[SC_BUCHEDENOEL]->val4 );
		critical += sc->data[SC_BUCHEDENOEL]->val4 *10;
	}
```
I tested it needs to *10 the value in order for the value to display properly in status window

hmm ... ok now have to recheck all status in `status_calc_critical` function
because I found that the *10 is from crusader spear quicken

**Comment by Jedzkie** [comment]
Omggggggggg... -.- whyyyyy!?!?!?!?!?!

**Comment by AnnieRuru** [comment]
because there is no documentation, or comments on top of that function ;-)
so obviously everyone did wrong
I also noticed this line
`return (short)cap_value(critical,10,SHRT_MAX);`
it cap the minimum value at 10,
it can't mean you have 10 critical at minimum, right ?

**Comment by dastgir** [comment]
What I suggest is, if 2 PR changes SC, make them into 1 PR(but not 1 commit)
, like if #958 gets merged before this, then this one will be conflicted, else that one will be conflicted.

Just my thought

**Comment by AnnieRuru** [comment]
we can always force commit in PR to resolve conflicts ^.^

**Comment by Jedzkie** [comment]
@dastgir okay next time.

**Comment by MishimaHaruna** [comment]
What's the status of this? I can resolve the merge conflicts, but is the implementation correct?

**Comment by AnnieRuru** [comment]
nope, @MishimaHaruna , this PR is bug
also all the status change in `status_calc_critical` need to review again
https://github.com/HerculesWS/Hercules/blob/master/src/map/status.c#L4888
there are no comment on top of the function to remind others to `*10` the value for the critical

in order to add 1 critical from a status change, has to do 
`critical += sc->data[SC_WHATEVER]->val1 *10;`
but in that function, some did the *`10`, some didn't
in this PR, Jedzkie didn't do the `*10`

**Comment by dastgir** [comment]
This is what happens when we lack proper documentation...

**Comment by Jedzkie** [comment]
Found this @AnnieRuru in status.c

case SC_PLUSAVOIDVALUE:
case SC_CRITICALPERCENT:
	val2 = val1*10; //Actual boost (since 100% = 1000)
	break;

**Comment by AnnieRuru** [comment]
its useless to tell me LOL, I'm scripting mod, not a developer
I only write custom stuffs

... I am soo speechless, why not just `*10` inside `status_calc_critical`
but have to `*10` inside `status_change_start` ... ?
and confirm only some of them has `*10` inside `status_change_start`
which makes this a culprit

I don't have aegis or official information about these kinda thing, I can't do this =/

**Pull request closed without merging**
