### PR TITLE
Monster hp bar fix

### PR DESCRIPTION
**Pull request by Jedzkie**
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

[//]: # (Note: Lines beginning with syntax such as this one, are comments and will not be visible in your report!)

### Pull Request Prelude

[//]: # (Thank you for working on improving Hercules!)

[//]: # (Please complete these steps and check the following boxes by putting an `x` inside the brackets _before_ filing your Pull Request.)

- [x] I have followed [proper Hercules code styling][code].
- [x] I have read and understood the [contribution guidelines][cont] before making this PR.
- [x] I am aware that this PR will be closed if the above-mentioned criteria are not fulfilled.

### Changes Proposed
In official servers, monster hp bar is not shown when you hit MVP Monsters.

[//]: # (Describe at length, the changes that this pull request makes.)

**Affected Branches:** 
master

[//]: # (Master? Slave?)

**Issues addressed:**

[//]: # (Issue Tracker Number if any.)

### Known Issues and TODO List

[//]: # (Insert checklist here)
[//]: # (Syntax: - [ ] Checkbox)

[//]: # (**NOTE** Enable the setting "[√] Allow edits from maintainers." when creating your pull request if you have not already enabled it.)

[cont]: https://github.com/HerculesWS/Hercules/blob/master/CONTRIBUTING.md
[code]: https://github.com/HerculesWS/Hercules/wiki/Coding-Style

### CODE REVIEW

**Comment by HerculesWSAPI** [comment]
This change is [Reviewable](https://reviewable.io/reviews/herculesws/hercules/2008)

**Comment by AnnieRuru** [comment]
can we do this as battle_config ?
or else members will start complaining suddenly seeing a feature they used to and suddenly it disappear

also, MD_BOSS also included mini-bosses like Angeling, Mastering, Chimera, Bloody Knight, etc...
make sure you check

**Comment by Jedzkie** [comment]
@AnnieRuru sure. Yeah, mini boss also don't have hp bars. even emperiums and barricades

**Comment by tlacson7** [comment]
how about emperium?

**Comment by Jedzkie** [comment]
@tlacson7 even emperiums doesn't have hp bar. only normal monsters.

**Comment by AnnieRuru** [comment]
that's why I also felt like rathena did the wrong way
they use `hidemobhpbar` mapflag

I think the correct way is just hiding the specific ID of monsters...
can you confirm WoE guardian also has hp bar ?

**Comment by 4144** [comment]
then probably add flag into mob_db to show/hide hp bar?

**Pull request closed without merging**
