### PR TITLE
(WIP) Fix signed item documentation

### PR DESCRIPTION
**Pull request by AnnieRuru**
[cont]: https://github.com/HerculesWS/Hercules/blob/master/CONTRIBUTING.md
[code]: https://github.com/HerculesWS/Hercules/wiki/Coding-Style
### Pull Request Prelude
- [x] I have followed [proper Hercules code styling][code].
- [x] I have read and understood the [contribution guidelines][cont] before making this PR.
- [x] I am aware that this PR will be closed if the above-mentioned criteria are not fulfilled.

### Issues addressed
signed item no longer use bitmask, we only need to directly read from the .@card3 value

### Changes Proposed
Fix WTF is happening in the documentation

### Affected Branches
* Master

### Known Issues and TODO List
then WTF is the .@card4 still having >>16 there ?
(getnameditem) in script.c
```
	item_tmp.nameid=nameid;
	item_tmp.amount=1;
	item_tmp.identify=1;
	item_tmp.card[0]=CARD0_CREATE; //we don't use 255! because for example SIGNED WEAPON shouldn't get TOP10 BS Fame bonus [Lupus]
	item_tmp.card[2]=tsd->status.char_id;
	item_tmp.card[3]=tsd->status.char_id >> 16;
```

### CODE REVIEW

**Comment by HerculesWSAPI** [comment]
This change is [Reviewable](https://reviewable.io/reviews/herculesws/hercules/2359)

**Comment by 4144** [comment]
now all id is not ``short`` (2 bytes) as before but ``int`` (4 bytes)
for old clients can be issue if some crafted id will be not in range for ``short`` types

**Comment by AnnieRuru** [comment]
yes, I know we have Item ID as int(11) field

so you admit this change has broke old clients =.=
my suspicion is correct

**Comment by AnnieRuru** [comment]
superseded by https://github.com/HerculesWS/Hercules/pull/2425

**Pull request closed without merging**
