### PR TITLE
Implementation of Private AirShip

### PR DESCRIPTION
**Pull request by Asheraf**
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

[//]: # (Note: Lines beginning with syntax such as this one, are comments and will not be visible in your report!)

### Pull Request Prelude

[//]: # (Thank you for working on improving Hercules!)

[//]: # (Please complete these steps and check the following boxes by putting an `x` inside the brackets _before_ filing your Pull Request.)

- [x] I have followed [proper Hercules code styling][code].
- [x] I have read and understood the [contribution guidelines][cont] before making this PR.
- [x] I am aware that this PR will be closed if the above-mentioned criteria are not fulfilled.

### Changes Proposed

Do not merge until maps list is updated to main servers.

[cont]: https://github.com/HerculesWS/Hercules/blob/master/CONTRIBUTING.md
[code]: https://github.com/HerculesWS/Hercules/wiki/Coding-Style

### CODE REVIEW

**Comment by HerculesWSAPI** [comment]
This change is [Reviewable](https://reviewable.io/reviews/herculesws/hercules/1998)

**Comment by Emistry** [comment]
Review status: 0 of 9 files reviewed at latest revision, all discussions resolved.

---

*[db/constants.conf, line 3881 at r1](https://beta.reviewable.io/reviews/herculesws/hercules/1998#-L8VCLlL9zCwce02lKjq:-L8VCLlL9zCwce02lKjr:b6paa8t) ([raw file](https://github.com/herculesws/hercules/blob/f8160b5c556c121a269e7a20640666217450a49b/db/constants.conf#L3881)):*
> comment__: "Private AirShip Respond"
> 	PAIRSHIP_NONE:               0
> 	PAIRSHIP_TRYAGAIN:           1
> 	PAIRSHIP_INVALID_STARTMAP:   2
> 	PAIRSHIP_INVALID_ENDMAP:     3
> 	PAIRSHIP_NOTENOUGH_ITEMS:    4
> 	PAIRSHIP_INVALID_ITEM:       5

Perhaps change into these? word shall be separated with `_`.
```
comment__: "Private AirShip Respond"
P_AIRSHIP_NONE:					0
P_AIRSHIP_RETRY:				1
P_AIRSHIP_INVALID_START_MAP:	2
P_AIRSHIP_INVALID_END_MAP:		3
P_AIRSHIP_ITEM_NOT_ENOUGH:		4
P_AIRSHIP_ITEM_INVALID:			5
```
since its flag, maybe a `FLAG_` prefix to?

---

*[doc/script_commands.txt, line 9997 at r1](https://beta.reviewable.io/reviews/herculesws/hercules/1998#-L8VDoZbC2YgP12sQQxu:-L8VDoZbC2YgP12sQQxv:b-dheip) ([raw file](https://github.com/herculesws/hercules/blob/f8160b5c556c121a269e7a20640666217450a49b/doc/script_commands.txt#L9997)):*
> PAIRSHIP_NONE
> 	PAIRSHIP_TRYAGAIN
> 	PAIRSHIP_INVALID_STARTMAP
> 	PAIRSHIP_INVALID_ENDMAP
> 	PAIRSHIP_NOTENOUGH_ITEMS
> 	PAIRSHIP_INVALID_ITEM

Perhaps change into these? word shall be separated with `_`.
```
P_AIRSHIP_NONE
P_AIRSHIP_RETRY
P_AIRSHIP_INVALID_START_MAP
P_AIRSHIP_INVALID_END_MAP
P_AIRSHIP_ITEM_NOT_ENOUGH
P_AIRSHIP_ITEM_INVALID
```
since its flag, maybe a `FLAG_` prefix to?

---

*[npc/other/private_airship.txt, line 34 at r1](https://beta.reviewable.io/reviews/herculesws/hercules/1998#-L8VDGwB8pP_o1NDfyKs:-L8VDGwC6MsrG3j6CAY3:bkmbmwf) ([raw file](https://github.com/herculesws/hercules/blob/f8160b5c556c121a269e7a20640666217450a49b/npc/other/private_airship.txt#L34)):*
> OnAirShipIsNeedItem:

change to `S_AirShipIsNeedItem:`

---

*[npc/other/private_airship.txt, line 41 at r1](https://beta.reviewable.io/reviews/herculesws/hercules/1998#-L8VDSWbDN6-8LCrOgHA:-L8VDSWbDN6-8LCrOgHB:b-eujlkr) ([raw file](https://github.com/herculesws/hercules/blob/f8160b5c556c121a269e7a20640666217450a49b/npc/other/private_airship.txt#L41)):*
> OnAirShipIsStartableMap:

change to `S_AirShipStartableMap:`

---

*[npc/other/private_airship.txt, line 52 at r1](https://beta.reviewable.io/reviews/herculesws/hercules/1998#-L8VEEqSCEiXMtkVXkHP:-L8VE74bEI3copY-iHFN:b-npce6z) ([raw file](https://github.com/herculesws/hercules/blob/f8160b5c556c121a269e7a20640666217450a49b/npc/other/private_airship.txt#L52)):*
> OnAirShipIsEndableMap:

change to `S_AirShipEndableMap:`

---

*[npc/other/private_airship.txt, line 65 at r1](https://beta.reviewable.io/reviews/herculesws/hercules/1998#-L8VEGXtCatsgQj2CZM1:-L8VEGXtCatsgQj2CZM2:b-y6pf7h) ([raw file](https://github.com/herculesws/hercules/blob/f8160b5c556c121a269e7a20640666217450a49b/npc/other/private_airship.txt#L65)):*
> ```
> 
> OnAirShipRequest:
> 	if (callsub(OnAirShipIsNeedItem) == false) {
> ```

`callsub(S_AirShipIsNeedItem)`

---

*[npc/other/private_airship.txt, line 73 at r1](https://beta.reviewable.io/reviews/herculesws/hercules/1998#-L8VERBj4SI_GugiIPNB:-L8VERBj4SI_GugiIPNC:bperph6) ([raw file](https://github.com/herculesws/hercules/blob/f8160b5c556c121a269e7a20640666217450a49b/npc/other/private_airship.txt#L73)):*
> ```
> 		end;
> 	}
> 	if (callsub(OnAirShipIsStartableMap) == false) {
> ```

`callsub(S_AirShipIsStartableMap)`

---

*[npc/other/private_airship.txt, line 77 at r1](https://beta.reviewable.io/reviews/herculesws/hercules/1998#-L8VEVDa-r9yd1M8JswL:-L8VEVDa-r9yd1M8JswM:b-fjn7c9) ([raw file](https://github.com/herculesws/hercules/blob/f8160b5c556c121a269e7a20640666217450a49b/npc/other/private_airship.txt#L77)):*
> ```
> 		end;
> 	}
> 	if (callsub(OnAirShipIsEndableMap) == false) {
> ```

`callsub(S_AirShipEndableMap)`

---

*[npc/other/private_airship.txt, line 87 at r1](https://beta.reviewable.io/reviews/herculesws/hercules/1998#-L8VEdGdBcYgXD8vyTfS:-L8VEdGdBcYgXD8vyTfT:b-h3ck7f) ([raw file](https://github.com/herculesws/hercules/blob/f8160b5c556c121a269e7a20640666217450a49b/npc/other/private_airship.txt#L87)):*
> .NeedItem

`.needitem`, variable shall be in lowercase letters

---

*[npc/other/private_airship.txt, line 88 at r1](https://beta.reviewable.io/reviews/herculesws/hercules/1998#-L8VEtHb7F2HWhlx6FUx:-L8VEtHb7F2HWhlx6FUy:b-824m59) ([raw file](https://github.com/herculesws/hercules/blob/f8160b5c556c121a269e7a20640666217450a49b/npc/other/private_airship.txt#L88)):*
> .StartableMap$

`.startablemap$`, variable shall be in lowercase letters

---

*[npc/other/private_airship.txt, line 437 at r1](https://beta.reviewable.io/reviews/herculesws/hercules/1998#-L8VEyIb14vFJJ2jWcZp:-L8VEyIb14vFJJ2jWcZq:b-dg1r7d) ([raw file](https://github.com/herculesws/hercules/blob/f8160b5c556c121a269e7a20640666217450a49b/npc/other/private_airship.txt#L437)):*
> .EndableMap$

`.endablemap$`

---

*[npc/other/private_airship.txt, line 787 at r1](https://beta.reviewable.io/reviews/herculesws/hercules/1998#-L8VF56U6idQYowVisGP:-L8VF56U6idQYowVisGQ:b-i6o9um) ([raw file](https://github.com/herculesws/hercules/blob/f8160b5c556c121a269e7a20640666217450a49b/npc/other/private_airship.txt#L787)):*
> ```
> 	);
> 	end;
> }
> ```

need End of Line (EOL)

---

*[src/map/clif.c, line 20239 at r1](https://beta.reviewable.io/reviews/herculesws/hercules/1998#-L8VFBYB8NlhyCiG1TSB:-L8VFBYB8NlhyCiG1TSC:b4pz8aw) ([raw file](https://github.com/herculesws/hercules/blob/f8160b5c556c121a269e7a20640666217450a49b/src/map/clif.c#L20239)):*
> ```C
> 	const struct PACKET_CZ_PRIVATE_AIRSHIP_REQUEST *p = RP2PTR(fd);
> 
> 	safestrncpy(evname, "private_airship::OnAirShipRequest", EVENT_NAME_LENGTH);
> ```

other than hardcode the npc name, maybe consider an event label? shall avoid hardcoded content.

---

*[src/map/clif.c, line 20259 at r1](https://beta.reviewable.io/reviews/herculesws/hercules/1998#-L8VF_So5ak_OCk-SZkw:-L8VF_So5ak_OCk-SZkx:b-wun17k) ([raw file](https://github.com/herculesws/hercules/blob/f8160b5c556c121a269e7a20640666217450a49b/src/map/clif.c#L20259)):*
> ```C
> 	nullpo_retv(sd);
> 
> 	if (flag > 5) {
> ```

maybe replace the `if (flag > 5)` by adding the enum into src?
something like `if (flag > P_AIRSHIP_ITEM_INVALID)` 
better readability

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/herculesws/hercules/1998)*

**Comment by Emistry** [comment]
General case preferences can be found here.
https://github.com/HerculesWS/Hercules/issues/685#issuecomment-136308412

**Comment by MishimaHaruna** [comment]
What criteria were used to choose the available start and destination maps? Is there any way to avoid those hardcoded lists (i.e. do the maps have some existing flag in common? Would it be worth adding a new mapflag?)

**Comment by Asheraf** [comment]
@MishimaHaruna this list is from [client lua files](https://github.com/Asheraf/Translation/blob/master/System/PrivateAirplane_Sakray.lub)  im not sure if there is something in common between these maps as there is Towns, Fields, Dungeons.. perhaps a better implementation would be to create a new map zone and add them to it and check via `getmapinfo(MAPINFO_ZONE)` to avoid the too many searchs, i'll update this later when it's merged in kRO main servers (currently exist only in zero and sakray).

**Comment by Asheraf** [comment]
Review status: 0 of 16 files reviewed at latest revision, 14 unresolved discussions.

---

*[db/constants.conf, line 3881 at r1](https://reviewable.io/reviews/herculesws/hercules/1998#-L8VCLlL9zCwce02lKjq:-LBfewsyEaJXD9M3mJZF:b-896fix) ([raw file](https://github.com/herculesws/hercules/blob/f8160b5c556c121a269e7a20640666217450a49b/db/constants.conf#L3881)):*
<details><summary><i>Previously, Emistry (Emistry Haoyan) wrote…</i></summary><blockquote>

> comment__: "Private AirShip Respond"
> 	PAIRSHIP_NONE:               0
> 	PAIRSHIP_TRYAGAIN:           1
> 	PAIRSHIP_INVALID_STARTMAP:   2
> 	PAIRSHIP_INVALID_ENDMAP:     3
> 	PAIRSHIP_NOTENOUGH_ITEMS:    4
> 	PAIRSHIP_INVALID_ITEM:       5

Perhaps change into these? word shall be separated with `_`.
```
comment__: "Private AirShip Respond"
P_AIRSHIP_NONE:					0
P_AIRSHIP_RETRY:				1
P_AIRSHIP_INVALID_START_MAP:	2
P_AIRSHIP_INVALID_END_MAP:		3
P_AIRSHIP_ITEM_NOT_ENOUGH:		4
P_AIRSHIP_ITEM_INVALID:			5
```
since its flag, maybe a `FLAG_` prefix to?
</blockquote></details>

Done.

---

*[doc/script_commands.txt, line 9997 at r1](https://reviewable.io/reviews/herculesws/hercules/1998#-L8VDoZbC2YgP12sQQxu:-LBfeypC9gUmPAyzVkey:b-896fix) ([raw file](https://github.com/herculesws/hercules/blob/f8160b5c556c121a269e7a20640666217450a49b/doc/script_commands.txt#L9997)):*
<details><summary><i>Previously, Emistry (Emistry Haoyan) wrote…</i></summary><blockquote>

> PAIRSHIP_NONE
> 	PAIRSHIP_TRYAGAIN
> 	PAIRSHIP_INVALID_STARTMAP
> 	PAIRSHIP_INVALID_ENDMAP
> 	PAIRSHIP_NOTENOUGH_ITEMS
> 	PAIRSHIP_INVALID_ITEM

Perhaps change into these? word shall be separated with `_`.
```
P_AIRSHIP_NONE
P_AIRSHIP_RETRY
P_AIRSHIP_INVALID_START_MAP
P_AIRSHIP_INVALID_END_MAP
P_AIRSHIP_ITEM_NOT_ENOUGH
P_AIRSHIP_ITEM_INVALID
```
since its flag, maybe a `FLAG_` prefix to?
</blockquote></details>

Done.

---

*[npc/other/private_airship.txt, line 34 at r1](https://reviewable.io/reviews/herculesws/hercules/1998#-L8VDGwB8pP_o1NDfyKs:-LBff1r66UHT_pSvXr7q:b-896fix) ([raw file](https://github.com/herculesws/hercules/blob/f8160b5c556c121a269e7a20640666217450a49b/npc/other/private_airship.txt#L34)):*
<details><summary><i>Previously, Emistry (Emistry Haoyan) wrote…</i></summary><blockquote>

> OnAirShipIsNeedItem:

change to `S_AirShipIsNeedItem:`
</blockquote></details>

Done.

---

*[npc/other/private_airship.txt, line 41 at r1](https://reviewable.io/reviews/herculesws/hercules/1998#-L8VDSWbDN6-8LCrOgHA:-LBff4Ld1Y-lA8HUZEVV:b-896fix) ([raw file](https://github.com/herculesws/hercules/blob/f8160b5c556c121a269e7a20640666217450a49b/npc/other/private_airship.txt#L41)):*
<details><summary><i>Previously, Emistry (Emistry Haoyan) wrote…</i></summary><blockquote>

> OnAirShipIsStartableMap:

change to `S_AirShipStartableMap:`
</blockquote></details>

Done.

---

*[npc/other/private_airship.txt, line 52 at r1](https://reviewable.io/reviews/herculesws/hercules/1998#-L8VEEqSCEiXMtkVXkHP:-LBff4w29qutyL08VTQm:b-896fix) ([raw file](https://github.com/herculesws/hercules/blob/f8160b5c556c121a269e7a20640666217450a49b/npc/other/private_airship.txt#L52)):*
<details><summary><i>Previously, Emistry (Emistry Haoyan) wrote…</i></summary><blockquote>

> OnAirShipIsEndableMap:

change to `S_AirShipEndableMap:`
</blockquote></details>

Done.

---

*[npc/other/private_airship.txt, line 65 at r1](https://reviewable.io/reviews/herculesws/hercules/1998#-L8VEGXtCatsgQj2CZM1:-LBff5bw03Cv891HVoEr:b-896fix) ([raw file](https://github.com/herculesws/hercules/blob/f8160b5c556c121a269e7a20640666217450a49b/npc/other/private_airship.txt#L65)):*
<details><summary><i>Previously, Emistry (Emistry Haoyan) wrote…</i></summary><blockquote>

`callsub(S_AirShipIsNeedItem)`
</blockquote></details>

Done.

---

*[npc/other/private_airship.txt, line 73 at r1](https://reviewable.io/reviews/herculesws/hercules/1998#-L8VERBj4SI_GugiIPNB:-LBff6S7CszHqDAxHz58:b-896fix) ([raw file](https://github.com/herculesws/hercules/blob/f8160b5c556c121a269e7a20640666217450a49b/npc/other/private_airship.txt#L73)):*
<details><summary><i>Previously, Emistry (Emistry Haoyan) wrote…</i></summary><blockquote>

`callsub(S_AirShipIsStartableMap)`
</blockquote></details>

Done.

---

*[npc/other/private_airship.txt, line 77 at r1](https://reviewable.io/reviews/herculesws/hercules/1998#-L8VEVDa-r9yd1M8JswL:-LBff6BQ8b0a_57Jmnyo:b-896fix) ([raw file](https://github.com/herculesws/hercules/blob/f8160b5c556c121a269e7a20640666217450a49b/npc/other/private_airship.txt#L77)):*
<details><summary><i>Previously, Emistry (Emistry Haoyan) wrote…</i></summary><blockquote>

`callsub(S_AirShipEndableMap)`
</blockquote></details>

Done.

---

*[npc/other/private_airship.txt, line 87 at r1](https://reviewable.io/reviews/herculesws/hercules/1998#-L8VEdGdBcYgXD8vyTfS:-LBff7CB41qOfk9UjVOp:b-896fix) ([raw file](https://github.com/herculesws/hercules/blob/f8160b5c556c121a269e7a20640666217450a49b/npc/other/private_airship.txt#L87)):*
<details><summary><i>Previously, Emistry (Emistry Haoyan) wrote…</i></summary><blockquote>

> .NeedItem

`.needitem`, variable shall be in lowercase letters

</blockquote></details>

Done.

---

*[npc/other/private_airship.txt, line 88 at r1](https://reviewable.io/reviews/herculesws/hercules/1998#-L8VEtHb7F2HWhlx6FUx:-LBff7bPApeOZ40_yxfF:b-896fix) ([raw file](https://github.com/herculesws/hercules/blob/f8160b5c556c121a269e7a20640666217450a49b/npc/other/private_airship.txt#L88)):*
<details><summary><i>Previously, Emistry (Emistry Haoyan) wrote…</i></summary><blockquote>

> .StartableMap$

`.startablemap$`, variable shall be in lowercase letters
</blockquote></details>

Done.

---

*[npc/other/private_airship.txt, line 437 at r1](https://reviewable.io/reviews/herculesws/hercules/1998#-L8VEyIb14vFJJ2jWcZp:-LBff83zDlFxkt9qV38c:b-896fix) ([raw file](https://github.com/herculesws/hercules/blob/f8160b5c556c121a269e7a20640666217450a49b/npc/other/private_airship.txt#L437)):*
<details><summary><i>Previously, Emistry (Emistry Haoyan) wrote…</i></summary><blockquote>

> .EndableMap$

`.endablemap$`
</blockquote></details>

Done.

---

*[npc/other/private_airship.txt, line 787 at r1](https://reviewable.io/reviews/herculesws/hercules/1998#-L8VF56U6idQYowVisGP:-LBff8Ui8ssagL2OhYhE:b-896fix) ([raw file](https://github.com/herculesws/hercules/blob/f8160b5c556c121a269e7a20640666217450a49b/npc/other/private_airship.txt#L787)):*
<details><summary><i>Previously, Emistry (Emistry Haoyan) wrote…</i></summary><blockquote>

need End of Line (EOL)
</blockquote></details>

Done.

---

*[src/map/clif.c, line 20259 at r1](https://reviewable.io/reviews/herculesws/hercules/1998#-L8VF_So5ak_OCk-SZkw:-LBffArr8cOTaNfWKwW6:b-896fix) ([raw file](https://github.com/herculesws/hercules/blob/f8160b5c556c121a269e7a20640666217450a49b/src/map/clif.c#L20259)):*
<details><summary><i>Previously, Emistry (Emistry Haoyan) wrote…</i></summary><blockquote>

maybe replace the `if (flag > 5)` by adding the enum into src?
something like `if (flag > P_AIRSHIP_ITEM_INVALID)` 
better readability
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/herculesws/hercules/1998)*

**Pull request merged**
