### PR TITLE
Added 2 New Costume items:

### PR DESCRIPTION
**Pull request by Jedzkie**
- Angels Stair (ID# 20062)
   - Decoration of Time (ID# 20246)

Signed-off-by: Jedzkie <jedzkie13@rocketmail.com>

### CODE REVIEW

**Comment by kyeme** [comment]
You forget sc_config.txt 😊

**Comment by dastgir** [comment]
Also, I would need to check how hat_effect works, till then new costume having entry in hat effect will be on hold..

**Comment by Jedzkie** [comment]
Thanks for telling me @kyeme :)

**Comment by kyeme** [comment]
Testing on item Angels Stair (ID# 20062) but its not working or no effect?

**Comment by Jedzkie** [comment]
@kyeme What client are you using? if 2015-05-13aRagexe, I can't reproduce it.

<a href="http://tinypic.com?ref=vsdllf" target="_blank">Image and video hosting by TinyPic</a>

**Comment by Jedzkie** [comment]
Do not merge this pull, thanks! I'll update another one.

**Pull request closed without merging**
