### PR TITLE
Changed the default value of max_body_style

### PR DESCRIPTION
**Pull request by EPuncker**
### Pull Request Prelude

- [x] I have followed [proper Hercules code styling][code].
- [x] I have read and understood the [contribution guidelines][cont] before making this PR.
- [x] I am aware that this PR may be closed if the above-mentioned criteria are not fulfilled.

### Changes Proposed
Changed the default value of max_body_style to 1 since there is only one body style AFAIK, otherwise it will cause a gravity error if someone set a value higher than 1 without having the proper sprites

[cont]: https://github.com/HerculesWS/Hercules/blob/master/CONTRIBUTING.md
[code]: https://github.com/HerculesWS/Hercules/wiki/Coding-Style

### CODE REVIEW

**Comment by EPuncker** [comment]
it actually has 4 body style, but the 2 to 4 are only mado gear

**Comment by 4144** [comment]
probably better add per job body style limits?
because some jobs may have sprites for 4 body styles and some other only 2 or less.

**Comment by AnnieRuru** [comment]
I think the limit should be on the stylist script and atcommand `@bodystyle` instead

**Comment by EPuncker** [comment]
> probably better add per job body style limits?
> because some jobs may have sprites for 4 body styles and some other only 2 or less.

yes I was also thinking about it, but then I remembered we also need a separated hair style/dyes to doram class... or should we handle this on stylist npc only? 🤷

**Pull request closed without merging**
