### PR TITLE
Documenation for <URL> browser dimensions.

### PR DESCRIPTION
**Pull request by marky291**
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

[//]: # (Note: Lines beginning with syntax such as this one, are comments and will not be visible in your report!)

### Pull Request Prelude

[//]: # (Thank you for working on improving Hercules!)

[//]: # (Please complete these steps and check the following boxes by putting an `x` inside the brackets _before_ filing your Pull Request.)

- [X ] I have followed [proper Hercules code styling][code].
- [ X] I have read and understood the [contribution guidelines][cont] before making this PR.
- [ X] I am aware that this PR will be closed if the above-mentioned criteria are not fulfilled.

### Changes Proposed

[//]: # (Describe at length, the changes that this pull request makes.)

**Affected Branches:** 

[//]: # (Master? Slave?)

**Issues addressed:**

[//]: # (Issue Tracker Number if any.)

### Known Issues and TODO List

[//]: # (Insert checklist here)
[//]: # (Syntax: - [ ] Checkbox)

[//]: # (**NOTE** Enable the setting "[√] Allow edits from maintainers." when creating your pull request if you have not already enabled it.)

[cont]: https://github.com/HerculesWS/Hercules/blob/master/CONTRIBUTING.md
[code]: https://github.com/HerculesWS/Hercules/wiki/Coding-Style

### CODE REVIEW

**Comment by HerculesWSAPI** [comment]
This change is [Reviewable](https://reviewable.io/reviews/herculesws/hercules/1755)

**Comment by dastgir** [comment]
Are you sure it opens default browser?
Last time I checked, it opened up clients own browser

**Comment by marky291** [comment]
Windows 10 = Internet explorer 11.

[](https://postimg.org/image/nz023xqld/)

**Comment by dastgir** [comment]
It would show IE no matter what, that's how implementation of browser is done.
So previous documentation was correct.
In your new documentation, if I set chrome as my default browser, I would have assumed that 'default' here means chrome and not IE

**Comment by MishimaHaruna** [comment]
Thank you, merged

**Pull request merged**
