### PR TITLE
Added new items DB and script fixes

### PR DESCRIPTION
**Pull request by zackdreaver**
List of changed : 
- Added new costume garments
- Added new costume headgears
- Added new footgears
- Added new accessories
- Added new shields
- Added new weapons
- Added 'Thanatos' weapons pack
- Added 'Crimson' weapons pack
- Added 'Vicious Mind' weapons pack
- Added Shadow equipments
- Fixed bug 8563

### CODE REVIEW

**Comment by dastgir** [comment]
This is most detailed pull request,(considering so much commits and following the rules of commit) :)

**Comment by zackdreaver** [comment]
yep based on the quest given, it can't be equipped, cus it need to give back to the NPC

**Comment by zackdreaver** [comment]
still need to edit the constant that not exist in hercules (shadow equipment part)

**Comment by zackdreaver** [comment]
please don't merge it,
i will add more gears+updated script of some.

**Comment by zackdreaver** [comment]
@dastgir 
Ok it's ready

**Comment by dastgir** [comment]
Thanks For cobtribution

**Pull request merged**
