### PR TITLE
Fix @QMapChangeTo$ not usable when HQO_OnMapChange triggered

### PR DESCRIPTION
**Pull request by AnnieRuru**
- also add documentation for it
- and change HQO_onLogOut into HQO_OnLogOut in source code

well this is the final one
now my Last Man Standing script working perfectly fine without anymore errors !
http://upaste.me/a93221862ed4bf9a4
I mean, you have to patch all these 4 patches, then only this script doesn't bug

EDIT: this patch contains all 4 bug fix
http://upaste.me/65dc218636607ad7a

### CODE REVIEW

**Comment by AnnieRuru** [comment]
maybe should change `@QMapChangeTo$` into `@mapchangeto$`
while nobody using these commands yet ...

**Comment by Aeromesi** [comment]
Curious AnnieRuru, if no one has used these commands, how do you know about them? By looking into Hercules's SRC? and if so how come none of this is documented? First time I've seen anything about such commands as:

queuesize/queueadd/queueopt, things like this I never knew existed and it irritates me if it's already existed, because it would help with my scripting abilities =/

**Comment by dastgir** [comment]
It existed like from past year...

**Comment by MishimaHaruna** [comment]
The commands exist and are documented, but are still at an alpha stage and quite broken (returning wrong values or crashing). I have an ongoing branch where I made some fixes (and some more may be necessary once I look into the latest issues that AnnieRuru opened).
Considering the situation, I agree that if we need to change something in the commands API, it's better to do it now, than when the use of these commands will be widespread.

**Comment by AnnieRuru** [comment]
@Aeromesi 
these script commands has been announced to public for years
http://herc.ws/board/topic/928-memory-slasher-may-30-patch/

there are 2 reasons why people doesn't know about this

1. because when it made known to public,
there are 10 script commands you need to learn in order to write a hercules battleground script
and of course, like haru said. its bugged, and sometimes crash
(its bg_queue crash, not from queue script command itself )
so even some of them want to learn, only to find out these script commands aren't really usable

2. I switched side from rathena to hercules
and I brought this createbgid/setbgid/getbgusers custom script commands from rathena
http://herc.ws/board/topic/4570-battleground-system-without-waitingroom/
and wrote them into plugin in hercules
that's when hercules community found out mine are way easier to learn
mine just need you to learn 3 script commands, but hercules' want you to learn 10 script commands
furthermore, my modification has already spread in rathena forum for at least 1 year before I join hercules,
so I can guarantee mine are 100% bug free
I also refused to learn hercules queue iterator system at that time because I always thought
mine just work the same as hercules queue iterator system when it come to writing bg scripts

it wasn't until recently Ancyker said something about OnPCxxxxEvent cost a lot of server resources
only made me rediscover these queue iterator script command can also be used for events
only just 3 days ago I started to learn how to use these script commands

**Comment by MishimaHaruna** [comment]
@AnnieRuru Do you mind if I merge this into #857, so that both are merged at the same time?

Also, if we are to rename constants, or change anything on the script side of the queue system, we should do so now (and merge everything at the same time, as one pull request). Brainstorming needed.

**Comment by AnnieRuru** [comment]
well, when I was playing around with this queue iterator script commands,
I didn't know you already started it way before me

I think you should disregard my pull request, and only fix whatever I have reported

your branch, doesn't fix the `QMapChangeTo`,
it need `@QMapChangeTo$` the symbols in order to work
try read getpartymember or something else similar, they also return `$@partymemberaid`
```
mapreg->setreg(reference_uid(script->add_str("$@partymemberaid"), j),p->party.member[i].account_id);
```

I still think we should rename `@QMapChangeTo$` into `@mapchangeto$` ... 
though, this just my personal idea anyway

**Comment by MishimaHaruna** [comment]
This was merged as part of PR #857 (I cherry-picked your commit and kept the non-conflicting part). Thank you!

**Pull request closed without merging**
