### PR TITLE
Stops tsd client crashing if party inviter is disguised.

### PR DESCRIPTION
**Pull request by bWolfie**
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

[//]: # (Note: Lines beginning with syntax such as this one, are comments and will not be visible in your report!)

### Pull Request Prelude

[//]: # (Thank you for working on improving Hercules!)

[//]: # (Please complete these steps and check the following boxes by putting an `x` inside the brackets _before_ filing your Pull Request.)

- [x] I have followed [proper Hercules code styling][code].
- [x] I have read and understood the [contribution guidelines][cont] before making this PR.
- [x] I am aware that this PR will be closed if the above-mentioned criteria are not fulfilled.

### Changes Proposed
Stops disguised party invites if disguised. If the party inviter is disguised, they can crash anyone's client just by inviting them to their party (not sure if it will crash on partylock or if player already has party).

Confirmed to crash the target's client in 20160113.

[//]: # (Describe at length, the changes that this pull request makes.)

**Affected Branches:** 

[//]: # (Master? Slave?)
- [x] master
- [x] stable

**Issues addressed:**

[//]: # (Issue Tracker Number if any.)

### Known Issues and TODO List

- [ ] Test in other clients to see if it is a packetver related thing.

[//]: # (Insert checklist here)
[//]: # (Syntax: - [ ] Checkbox)

[//]: # (**NOTE** Enable the setting "[√] Allow edits from maintainers." when creating your pull request if you have not already enabled it.)

[cont]: https://github.com/HerculesWS/Hercules/blob/master/CONTRIBUTING.md
[code]: https://github.com/HerculesWS/Hercules/wiki/Coding-Style

### CODE REVIEW

**Comment by HerculesWSAPI** [comment]
This change is [Reviewable](https://reviewable.io/reviews/herculesws/hercules/2184)

**Comment by 4144** [comment]
caption said prevent invite if party leader disguised, but pr really prevent invites if party inviter disguised.
what is correct caption or code?

**Comment by dastgirp** [comment]
If someone else can test for which client it crashes, it would be great.

**Comment by MrKeiKun** [comment]
> 
> 
> If someone else can test for which client it crashes, it would be great.

yep crashing here using current Hercules~

**Comment by 4144** [comment]
look like need rebase and conflict fixing

**Comment by Kenpachi2k13** [comment]
I just tested these 3 clients:

- **2016-01-13aRagexeRE**: Crashes upon being invited by a disguised character.
- **2016-01-13bRagexeRE**: Doesn't Crash upon being invited by a disguised character.
- **2016-01-13cRagexeRE**: Doesn't Crash upon being invited by a disguised character.

So this issue obviously is caused by a faulty client and not by Hercules code.

**Comment by Kenpachi2k13** [comment]
I did some testing with `2016-01-13cRagexeRE` and the issue isn't related to the invitation itself.
The actual problem is opening the party window. As of yet I wasn't able to find the real culprit since the crash doesn't occur every time the party window is opened. Actually it doesn't always happen under identical circumstances. :disappointed:

However, prevent disguised characters from inviting other characters doesn't fix anything and thus this PR brings no benefit.

**Comment by skyleo** [comment]
This crash is caused by a missing check in the client for when getting the Actor Object by AID what type of object it is. They think it's of type "0" instead of "1" but both have different vftables and different adresses / offsets for their HP bar information, which leads to an memory access violation for when you have disguised people in your party.

Can pretty much only be solved by modifying the client with your own asm. :)

**Pull request closed without merging**
