### PR TITLE
Add missing warps dali<->dali02

### PR DESCRIPTION
**Pull request by AnnieRuru**
[cont]: https://github.com/HerculesWS/Hercules/blob/master/CONTRIBUTING.md
[code]: https://github.com/HerculesWS/Hercules/wiki/Coding-Style
### Pull Request Prelude
- [x] I have followed [proper Hercules code styling][code].
- [x] I have read and understood the [contribution guidelines][cont] before making this PR.
- [x] I am aware that this PR will be closed if the above-mentioned criteria are not fulfilled.

### Issues addressed
```
Bruno Last Tuesday at 5:12 AM
hello @AnnieRuru and @Kisuka i find 1 simple error, hercules need add portal acess to map "dali02"
```

### Changes Proposed
```
AnnieRuru Last Tuesday at 3:43 PM
@Bruno 
found in rathena -> https://github.com/rathena/rathena/commit/f07ceced916ea65336370e629b4ba394f7c91000
probably just need to add that
```

### Affected Branches
* Master

### Known Issues and TODO List
rAthena are well known for adding unofficial stuff, so need confirmation
I tested in-game, and somehow the portal location .... seems off to me

### CODE REVIEW

**Comment by HerculesWSAPI** [comment]
This change is [Reviewable](https://reviewable.io/reviews/herculesws/hercules/2372)

**Comment by Asheraf** [comment]
not sure if this is a good idea, for now we have only one instance in the dali02 map.. ghost palace which needs to be rewritten since it has many inaccurate things (it was based off videos rather than actually playing). so this might cause problems for some people.

**Comment by AnnieRuru** [comment]
ghost palace ... https://github.com/HerculesWS/Hercules/pull/1409
rather than ... stop our progress at --> its still not accurate !!
why not having a topic somewhere to mark the accuracy ... ?

example : like having a [project page](https://github.com/HerculesWS/Hercules/projects) and mark
1. this script is direct conversion from Aegis -> Very High
2. this script has been tested by the author in official server repeatedly -> High
3. this script is made based on video, iro-wiki or divine-pride -> Ambiguous
so we don't get mixed up some script which is accurate, and which are ... less accurate

or maybe include this info in the Script Header itself ... so any contributor can report this is inaccurate

and this ... Ima closing this because I don't have any official information

**Comment by Asheraf** [comment]
It's not stopping progress but rather preventing complains by someone who might not want this script.. As for your suggestions we definitely should do something to categorize our scripts but couple things to point out:

- there is too many scripts that have been created/modified by multiple people, and 90% of these authors are no longer in the community to confirm the source of their scripts.

- there is at least 4 different aegis script versions for each script with changes in dialogue and sometimes in how it works depending on the server the leak was from (what should we pick?).

**Pull request closed without merging**
