### PR TITLE
Change numbers into constants in item_db.conf

### PR DESCRIPTION
**Pull request by iRagno**
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

[//]: # (Note: Lines beginning with syntax such as this one, are comments and will not be visible in your report!)

### Pull Request Prelude

[//]: # (Thank you for working on improving Hercules!)

[//]: # (Please complete these steps and check the following boxes by putting an `x` inside the brackets _before_ filing your Pull Request.)

- [x] I have followed [proper Hercules code styling][code].
- [x] I have read and understood the [contribution guidelines][cont] before making this PR.
- [x] I am aware that this PR will be closed if the above-mentioned criteria are not fulfilled.

### Changes Proposed

Changes numeric values contained on item_db fields into constants.
Values changed: Type and Gender

**Affected Branches:** `item_viewid`

**Issues addressed:** `Suggestion`

### Known Issues and TODO List

- [x] Upper Values: Make them capable of put multiple values according to bitmask.
- [x] Add new constant for Sex Both (it is default value to string in item_db structure prelude)
- [x] Add constant for Loc value and check if allow multiple values according to bitmask.
- [ ] Add constant for View in Headears, Shields and Garments

[//]: # (**NOTE** Enable the setting "[√] Allow edits from maintainers." when creating your pull request if you have not already enabled it.)

[cont]: https://github.com/HerculesWS/Hercules/blob/master/CONTRIBUTING.md
[code]: https://github.com/HerculesWS/Hercules/wiki/Coding-Style

---
This change is [Reviewable](https://reviewable.io/reviews/herculesws/hercules/1633)

### CODE REVIEW

**Comment by iRagno** [comment]
Initially I suggested this on Hercules' Boards: http://herc.ws/board/topic/14453-add-usage-of-constants-on-item-dbconf-structure/. Reply from 4144 encourage me to start with this little project and now I'm sending this as a Pull Request.

About required constants, I would like to propose the next ones:

**Comment by iRagno** [comment]
Constants for Loc values:
```
	LOC_LOWER_HEADGEAR:       0x000001
	LOC_WEAPON:               0x000002
	LOC_GARMENT:              0x000004
	LOC_ACCESSORY_1:          0x000008
	LOC_ARMOR:                0x000010
	LOC_SHIELD:               0x000020
	LOC_FOOTGEAR:             0x000040
	LOC_ACCESSORY_2:          0x000080
	LOC_UPPER_HEADGEAR:       0x000100
	LOC_MIDDLE_HEADGEAR:      0x000200
	LOC_COSTUME_TOP_HEADGEAR: 0x000400
	LOC_COSTUME_MID_HEADGEAR: 0x000800
	LOC_COSTUME_LOW_HEADGEAR: 0x001000
	LOC_COSTUME_GARMENT:      0x002000
	LOC_SHADOW_ARMOR:         0x010000
	LOC_SHADOW_WEAPON:        0x020000
	LOC_SHADOW_SHIELD:        0x040000
	LOC_SHADOW_SHOES:         0x080000
	LOC_SHADOW_ACCESSORY_2:   0x100000
	LOC_SHADOW_ACCESSORY_1:   0x200000
	LOC_AMMO:                 0x008000
```

**Comment by iRagno** [comment]
_Reserved to constants for headgears._

**Comment by iRagno** [comment]
Constants for View on Weapons:
```
	WT_NONE:           0
	WT_DAGGER:         1
	WT_SWORD:          2
	WT_TWO_HAND_SWORD: 3
	WT_SPEAR:          4
	WT_TWO_HAND_SPEAR: 5
	WT_AXE:            6
	WT_TWO_HAND_AXE:   7
	WT_MACE:           8
	WT_TWO_HAND_MACE:  9
	WT_ROD:           10
	WT_BOW:           11
	WT_KNUCKLE:       12
	WT_INSTRUMENT:    13
	WT_WHIP:          14
	WT_BOOK:          15
	WT_KATAR:         16
	WT_HANDGUN:       17
	WT_RIFLE:         18
	WT_GATLING:       19
	WT_SHOTGUN:       20
	WT_GRENADE:       21
	WT_SHURIKEN:      22
	WT_TWOHANDROD:    23
```

Constants for View of Shields:
```
	ST_NONE:          0
	ST_GUARD:         1
	ST_BUCKLER:       2
	ST_SHIELD:        3
	ST_MIRROR_SHIELD: 4
	ST_MEMORIZE_BOOK: 5
```

Constants for View on Garments:
```
	GT_ARCHANGEL_WING:      1
	GT_BRAVERY_BAG:         2
	GT_FALLEN_ANGEL_WING:   3
	GT_AMISTR_BAG:          4
	GT_LOVE_DAD_WINGS_2012: 5
	GT_KIRIN_WING:          6
	GT_RIBBON_PIAMAT:       7
	GT_WING_OF_HAPPINESS:   9
	GT_ARCH_ANGEL_WING:    10
```

**Comment by iRagno** [comment]
If agree with the constants proposed, I can start to work on it.

**Comment by iRagno** [comment]
Another way to put view constants could be:
```
ACC_GOGGLES       -> VIEW_HEADGEAR_GOOGLES
WT_DAGGER         -> VIEW_WEAPON_DAGGER
ST_GUARD          -> VIEW_SHIELD_GUARD
GT_ARCHANGEL_WING -> VIEW_GARMENT_ARCHANGEL_WING
AT_ARROW          -> VIEW_AMMO_ARROW
```
What do you think? @HerculesWS/developers

**Comment by Ancyker** [comment]
@iRagno I think it's convoluted. The view ID list is giant, and the names of the items vary in some cases. It would be insanely confusing to try and make them into constants, not to mention the length limit would be hit on many of them opening the door for accidental collisions.

View IDs are 100% client side so it makes little sense to use constants for them. Monsters and items make sense. NPC sprites make some sense because their sprite names are in English and fairly straight forward. But view IDs? Not so much.

**Comment by skyleo** [comment]
I'm all for this, let's get away from those black magic numbers!
(But not sure if we want Constants for View_IDs)

**Comment by 4144** [comment]
@iRagno remember what all C constants should be defined in C side with special functions and not in constants.conf
This constants already have names, and probably dont need change names for many of it.
For example WT_* in C designed as W_* but not registered for script engine.
Same for AT_* -> A_*
May be other too.

**Comment by Asheraf** [comment]
Constants for view id have been already added by @MishimaHaruna in https://github.com/HerculesWS/Hercules/tree/item_viewid maybe you can remove them from this pr

**Comment by iRagno** [comment]
@Ancyker, the purpouse of this is to make easier to read and understand item_db. Having "View" values into weapons, shields and garments is not intuitive enough to know what does that mean. You can see an example on 1401-Javelin, 2115-Valkyrja's Shield, 20706-Amistr Bag and 2207-Fancy Flower, all of them uses View value of 4, but that 4 has different context for every one of them.

@skyleo, yeah, those values of Type and Upper are black magic that needs special manuals to understand xD. At least, I always need to open doc\item_db.txt to track what those values mean, and in the case of Upper also need a calc to make maths for every bit. It can be improved to make easier to read and lead into the light those values.

@4144, I have to be honest and say I don't have too much skills at C (still learning and training), so, that is something new for me and would appreciate any advice on it. I didn't have in consideration those constants could be already in use, but, well, that is the reason it's only a suggestion.

In that way, even when I really would love to introduce Upper in libconfig, the most I can do with my actual skills is to introduce constants like "LOC_UPPERLOW_HEADGEAR" for items like Sphinx Hat or "LOC_TWO_HAND_WEAPON" to items equipable in both Weapon and Armor slots.

@Asheraf, didn't know about that, thank you. Seems it's already being in maintenance, so, shouldn't change View values for this. @MishimaHaruna, does this suggestion create conflicts with maintenance in process? Maybe I could pull into item_viewid branch if this suggestion is useful for it.

**Comment by MishimaHaruna** [comment]
@iRagno  Feel free to continue the work based on my branch, or to cherry-pick my changes into yours. It's a project I started a long ago, but never managed to complete.
The goal of my branch was to also differentiate the use of View IDs from the use of weapon/ammunition subtypes, since I find it very ugly for them to share the same item db field.
I initially added the `W_*` and `A_*` constants in the .conf file rather than using the ones hardcoded in the source, and I believe that @4144's suggestion is a good improvement idea.

As a suggestion for this pull request, I believe that it'd be easier to review it if it was split in multiple commits, where each of them replaces one specific value. That way it's harder that an error slips in, considering how impossible it is to eyeball a diff with 14k lines changed.

I'm going to update my branch, since it's been a while since I last rebased it, and I'll also move the constants definitions to the source, so you can use that as an example.

**Comment by MishimaHaruna** [comment]
Branch rebased and pushed

**Comment by iRagno** [comment]
Thank you @MishimaHaruna, I will do it in that way and change target branch to item_viewid to continue in there.

**Comment by iRagno** [comment]
I have separated changes on item_db in individual commit for every change. Also, in this time I take the chance to remove "Type: 3" from pre-re\item_db.conf since that is default value.

Changed target branch from `master` to `item_viewid`.

**Comment by iRagno** [comment]
About Travis' check fail, it is because there are some new items on item_db that should be marked as armor, but in db were marked as weapon and shows warning pointing that weapon doesn't have a subtype. It is an amazing improvement by Haru, because console will tell when an item is not configured correctly. I don't know if can I fix those in this pr, or if should be fixed on `master` branch, since those errors were introduced in there.

Also I think having constants on item types will reduce the chances to introduce errors in configurations.

I have added constants for shield and garment sprite types. If those changes are correct, I'm ready to start changing values to constants in shields and garments. About headgears view sprite, I think too it is not worth enought to bring over a thousand constants only for that, besides it may be the only one to have view sprites in numeric value instead of constant, and having constants for shields and garments will be enought help to understand those values.

For loc values, I will send an independent pull request to suggest it.

**Comment by MishimaHaruna** [comment]
@iRagno About the travis check fails, please fix them in the PR, in a separate commit at the end (to avoid touching the file in the master branch and cause merge conflicts).

I agree that those view IDs are fine as numbers.

About the gender constants, the current design is a bit unfortunate (because it was done to follow the clientside boolean-like values). It would have been better as a bitmask, but for now let's not change the values, and keep it for a later time.
I don't think `SEX_SERVER` is appropriate, adding a new constant (I'd call it `SEX_ANY` = 2) sounds good for now.

**Comment by iRagno** [comment]
I have applied requested changes, @MishimaHaruna.

In commit 0698c44799575a2394216e1749e376d4d72eff7e I add a proposal constants for Shields and Garments sprite values. If those are fine, I can start to change numbers into constants for Shields and Garments (or to remove those constants, otherwise).

By the way, in this other branch [item_loc_constants](https://github.com/AtlantisRO/Hercules/commits/item_loc_constants) I have been working on changing loc numeric values into constants. Changes on item_db are done, but I don't have the skills to apply changes on src. Would be ok if I send those changes in pr to `item_viewid` branch so you or other person able of that can change it?

**Comment by MishimaHaruna** [comment]
I'm not really sure about using constants for view IDs. They tend to be a lot (especially the headgear ones), and using constants on certain item types while not on others doesn't feel right.

What do the others think? @HerculesWS/developers 

On a side note,  if we decide to use those constants, consider renaming them to start with `VIEWID_*` to avoid namespace conflicts with mob names (`G_*` is already used in several mob SpriteNames for example)

About item_loc_constants, sure, that's fine. Maybe after this one is complete, to avoid too many conflicts?

**Comment by Emistry** [comment]
Just a concern, does it still support for number value for these field? if it doesn't do we provide an external converter to convert the old value into constants like Herc did with the `item_db.txt` to `item_db.conf` and etc ?

We do believe the changes from number to constant are good for readability, but what about the user side? We know that most of the server out there created thousand of custom items of their own, editing one by one would be pain in the ass, especially if they dont even know how to use the find and replace feature lol.

**Comment by 4144** [comment]
@Emistry 
item_db support at same time numbers and constants in many fields.
This mean players can use only numbers or only constants or mix two items in one db with numbers and constants.

**Comment by Smokexyz** [comment]
Sounds good to me, and so I +1 this PR. Maybe to avoid a lengthy constants file, we could have a folder in the db such as - `db/constants/*.conf` and separate out different constants in respect to their source. (just a thought, and in a different PR of course)

**Comment by MishimaHaruna** [comment]
@iRagno would it be too much to ask to remove (at least for now) the commit that adds the G_ and S_ constants, so we start merging this part?

**Pull request merged**
