### PR TITLE
Missing break in skill

### PR DESCRIPTION
**Pull request by Nihadm89**
Lightning Spear of Ice

### CODE REVIEW

**Comment by MishimaHaruna** [comment]
Judging by the comment right after, it seems like the missing break was intended, in order to fall through into the next case.

**Comment by Nihadm89** [comment]
Intended or not it breaks the lightning spear skill. By putting the break in there the skill goes back to official damage.

**Comment by MishimaHaruna** [comment]
Ah, I see. I'll reopen then, thank you!

**Comment by MishimaHaruna** [comment]
This piece of code was added in 6dd08bef. @rud0lp20, can you confirm that the lack of `break` was an oversight in that commit?

**Comment by rud0lp20** [comment]
yeah..missing break...

**Comment by MishimaHaruna** [comment]
@rud0lp20 would you mind checking the other `/* Fall through */` comments in the same file if you can? They mark all the instances of omitted `break` (some of them might be intended, some might not perhaps)

**Comment by rud0lp20** [comment]
ok...:D

**Pull request merged**
