### PR TITLE
Fix for Issue 592

### PR DESCRIPTION
**Pull request by Milchdealer**
Exchanged message for its colored counterpart with DEFAULT_COLOR to prevent it from bugging out on special symbols.

### CODE REVIEW

**Comment by 4144** [comment]
Here one line change, but two useless commits. May be better clean it?

**Comment by Milchdealer** [comment]
No
It's best practice to only merge on master and never commit directly.
Also I think they currently work on a bigger patch anyways and could just incorporate this

**Comment by Milchdealer** [comment]
But it did add my synching the fork with the origin which I will remove later today

**Comment by HerculesWSAPI** [comment]
Yep, best practice is to only merge on master, that's why it's recommended to start pull requests from specific branches (targeting Hercules:master), so they can be easily rebased before merging, as not to clutter the main repository history with reverse merges

**Comment by MishimaHaruna** [comment]
Yep, best practice is to only merge on master, that's why it's recommended to start pull requests from specific branches (targeting Hercules:master), so they can be easily rebased before merging, as not to clutter the main repository history with reverse merges

**Comment by Milchdealer** [comment]
Yes I'll clean it up after work

**Pull request closed without merging**
