### PR TITLE
Add and update some existing packets for 2016-2017 clients

### PR DESCRIPTION
**Pull request by 4144**
### Pull Request Prelude

- [x] I have followed [proper Hercules code styling][code].
- [x] I have read and understood the [contribution guidelines][cont] before making this PR.
- [x] I am aware that this PR will be closed if the above-mentioned criteria are not fulfilled.

### Changes Proposed

Add and update some existing packets for 2016-2017 clients.
Fixed style in changed functions in separate commits.
Fixed guild leader change packet.
Most work based on commits from rAthena.

### CODE REVIEW

**Comment by HerculesWSAPI** [comment]
This change is [Reviewable](https://reviewable.io/reviews/herculesws/hercules/1785)

**Comment by 4144** [comment]
I not tested it. Need testing for clients < 2016 and for >2016. and 2017

**Comment by Asheraf** [comment]
I tested some of the updates and the results are:
- Vending list tested in `2015-08-26bRagexe`, `2017-06-14bRagexeRE` working correctly
- Guild UI tested with `2013-07-24eRagexe`, `2015-08-26bRagexe`, `2017-03-15cRagexeRE`, `2017-06-14bRagexeRE` working fine but missing last login which could be added after #1718 merged.
- Party UI tested with `2017-04-26dRagexeRE` (old ui) and `2017-05-02dRagexeRE` (new ui) and both working fine.

**Comment by dastgir** [comment]
so this can be merged?

**Comment by admkakaroto** [comment]
Already have support for the equipment swap present in the new clients 2017?

**Comment by dastgir** [comment]
It doesn't give error, but it doesn't work exactly as intended(This PR isn't meant for that yet)

**Comment by MishimaHaruna** [comment]
Done, thank you

**Pull request merged**
