### PR TITLE
Fix some skills bugs

### PR DESCRIPTION
**Pull request by inhyositsu**
Fix the skill type of RK_DRAGONBREATH and RK_DRAGONBREATH_WATER, they should be BF_WEAPON in official server, and they support bLongAtkRate bonus.

---
This change is [Reviewable](https://reviewable.io/reviews/herculesws/hercules/1304)

### CODE REVIEW

**Comment by Ridley8819** [comment]
@MishimaHaruna

**Comment by Smokexyz** [comment]
I see that you have removed the line `md.flag |= BF_LONG|BF_WEAPON;`
This flag enables BF_LONG. Find in `battle_calc_weapon_attack()` on line 5319, it enables the addition of `bonus.long_attack_atk_rate`

**Comment by Murilo-BiO** [comment]
@Smokexyz since it's BF_WEAPON and its range is 9 (>=5) it will be considered as BF_LONG as well.

**Comment by MrKeiKun** [comment]
Anyone wanna remove this from **Release Candidate (review)** in the Project Board?

**Pull request merged**
