### PR TITLE
Change all TBL_* to actual struct to follow unix kernel syntax

### PR DESCRIPTION
**Pull request by hemagx**
Change all TBL_* to actual struct to follow unix kernel syntax

### CODE REVIEW

**Comment by dastgir** [comment]
So for what purpose is TBL_PC?

**Comment by AnnieRuru** [comment]
I'm sensing my plugins get broken if this is merge ...
once the hercules bot update HPM_HookingMap, that is ...

**Comment by hemagx** [comment]
@dastgir
it's for BL_CAST macro and should never used anywhere

@AnnieRuru 
no it wont get broken

**Comment by dastgir** [comment]
@Annieruru
TBL_PC is just typedef
(You still can use TBL_PC)
It's like TBL_PC = struct map_session_data,
And TBL_PC won't be removed..
So none of your plugins will break

**Pull request closed without merging**
