### PR TITLE
Update Exp Table

### PR DESCRIPTION
**Pull request by Ridley8819**
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

[//]: # (Note: Lines beginning with syntax such as this one, are comments and will not be visible in your report!)

### Pull Request Prelude

[//]: # (Thank you for working on improving Hercules!)

[//]: # (Please complete these steps and check the following boxes by putting an `x` inside the brackets _before_ filing your Pull Request.)

- [x] I have followed [proper Hercules code styling][code].
- [x] I have read and understood the [contribution guidelines][cont] before making this PR.
- [x] I am aware that this PR will be closed if the above-mentioned criteria are not fulfilled.

### Changes Proposed

[//]: # (Describe at length, the changes that this pull request makes.)

**Affected Branches:** Master

[//]: # (Master? Slave?)

**Issues addressed:** None

[//]: # (Issue Tracker Number if any.)

### Known Issues and TODO List

[//]: # (Insert checklist here)
[//]: # (Syntax: - [ ] Checkbox)
Did not include to update values higher than the official ones (jlvl 50 and 70).

[//]: # (**NOTE** Enable the setting "[√] Allow edits from maintainers." when creating your pull request if you have not already enabled it.)

[cont]: https://github.com/HerculesWS/Hercules/blob/master/CONTRIBUTING.md
[code]: https://github.com/HerculesWS/Hercules/wiki/Coding-Style

### CODE REVIEW

**Comment by HerculesWSAPI** [comment]
This change is [Reviewable](https://reviewable.io/reviews/herculesws/hercules/1723)

**Comment by Mysteries** [comment]
The commit title is changed o_o

**Comment by Smokexyz** [comment]
@Mysteries Commit title is not the same as PR title.

**Comment by Mysteries** [comment]
Oh welp.. the commit one :P Yes. My apologies then!

**Comment by mekolat** [comment]
@Ridley8819 
1. to change your commit message: `git commit --amend`
2. to update your pull request: `git push -f exp`

**Comment by MishimaHaruna** [comment]
Commit message edited

**Comment by MishimaHaruna** [comment]
Merged

**Pull request merged**
