### PR TITLE
Fixed Land Mine, Blast Mine and Claymore Mine not ignoring damage red…

### PR DESCRIPTION
**Pull request by SamuelHercules**
…uction cards

Merge rAthena @ 5971745dfd36451ecae766f7e4e9afb8f293ca5a
Credit: Playtester

### CODE REVIEW

**Comment by dastgir** [comment]
@Jedzkie

**Comment by Smokexyz** [comment]
@HerculesWS/developers This is clearly outdated beyond repair, someone please rebase or shall I?

**Comment by HerculesWSAPI** [comment]
This change is [Reviewable](https://reviewable.io/reviews/herculesws/hercules/1149)

**Comment by kyeme** [comment]
Any news here?

**Comment by MishimaHaruna** [comment]
Replaced by #3024

**Pull request closed without merging**
