### PR TITLE
 Convert mob_skill_db into libconf format

### PR DESCRIPTION
**Pull request by Asheraf**
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

[//]: # (Note: Lines beginning with syntax such as this one, are comments and will not be visible in your report!)

### Pull Request Prelude

[//]: # (Thank you for working on improving Hercules!)

[//]: # (Please complete these steps and check the following boxes by putting an `x` inside the brackets _before_ filing your Pull Request.)

- [x] I have followed [proper Hercules code styling][code].
- [x] I have read and understood the [contribution guidelines][cont] before making this PR.
- [x] I am aware that this PR will be closed if the above-mentioned criteria are not fulfilled.

### Changes Proposed

suggestions for better key names are welcome (i'm not good with names..)

[//]: # (Insert checklist here)
[//]: # (Syntax: - [ ] Checkbox)

[//]: # (**NOTE** Enable the setting "[√] Allow edits from maintainers." when creating your pull request if you have not already enabled it.)

[cont]: https://github.com/HerculesWS/Hercules/blob/master/CONTRIBUTING.md
[code]: https://github.com/HerculesWS/Hercules/wiki/Coding-Style

### CODE REVIEW

**Comment by HerculesWSAPI** [comment]
This change is [Reviewable](https://reviewable.io/reviews/herculesws/hercules/2019)

**Comment by marcosbucarte** [comment]
interesting, however looking at the file I find it difficult to read because it is very large in some monsters, changing the form of writing would be better not?

Example:

```lua
CURUPIRA: {
		NPC_GROUNDATTACK: { SkillState: "MSS_BERSERK", SkillLevel: 2, Rate: 500,   CastTime: 500, Delay: 5000,      SkillTarget: "MST_TARGET", CastCondition: "MSC_ALWAYS", Emotion: 6  }
		SA_REVERSEORCISH: { SkillState: "MSS_BERSERK", SkillLevel: 1, Rate: 50,    Delay: 30000,  Cancelable: true, SkillTarget: "MST_TARGET", CastCondition: "MSC_ALWAYS", Emotion: 18 }
		SA_REVERSEORCISH: { SkillState: "MSS_RUSH",    SkillLevel: 1, Rate: 50,    Delay: 30000,  Cancelable: true, SkillTarget: "MST_TARGET", CastCondition: "MSC_ALWAYS", Emotion: 18 }
		NPC_BLINDATTACK:  { SkillState: "MSS_BERSERK", SkillLevel: 3, Rate: 500,   Delay: 5000,   Cancelable: true, SkillTarget: "MST_TARGET", CastCondition: "MSC_ALWAYS"              }
		MG_STONECURSE:    { SkillState: "MSS_IDLE",    SkillLevel: 5, Rate: 10000, Delay: 5000,   Cancelable: true, SkillTarget: "MST_TARGET", CastCondition: "MSC_ALWAYS", Emotion: 11 }
		MG_STONECURSE:    { SkillState: "MSS_BERSERK", SkillLevel: 5, Rate: 10000, Delay: 5000,   Cancelable: true, SkillTarget: "MST_TARGET", CastCondition: "MSC_ALWAYS", Emotion: 11 }
		AL_INCAGI:        { SkillState: "MSS_RUSH",    SkillLevel: 1, Rate: 500,   CastTime: 700, Delay: 60000,     SkillTarget: "MST_SELF",   CastCondition: "MSC_ALWAYS", Emotion: 6  }
}
```

**Comment by Asheraf** [comment]
@marcosbucarte that is against the style standards i believe, but you can always use folding in your text editor for big lists.

**Comment by EyesOfAHawk** [comment]
looking forward to this. hoping file does not get too massive and unreadable.

**Comment by Asheraf** [comment]
@EyesOfAHawk no offense but its not like the old format is readable at all... also this kind of databases is meant to be either auto generated from an aegis version or an api (divine-pride for example), and its much easier to do individual edits in this format if want to do any.

**Comment by Asheraf** [comment]
@EyesOfAHawk again as i said previously if a list is too long you can always use folding in your text editor.


also if you're using any modern text editor it should have support for more options, example in sublime you can go `Edit > Code Folding > Fold Level 3` and that will minimize all the skill blocks and you can pick whatever you want to check and expand it then.

**Comment by AnnieRuru** [comment]
I'm sure many of you ... or us still using Notepad++ :grin: 
to word wrap like asheraf did in notepad++
press Alt for menu -> View -> Collapse Level -> 3 = Alt +3
hotkey is **Alt +3**

to unfold all is hotkey Alt+Shift+0

**Comment by MishimaHaruna** [comment]
Here's a gist with the tests and the outputs I obtained: https://gist.github.com/MishimaHaruna/34346215e0ab0b36ed81c9bb430c210d

**Pull request merged**
