### PR TITLE
Automatically migrate pets to the new system that keeps hatched eggs in the inventory

### PR DESCRIPTION
**Pull request by hemagx**
### Pull Request Prelude

- [x] I have followed [proper Hercules code styling][code].
- [x] I have read and understood the [contribution guidelines][cont] before making this PR.
- [x] I am aware that this PR may be closed if the above-mentioned criteria are not fulfilled.

### Changes Proposed

Automatically migrate pets to the new system that keeps hatched eggs in the inventory
- The pet evolution update caused all already hatched eggs to get lost cause the previous system would actually remove the egg unlike the new one, this code will ensure the return of it.

**Issues addressed:** 

[cont]: https://github.com/HerculesWS/Hercules/blob/master/CONTRIBUTING.md
[code]: https://github.com/HerculesWS/Hercules/wiki/Coding-Style

### CODE REVIEW

**Comment by HerculesWSAPI** [comment]
This change is [Reviewable](https://reviewable.io/reviews/herculesws/hercules/2428)

**Comment by AnnieRuru** [comment]
curious, this doesn't fix that ...
1. `@makeegg 1002` create a poring egg
2. `@hatch` hatch the poring egg
3. `@petfriendly 1000` intimacy to max
4. `@item Leaf_Of_Yggdrasil 10` `@item Unripe_Apple 3` and select pet evolution to Mastering
5. `@hatch` the mastering egg
-> now your mastering is uncontrollable

doesn't fix this bug right ?

**Comment by hemagx** [comment]
@AnnieRuru It's unrelated issue, this code is to fix lost pets, basically after pet evolution update was merged anyone with a hatched pet would lose their eggs, this code is to restore their eggs, if you may link me to this issue so i may include it in this PR!

**Comment by Asheraf** [comment]
@AnnieRuru the bug you're reporting is related to missing pet info in the database, basically mastering have a `HungerDelay` value of 0 which means once you obtain it it loses all the hunger and loyalty and its gone. due to missing infos about these new pets nothing was added to their values.

**Comment by bWolfie** [comment]
thank u

**Pull request merged**
