### PR TITLE
TESTING ONLY !! DO NOT MERGE ... testing hercules travis-ci

### PR DESCRIPTION
**Pull request by AnnieRuru**
Issue https://github.com/HerculesWS/Hercules/issues/2853

 try remove the map_cell2get function and see if this PR return built success

if this actually return success, then this function needs a rewrite

### CODE REVIEW

**Comment by AnnieRuru** [comment]
yeah seriously travis works at turtle speed ....

**Comment by 4144** [comment]
what the sense to change this function?
you afraid huge memory copy on each call? it's not, because struct less than int size.
compiler note? as i explained before it don't make sense to build hercules with one compiler and plugins with another to get run time bug.

**Comment by AnnieRuru** [comment]
> it don't make sense to build hercules with one compiler and plugins with another to get run time bug.

then there is a bug in travis =/

**Comment by 4144** [comment]
i wrote in other pr about.
this is not issue with this method. issue in timeout. because compiled in ARM arch, it much slower than amd64, and travis allow run compilation for fixed time only for 1h. if runs longer it show timeout.
most time this issue can be fixed by pressing ``retry`` on build with timeout.

**Pull request closed without merging**
