### PR TITLE
Fixes #889 & #840

### LINKED ISSUE #889: Hp displayed when dead
On iro/euro the client display 1 hp when you have died (on rathena -> 0 hp).

Image on left, with rathena ; offi on right

image

Credits to @Atemo 
https://github.com/rathena/rathena/issues/758

### PR DESCRIPTION
**Pull request by Jedzkie**
- Novice classes will never go below 50% hp when died.
- Other classes will show 1 HP rather than 0 when died.

---

This change is [Reviewable](https://reviewable.io/reviews/herculesws/hercules/1215)

### CODE REVIEW

**Comment by hemagx** [comment]
What's the point of show fake HP, that what we actually have ?

**Comment by Jedzkie** [comment]
Maybe its only a visual glitch, but its confirmed that when i respawn and if i'm a novice, my hp goes half.

**Comment by dastgir** [comment]
Maybe a new battle config for novice to set respawn HP is needed rather than visual glitch...

**Comment by hemagx** [comment]
then it's no sense to fix this way, it will be better to fix the actual HP and not send Fake HP.

**Comment by Jedzkie** [comment]
We need the opinion of @MishimaHaruna

**Comment by MishimaHaruna** [comment]
I believe this is just an AEGIS limitation, no reason to emulate it. I'd rather have 0 HP on dead characters, I don't see a point in displaying what the HP after respawning will be.

**Comment by dastgir** [comment]
@MishimaHaruna 
The problem here is, novice should respawn with 50% HP and not 1Hp

**Comment by MishimaHaruna** [comment]
That's a separate problem (I thought we already have that?) This PR only changes what's displayed *before* respawning, not the actual HP *after*. (when you are dead, you have 0 hp regardless of what this PR does, it just cheats by sending a different value to the client)

**Comment by Playtester** [comment]
@MishimaHaruna 
Reason why Gravity does this is because the client HP display messes up when you send "0 HP" to it. The numbers will disappear in the display completely then.

**Comment by MishimaHaruna** [comment]
@Playtester I wouldn't call that 'messes up', it looks more like they actually took their time to add special handling for the '0'. Or, that's what I've always thought when I saw it.

**Comment by MishimaHaruna** [comment]
Edited so that it uses the same logic that's actually used at respawn.

**Comment by malufett** [comment]
I believe we need to investigate further cause it seems like when after a character dies it actually revive but flagged as dead  so some functions work and some are not according to that flag..

**Comment by MishimaHaruna** [comment]
I don't think we want dead characters to behave like alive ones (even if that happens on Aegis, I refuse to consider it anything other than a bug...)

This pull request only changes the HP display (which I consider really stupid by the way)

**Comment by MishimaHaruna** [comment]
Since it's not clear what we want to do here, I'm putting it on hold. I'm fine with anything, as long as:
1. users can still revert to our old, sane, behavior
2. we don't emulate any aegis bugs, especially with regard to the value of HP that the scripts will see (through the `Hp` parameter)

Feel free to merge, reject or improve this, as long as the two above points are met.

**Comment by Smokexyz** [comment]
@Jedzkie PR fulfill's Haru's requirements. There are conflicting files and the build is failing. Do you want to update this?

**Comment by MishimaHaruna** [comment]
I extended this PR with a candidate fix for the issue discussed in IRC (characters respawning with 2 HP instead of 1).

@Jedzkie could you test that this still works as intended (with both the setting enabled and disabled), and we lost nothing during the rebase and the recent changes I added?

**Comment by MrKeiKun** [comment]
this can be removed from project board. @MishimaHaruna

**Pull request merged**
