### PR TITLE
Unittalk script cmd shouldn't display the hidden name of npc

### PR DESCRIPTION
**Pull request by Angelmelody**
my test:

    prontera,156,153,5	script	afda#123	4_F_MAID,{
     unittalk getnpcid(0),"Hi I m a npc!";
     close;
    }

npctest

after fixes

### CODE REVIEW

**Comment by dastgir** [comment]
@HerculesWS/developers

**Comment by MishimaHaruna** [comment]
Whoops :D Nice catch

**Comment by Emistry** [comment]
lol, i always thought that was actually intended and then they created the *npctalk to overcome this issue haha.

**Comment by MishimaHaruna** [comment]
I don't think it really was intended. The purpose for npctalk is that it's automatically attached to the current NPC (or can target a NPC by name), but the expected visible output should be the same. The `#hiddenpart` (just like the`::internalname`) of NPCs isn't something that players should care about, so it has no reason to be displayed in chat messages.

**Comment by MishimaHaruna** [comment]
Merged, thank you

**Pull request merged**
