### PR TITLE
RC_Player Implementation on item_db.conf

### PR DESCRIPTION
**Pull request by dastgir**
@malufett 
Once SCRedesign is complete, Merge this :)

(Note: RC_Player is only Renewal, RC_Player shouldn't work on pre-re)
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/HerculesWS/Hercules/pull/498%23issuecomment-93705850%22%2C%20%22https%3A//github.com/HerculesWS/Hercules/pull/498%23issuecomment-101662491%22%2C%20%22https%3A//github.com/HerculesWS/Hercules/pull/498%23issuecomment-101670728%22%2C%20%22https%3A//github.com/HerculesWS/Hercules/pull/498%23issuecomment-101671420%22%2C%20%22https%3A//github.com/HerculesWS/Hercules/pull/498%23issuecomment-101884297%22%2C%20%22https%3A//github.com/HerculesWS/Hercules/pull/498%23issuecomment-101884414%22%2C%20%22https%3A//github.com/HerculesWS/Hercules/pull/498%23issuecomment-109956883%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/HerculesWS/Hercules/pull/498%23issuecomment-93705850%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%40dastgir%20%5Cr%5Cnow%20I%20see..ok%20thanks...%3AD%5Cr%5Cn%3A%2B1%3A%20%22%2C%20%22created_at%22%3A%20%222015-04-16T10%3A45%3A43Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/3251821%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/malufett%22%7D%7D%2C%20%7B%22body%22%3A%20%22%40malufett%20%5Cr%5Cnany%20news%3F%20%3A%29%22%2C%20%22created_at%22%3A%20%222015-05-13T13%3A24%3A22Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/10024221%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/zackdreaver%22%7D%7D%2C%20%7B%22body%22%3A%20%22%40zackdreaver%20%5Cr%5CnI%27m%20waiting%20for%20Ind%20and%20Haru%27s%20review%20on%20my%20redesign...%5Cr%5Cn%22%2C%20%22created_at%22%3A%20%222015-05-13T13%3A55%3A19Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/3251821%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/malufett%22%7D%7D%2C%20%7B%22body%22%3A%20%22owh%20ok%2C%5Cr%5Cni%20see...%20will%20wait%22%2C%20%22created_at%22%3A%20%222015-05-13T13%3A57%3A53Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/10024221%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/zackdreaver%22%7D%7D%2C%20%7B%22body%22%3A%20%22conflicts%20%3A%28%22%2C%20%22created_at%22%3A%20%222015-05-14T02%3A29%3A25Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/4684880%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/EPuncker%22%7D%7D%2C%20%7B%22body%22%3A%20%22I%20know%20%2C%20but%20I%20won%27t%20update%20it%20till%20that%20branch%20is%20done%2C%20else%20there%20will%20again%20be%20conflicts...%22%2C%20%22created_at%22%3A%20%222015-05-14T02%3A30%3A47Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/2889931%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/dastgir%22%7D%7D%2C%20%7B%22body%22%3A%20%22List%20gears%20that%20only%20need%20RC_Player%2C%20without%20RC_DemiHuman%3A%5Cr%5Cn1293%5Cr%5Cn1294%5Cr%5Cn1395%5Cr%5Cn1396%5Cr%5Cn1436%5Cr%5Cn1492%5Cr%5Cn1587%5Cr%5Cn1832%5Cr%5Cn2016%5Cr%5Cn2483%5Cr%5Cn2484%5Cr%5Cn2485%5Cr%5Cn2586%5Cr%5Cn2587%5Cr%5Cn13072%5Cr%5Cn15046%5Cr%5Cn15047%5Cr%5Cn15048%5Cr%5Cn16020%5Cr%5Cn16021%5Cr%5Cn18113%5Cr%5Cn18114%22%2C%20%22created_at%22%3A%20%222015-06-08T11%3A27%3A12Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/10024221%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/zackdreaver%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>
- [ ] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/HerculesWS/Hercules/pull/498#issuecomment-93705850'>General Comment</a></b>
- <a href='https://github.com/malufett'></a> @dastgir
ow I see..ok thanks...:D
:+1:
- <a href='https://github.com/zackdreaver'></a> @malufett
any news? :)
- <a href='https://github.com/malufett'></a> @zackdreaver
I'm waiting for Ind and Haru's review on my redesign...
- <a href='https://github.com/zackdreaver'></a> owh ok,
i see... will wait
- <a href='https://github.com/EPuncker'></a> conflicts :(
- <a href='https://github.com/dastgir'></a> I know , but I won't update it till that branch is done, else there will again be conflicts...
- <a href='https://github.com/zackdreaver'></a> List gears that only need RC_Player, without RC_DemiHuman:
1293
1294
1395
1396
1436
1492
1587
1832
2016
2483
2484
2485
2586
2587
13072
15046
15047
15048
16020
16021
18113
18114

<a href='https://www.codereviewhub.com/HerculesWS/Hercules/pull/498?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/HerculesWS/Hercules/pull/498?approve=1'></a>&nbsp;<a href='https://github.com/HerculesWS/Hercules/pull/498'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by malufett** [comment]
@dastgir 
ow I see..ok thanks...:D
:+1:

**Comment by zackdreaver** [comment]
@malufett 
any news? :)

**Comment by malufett** [comment]
@zackdreaver 
I'm waiting for Ind and Haru's review on my redesign...

**Comment by zackdreaver** [comment]
owh ok,
i see... will wait

**Comment by EPuncker** [comment]
conflicts :(

**Comment by dastgir** [comment]
I know , but I won't update it till that branch is done, else there will again be conflicts...

**Comment by zackdreaver** [comment]
List gears that only need RC_Player, without RC_DemiHuman:
1293
1294
1395
1396
1436
1492
1587
1832
2016
2483
2484
2485
2586
2587
13072
15046
15047
15048
16020
16021
18113
18114

**Pull request closed without merging**
