### PR TITLE
Fixes Issue #688

### PR DESCRIPTION
**Pull request by Jedzkie**
Report No.1:  (Reference: http://forums.irowiki.org/showpost.php?p=1100558&postcount=104)

### CODE REVIEW

**Comment by Jedzkie** [comment]
@dastgir

**Comment by Jedzkie** [comment]
ItemDB Update reference:

<a href="http://tinypic.com?ref=do6nbn" target="_blank">Image and video hosting by TinyPic</a>

**Comment by dastgir** [comment]
The combo reference is from 2011, I guess something might have changed during these 4 years

**Comment by dastgir** [comment]
Seems fine , cross checked with last description available to me.

**Comment by emistry** [comment]
hmm why are these files included in the PR ?
https://github.com/Jedzkie/Hercules/commit/c66cac489b91e2fece28822d84e02d65b4b98071
```
conf/char-server.conf
conf/inter-server.conf
conf/map-server.conf
src/common/mmo.h
```

**Comment by Jedzkie** [comment]
@emistry I accidentally include them, I recommit this again.

**Pull request closed without merging**
