### PR TITLE
stopselling not cleaning items

### PR DESCRIPTION
**Pull request by dastgirp**
Currently, the items are not cleared, removal of items and adding them would result in duplicated items being sold in the shop.

### Pull Request Prelude

- [x] I have followed [proper Hercules code styling][code].
- [x] I have read and understood the [contribution guidelines][cont] before making this PR.
- [x] I am aware that this PR may be closed if the above-mentioned criteria are not fulfilled.

### Changes Proposed

Cleared the last element after the loop.

**Issues addressed:** 

[cont]: https://github.com/HerculesWS/Hercules/blob/master/CONTRIBUTING.md
[code]: https://github.com/HerculesWS/Hercules/wiki/Coding-Style

### CODE REVIEW

**Comment by AnnieRuru** [comment]
```
prontera,162,175,3	trader	Headgears Merchant 1	1_F_MERCHANT_01,{
OnInit:
	sellitem Ribbon_;
	stopselling Ribbon_;
	sellitem Ribbon_;
	stopselling Ribbon_;
	sellitem Ribbon_;
	stopselling Ribbon_;
	sellitem Ribbon_;
}
```
how to reproduce ? this ribbon only shows up 1 time on my test server

**Comment by dastgirp** [comment]
Try this:
```
prontera,162,175,3	trader	Headgears Merchant 1	1_F_MERCHANT_01,{
OnInit:
	sellitem 501, 1, 7227, 1;
        sellitem 502, 1, 7227, 1;
        sellitem 503, 1, 7227, 1;
        sellitem 504, 1, 7227, 1;
	stopselling 501, 7227, 1;
        stopselling 502, 7227, 1;
        stopselling 503, 7227, 1;
        stopselling 504, 7227, 1;
	sellitem 1002, 1 7227, 1;
        sellitem 1003, 1 7227, 1;
        sellitem 1004, 1 7227, 1;
}```

**Comment by AnnieRuru** [comment]
nope, still can't reproduce
```
/* demonstrate barter shop */
prontera,159,160,4	trader	Barter Shop#prt	4_M_KID1,{
OnInit:
	tradertype(NST_BARTER);
	sellitem White_Herb, 100, Red_Potion, 2;
	stopselling White_Herb, Red_Potion, 2;
	sellitem Blue_Herb, 200, Orange_Potion, 3;
	stopselling Blue_Herb, Orange_Potion, 3;
	sellitem Blue_Herb, 10, Orange_Potion, 3;
	end;
}
```
this sample was from [doc\sample\npc_trader_sample.txt](https://github.com/HerculesWS/Hercules/blob/stable/doc/sample/npc_trader_sample.txt#L59-L66)

tested everything there on that sample file and seems to be working fine without this PR

**Comment by dastgirp** [comment]
> nope, still can't reproduce
> 
> ```
> /* demonstrate barter shop */
> prontera,159,160,4	trader	Barter Shop#prt	4_M_KID1,{
> OnInit:
> 	tradertype(NST_BARTER);
> 	sellitem White_Herb, 100, Red_Potion, 2;
> 	stopselling White_Herb, Red_Potion, 2;
> 	sellitem Blue_Herb, 200, Orange_Potion, 3;
> 	stopselling Blue_Herb, Orange_Potion, 3;
> 	sellitem Blue_Herb, 10, Orange_Potion, 3;
> 	end;
> }
> ```
> 
> this sample was from [doc\sample\npc_trader_sample.txt](https://github.com/HerculesWS/Hercules/blob/stable/doc/sample/npc_trader_sample.txt#L59-L66)
> 
> tested everything there on that sample file and seems to be working fine without this PR

Did you try the sample provided by me?
Add multiple item, then remove them in the same sequence.
Then add another set of items

**Comment by AnnieRuru** [comment]
```c
prontera,162,175,3	trader	Headgears Merchant 1	1_F_MERCHANT_01,{
OnInit:
	tradertype(NST_BARTER);
	sellitem 501, 1, 7227, 1;
	sellitem 502, 1, 7227, 1;
	sellitem 503, 1, 7227, 1;
	sellitem 504, 1, 7227, 1;
	stopselling 501, 7227, 1;
	stopselling 502, 7227, 1;
	stopselling 503, 7227, 1;
	stopselling 504, 7227, 1;
	sellitem 1002, 1, 7227, 1;
	sellitem 1003, 1, 7227, 1;
	sellitem 1004, 1, 7227, 1;
}
```

do I have to post a screenshot as well ?

**Comment by MishimaHaruna** [comment]
I think that in order for this bug to occur, the `nd->u.scr.shop->item[]` list should have gaps (empty entries with item id set to 0), but I can't think of a way to make that happen. Can you reproduce the issue if you load that script on a mapserver just started and without prior errors on the console, @dastgirp ?

If there is indeed a way to create gaps in the list, then I believe this function shouldn't just clear `nd->u.scr.shop->item[cursor]`, but every index `>= cursor` and `< i`

**Comment by dastgirp** [comment]
I will have to test it more. As this was done with  little old source and customized one. It might be possible it's not happening in new hercules.

Will let you know the result.

**Comment by skyleo** [comment]
I'm gonna close this with the assumption that this wasn't able to be reproduced after in the last 4 years.

**Pull request closed without merging**
