### PR TITLE
Cash Foods Update

### PR DESCRIPTION
**Pull request by Jedzkie**
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

[//]: # (Note: Lines beginning with syntax such as this one, are comments and will not be visible in your report!)

### Pull Request Prelude

[//]: # (Thank you for working on improving Hercules!)

[//]: # (Please complete these steps and check the following boxes by putting an `x` inside the brackets _before_ filing your Pull Request.)

- [x] I have followed [proper Hercules code styling][code].
- [x] I have read and understood the [contribution guidelines][cont] before making this PR.
- [x] I am aware that this PR will be closed if the above-mentioned criteria are not fulfilled.

### Changes Proposed

[//]: # (Describe at length, the changes that this pull request makes.)

**Affected Branches:** master

[//]: # (Master? Slave?)

**Issues addressed:**

[//]: # (Issue Tracker Number if any.)

### Known Issues and TODO List
in kRO, you can still use cash foods, battle manual, bubble gum while the status effect is still active.
Status effects from Cash Food items cannot be removed by death.
 - ID12202
 - ID12203
 - ID12204
 - ID12205
 - ID12206
 - ID12207
Removed the cash food delay setting since we can set item usage delay in item_db.conf

[//]: # (Insert checklist here)
[//]: # (Syntax: - [ ] Checkbox)

[//]: # (**NOTE** Enable the setting "[√] Allow edits from maintainers." when creating your pull request if you have not already enabled it.)

[cont]: https://github.com/HerculesWS/Hercules/blob/master/CONTRIBUTING.md
[code]: https://github.com/HerculesWS/Hercules/wiki/Coding-Style

### CODE REVIEW

**Comment by HerculesWSAPI** [comment]
This change is [Reviewable](https://reviewable.io/reviews/herculesws/hercules/1695)

**Comment by MishimaHaruna** [comment]
The delay in item_db.conf is on an item by item basis, while the previous cash food delay setting that is getting removed is one for all the items (preventing to use all six items at once). Is this change intended?

**Comment by Jedzkie** [comment]
Let me try to use them all six at once. If its working in kRO same as in herc.

**Comment by Jedzkie** [comment]
Ugh

**Comment by Jedzkie** [comment]
@MishimaHaruna Upon testing in kRO and comparing to this PR, I got the same results, I can't use more than 1 cash food at once.

**Comment by MishimaHaruna** [comment]
But after this PR I can use them all at once:

**Comment by Jedzkie** [comment]
@MishimaHaruna it's intended.

**Comment by kyeme** [comment]
@Jedzkie but you said "Upon testing in kRO and comparing to this PR, I got the same results, I can't use more than 1 cash food at once."

**Comment by Jedzkie** [comment]
@kyeme well i thought, if I use the two or more cash foods at the same time. LOL

**Comment by Jedzkie** [comment]
@MishimaHaruna Here's the results in kRO.

!(http://imgur.com/a/NBb8z)

**Comment by Jedzkie** [comment]
@MishimaHaruna this is the result in kRO Sakray.

**Comment by Jedzkie** [comment]
@MishimaHaruna

**Comment by MishimaHaruna** [comment]
Ok, thanks for the tests in kRO, it's clear now

**Pull request merged**
