### PR TITLE
explode() return array size.

### PR DESCRIPTION
**Pull request by emistry**
http://herc.ws/board/topic/7489-explode-to-push-arraysize/

### CODE REVIEW

**Comment by emistry** [comment]
O__O ....my second pull request merged with this one .. lol ..
How do I separate it ?

**Comment by dastgir** [comment]
Use branches @emistry
First reset master branch with remote
Then for making sure you are on master
git checkout master
Then create new branch
git checkout -b BranchName
Apply your mods
Push as usual,
Then make PR with that branch.

(Tip: don't have edit master branch)

**Comment by emistry** [comment]
DELETED .. will recreate another PR.

**Comment by EPuncker** [comment]
and about that pcstatcalcevent, are you going to make PR for that?

**Comment by dastgir** [comment]
I doubt that will ever be accepted.

**Comment by EPuncker** [comment]
that is why I asked xD it was suggested already and denied bcz too resource intensive

**Comment by emistry** [comment]
since it's denied, I am not going to create a pull request for it.
those users who want the patch can use the link above to get it =D

**Pull request closed without merging**
