### PR TITLE
Remove skill->get_linked_song_dance_id

### PR DESCRIPTION
**Pull request by AnnieRuru**
before I follow the guidelines, (just copy paste anyway)
how to run HPMHook update on your own emulator ? (my own test server)

because this is even causing error when compiling locally

### CODE REVIEW

**Comment by 4144** [comment]
use ``make hooks``

**Comment by AnnieRuru** [comment]
`make hooks` as in `make sql` `make plugins` ?
means linux only ??
no windows option ???

time to fire up my google cloud machine again

```
[annie@centos Hercules]$ make hooks
        MAKE    hooks
make[1]: Entering directory '/home/annie/Hercules/tools/HPMHookGen'
doxygen not found or disabled by the configure script
make[1]: *** [Makefile:92: needs_doxygen] Error 1
make[1]: Leaving directory '/home/annie/Hercules/tools/HPMHookGen'
make: *** [Makefile:140: hooks] Error 2
[annie@centos Hercules]$ cd /home/annie/Hercules/
```

damn, I am very weak in linux

**Comment by 4144** [comment]
windows is not development platform. you can use WSL or WSL2 on windows for real development.

about errors, it said missing doxygen. if you using debina based system install it as ``apt-get install doxygen``

**Comment by guilherme-gm** [comment]
It used to be possible on windows, not sure if it still works: https://github.com/HerculesWS/Hercules/wiki/Generate-HPM-Hook-with-HPMHookGen.pl#generate-hpm-hook-on-windows

**Review by MishimaHaruna — APPROVED** [review]

**Pull request merged**
