### PR TITLE
global_configuration.md

### LINKED ISSUE #2216: turn the global conf documentation into markdown
`doc/global_configuration.txt` should be rewritten in markdown for easier reading in the browser and better organization.

proposed syntax:

``` markdown
# Global configuration reference

## What is global configuration?
…

## How does it work?
…

. . . 
```

### PR DESCRIPTION
**Pull request by linton-dawson**
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

[//]: # (Note: Lines beginning with syntax such as this one, are comments and will not be visible in your report!)

### Pull Request Prelude

[//]: # (Thank you for working on improving Hercules!)

[//]: # (Please complete these steps and check the following boxes by putting an `x` inside the brackets _before_ filing your Pull Request.)

- [x] I have followed [proper Hercules code styling][code].
- [x] I have read and understood the [contribution guidelines][cont] before making this PR.
- [x] I am aware that this PR will be closed if the above-mentioned criteria are not fulfilled.

### Changes Proposed
Turned doc/global_configuration.txt into Markdown format.

closes #2216 

[cont]: https://github.com/HerculesWS/Hercules/blob/master/CONTRIBUTING.md
[code]: https://github.com/HerculesWS/Hercules/wiki/Coding-Style

### CODE REVIEW

**Comment by HerculesWSAPI** [comment]
This change is [Reviewable](https://reviewable.io/reviews/herculesws/hercules/2229)

**Comment by linton-dawson** [comment]
> Why there's > in this line?

I thought it would be a bit "cleaner" if the documentation info was in blockquotes. Should I change it ?

**Comment by linton-dawson** [comment]
You're welcome ! :smile:

**Comment by 4144** [comment]
please remove merge commits from this pull request

**Pull request merged**
