### PR TITLE
New Entity Packets Implemented (Thanks to Rytech)

### PR DESCRIPTION
**Pull request by dastgir**

### CODE REVIEW

**Comment by kyeme** [comment]
@dastgir can you please also include the new view equip packet? thank you!
http://herc.ws/board/topic/9600-2015-05-13aragexe-release/?p=67096

**Comment by kyeme** [comment]
And this is normal? GM can't view the CC-Code of normal player?

**Comment by dastgir** [comment]
CCode, I will check if anything added (but CCode is character code encoded
```
1->8
2->6
3->7
4->0
5->1
6->2
7->4
8->9
9->5
0->3
```
Thus if char Id is 900, CCODE is 533

About view equip, will add that packet soon, since we just need one line for it, we already have new equip packets to support viewEquip

**Comment by dastgir** [comment]
@MishimaHaruna

**Comment by dastgir** [comment]
@kyeme Added the viewequip packet.
@MishimaHaruna @hemagx 
could you review and merge this?

**Comment by kyeme** [comment]
@dastgir thank you.

**Pull request merged**
