### PR TITLE
Issue and Pull Request Templates.

### PR DESCRIPTION
**Pull request by Smokexyz**
Initial implementation of issue and pull request templates for github that enforce certain basic requirements before submitting an issue or pull request.

Template follows basic markdown syntax.
More details on github templates can be found here - https://github.com/blog/2111-issue-and-pull-request-templates

---
This change is [Reviewable](https://reviewable.io/reviews/herculesws/hercules/1606)

### CODE REVIEW

**Comment by Smokexyz** [comment]
@MishimaHaruna @Mysteries

**Comment by Ridley8819** [comment]
@Mysteries please check spelling here

**Comment by MishimaHaruna** [comment]
lgtm

**Comment by Emistry** [comment]
about the checkbox part .... 
Image

aren't this may cause some wrong info display when we looking at the PR list? 
because it's shown as "Todo" list in the PR.

like this PR https://github.com/HerculesWS/Hercules/pull/374 did ..
Image

**Comment by Smokexyz** [comment]
I guess you could assume that the first `n` amount of checks are for the message prelude.

**Pull request merged**
