### PR TITLE
Make userid UNIQUE

### PR DESCRIPTION
**Pull request by kubixservice**
Now you can create two accounts with same userid (login)

[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

[//]: # (Note: Lines beginning with syntax such as this one, are comments and will not be visible in your report!)

### Pull Request Prelude

[//]: # (Thank you for working on improving Hercules!)

[//]: # (Please complete these steps and check the following boxes by putting an `x` inside the brackets _before_ filing your Pull Request.)

- [x] I have followed [proper Hercules code styling][code].
- [x] I have read and understood the [contribution guidelines][cont] before making this PR.
- [x] I am aware that this PR will be closed if the above-mentioned criteria are not fulfilled.

### Changes Proposed

[//]: # (Describe at length, the changes that this pull request makes.)

**Affected Branches:** 

[//]: # (Master? Slave?)

**Issues addressed:**

[//]: # (Issue Tracker Number if any.)

### Known Issues and TODO List

[//]: # (Insert checklist here)
[//]: # (Syntax: - [ ] Checkbox)

[//]: # (**NOTE** Enable the setting "[√] Allow edits from maintainers." when creating your pull request if you have not already enabled it.)

[cont]: https://github.com/HerculesWS/Hercules/blob/master/CONTRIBUTING.md
[code]: https://github.com/HerculesWS/Hercules/wiki/Coding-Style

### CODE REVIEW

**Comment by HerculesWSAPI** [comment]
This change is [Reviewable](https://reviewable.io/reviews/herculesws/hercules/2169)

**Comment by Emistry** [comment]
Missing SQL files for upgrade?
and if we're to follow the format, it should be something like `UNIQUE KEY `userid` (`userid`),`

May reference this https://github.com/HerculesWS/Hercules/commit/b35718cad265492d13e67c600855a8a45d5c1fbb#diff-ae5800534bb25effa37150c6874eb4ad

**Comment by dastgirp** [comment]
Also there's no need of default value for unique column

**Comment by kubixservice** [comment]
Updated. Don't know about default values, I left it. Also fixed char_achievements table. Someone forgot about `IF NOT EXISTS`

**Pull request closed without merging**
