### PR TITLE
ItemDB Format Update

### PR DESCRIPTION
**Pull request by dastgir**
* Changes Job Field in item_db.conf
* It is backward compatible (Or should I remove backward Compatibility?)
* Changes Job field to long long int to support more values

### CODE REVIEW

**Comment by hemagx** [comment]
Usage of long long int should be unsafe, I believe you should use uint64
instead

**Comment by dastgir** [comment]
@hemagx
libconfig accepts long long int variable,
so take it as long long int and save to uint64?

**Comment by hemagx** [comment]
Long long int can be smaller but not bigger than uint64

**Comment by dastgir** [comment]
@hemagx ,
But it leaves incompatible data type warning

**Comment by hemagx** [comment]
Let me go home and see

**Comment by dastgir** [comment]
@hemagx , changed to uint64

**Comment by Jedzkie** [comment]
@dastgir I see a little bug here, maybe you put specific Third Job Fields, on our current settings, the id#2480 (Black Wing Boots) cannot be worn by Hunter/Sniper Job even the level is 100+, in this new setting hunters can wear this if they reached 100+.

**Comment by dastgir** [comment]
Strange @Jedzkie (I haven't touched upper code), I will try this now and let you know what is the result

**Comment by dastgir** [comment]
@Jedzkie unable to reproduce

**Comment by dastgir** [comment]
@MishimaHaruna

**Comment by MishimaHaruna** [comment]
Merged via 7868637, thank you very much!

**Pull request closed without merging**
