### PR TITLE
Fix show_mob_info not working

### PR DESCRIPTION
**Pull request by AnnieRuru**
[cont]: https://github.com/HerculesWS/Hercules/blob/master/CONTRIBUTING.md
[code]: https://github.com/HerculesWS/Hercules/wiki/Coding-Style
### Pull Request Prelude
- [x] I have followed [proper Hercules code styling][code].
- [x] I have read and understood the [contribution guidelines][cont] before making this PR.
- [x] I am aware that this PR will be closed if the above-mentioned criteria are not fulfilled.

### Issues addressed
https://rathena.org/board/topic/118076-monster-level-not-showing/

### Changes Proposed
Fix show_mob_info not working

### Affected Branches
* Master

### Known Issues and TODO List

### CODE REVIEW

**Comment by HerculesWSAPI** [comment]
This change is [Reviewable](https://reviewable.io/reviews/herculesws/hercules/2358)

**Comment by Emistry** [comment]
Since its fixing the `show_mob_info`, do you think its possible to include some enhancement?
add new option to display other info like `element / race / size` using the guild name area for monster?

**Comment by AnnieRuru** [comment]
@dastgirp hahaha ~ didn't test this thoroughly

@Emistry doesn't seems can do like that now,
because using party_name and guild_name area for monsters doesn't seems to work
maybe we should find out which packet change causing this problem
and the name area only has 23 characters ....

**Comment by dastgirp** [comment]
@AnnieRuru are you sure it's not because of /showname?

**Comment by AnnieRuru** [comment]
ok be honest, I didn't know about the /showname

without this patch, just type /showname will display correctly
so how do we actually solve this with default newer client without typing /showname ?

**Comment by Emistry** [comment]
> @Emistry doesn't seems can do like that now,
because using party_name and guild_name area for monsters doesn't seems to work
maybe we should find out which packet change causing this problem

seem this done in the SEAR emulator, seem workable .... I did once long time ago, but it look ugly hence i dropped it and hope someone with better knowledge could do it xD

their format 
```
Monster Name (HP/MaxHP)   <--- Name/Party column
[Element: XXX] (Race:XXXX)    <--- Guildname / Position column
```

**Pull request closed without merging**
