### PR TITLE
RoDEX Update

### PR DESCRIPTION
**Pull request by dastgir**
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

[//]: # (Note: Lines beginning with syntax such as this one, are comments and will not be visible in your report!)

### Pull Request Prelude

[//]: # (Thank you for working on improving Hercules!)

[//]: # (Please complete these steps and check the following boxes by putting an `x` inside the brackets _before_ filing your Pull Request.)

- [x] I have followed [proper Hercules code styling][code].
- [x] I have read and understood the [contribution guidelines][cont] before making this PR.
- [x] I am aware that this PR will be closed if the above-mentioned criteria are not fulfilled.

### Changes Proposed

[//]: # (Describe at length, the changes that this pull request makes.)
RoDEX should not open, neither should send mail (packet manipulation) when it is disabled or NPC is opened.

**Affected Branches:** 

* [x] master

[//]: # (Master? Slave?)

**Issues addressed:**

[//]: # (Issue Tracker Number if any.)
* [x] #1934 

### Known Issues and TODO List

[//]: # (Insert checklist here)
[//]: # (Syntax: - [ ] Checkbox)

[//]: # (**NOTE** Enable the setting "[√] Allow edits from maintainers." when creating your pull request if you have not already enabled it.)

[cont]: https://github.com/HerculesWS/Hercules/blob/master/CONTRIBUTING.md
[code]: https://github.com/HerculesWS/Hercules/wiki/Coding-Style

### CODE REVIEW

**Comment by HerculesWSAPI** [comment]
This change is [Reviewable](https://reviewable.io/reviews/herculesws/hercules/1936)

**Comment by 4144** [comment]
Against script bugs this changes do nothing. It only add mostly useless extra limits.

Is this is official way? If not probable better add option for extra checks and disable it by default.

**Comment by kyeme** [comment]
On official you can still use Rodex while interacting to npc. Maybe add config to enable or disable this option.

**Comment by dastgir** [comment]
Asheraf confirmed that you can open rodex, but cannot send mails

**Pull request merged**
