### PR TITLE
Fixed Issue #2180

### PR DESCRIPTION
**Pull request by dastgirp**
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

[//]: # (Note: Lines beginning with syntax such as this one, are comments and will not be visible in your report!)

### Pull Request Prelude

[//]: # (Thank you for working on improving Hercules!)

[//]: # (Please complete these steps and check the following boxes by putting an `x` inside the brackets _before_ filing your Pull Request.)

- [x] I have followed [proper Hercules code styling][code].
- [x] I have read and understood the [contribution guidelines][cont] before making this PR.
- [x] I am aware that this PR will be closed if the above-mentioned criteria are not fulfilled.

### Changes Proposed

[//]: # (Describe at length, the changes that this pull request makes.)
OnEquipScript and OnUnequipScript is now not called if equipment/card is nullified

**Affected Branches:** 

[//]: # (Master? Slave?)

**Issues addressed:**

#2180 

### Known Issues and TODO List

[//]: # (Insert checklist here)
[//]: # (Syntax: - [ ] Checkbox)

[//]: # (**NOTE** Enable the setting "[√] Allow edits from maintainers." when creating your pull request if you have not already enabled it.)

[cont]: https://github.com/HerculesWS/Hercules/blob/master/CONTRIBUTING.md
[code]: https://github.com/HerculesWS/Hercules/wiki/Coding-Style

### CODE REVIEW

**Comment by HerculesWSAPI** [comment]
This change is [Reviewable](https://reviewable.io/reviews/herculesws/hercules/2207)

**Comment by kyeme** [comment]
Still not working.. tested in Eddga_Card

**Comment by MishimaHaruna** [comment]
What do you mean by still not working @kyeme ? Does it not resolve the problem described in #2180 at all?

**Comment by kyeme** [comment]
Yes. The bug still exist.

**Comment by kyeme** [comment]
What happened to github? I'm unable to comment.

**Comment by MishimaHaruna** [comment]
There was an outage https://blog.github.com/2018-10-21-october21-incident-report/ (which apparently still isn't fully solved) - I had to delay yesterday's release to today, as the commands issued from the web were failing most of the time

**Comment by MishimaHaruna** [comment]
@kyeme which value do you have in your `unequip_restricted_equipment` configuration flag?

**Comment by MishimaHaruna** [comment]
Closing this in favor of #2642

**Pull request closed without merging**
