### PR TITLE
Fix some wrong return values in mob skill code

### PR DESCRIPTION
**Pull request by Kenpachi2k13**
### Pull Request Prelude

- [x] I have followed [proper Hercules code styling][code].
- [x] I have read and understood the [contribution guidelines][cont] before making this PR.
- [x] I am aware that this PR may be closed if the above-mentioned criteria are not fulfilled.

### Changes Proposed

- Fix return value evaluation of `mob_skill_use()` in `mob_ai_sub_hard()`.
- Fix `nullpo`-check return values in `mob_skill_use()`.
- Fix `nullpo`-check return values and initial value of variable `ret` in `mobskill_event()`.
- Rename `mob->skill_use()` to `mob->use_skill()` due to changed return values.
- Rename `mob->skill_event()` to `mob->use_skill_event()` due to changed return values.

**Issues addressed:** None.

[cont]: https://github.com/HerculesWS/Hercules/blob/master/CONTRIBUTING.md
[code]: https://github.com/HerculesWS/Hercules/wiki/Coding-Style

### CODE REVIEW

**Review by 4144 — APPROVED** [review]

**Comment by skyleo** [comment]
What confuses me a bit about this PR is that I see no commit that is purely dedicated to changing the return value logic.
But there's commits that rename functions due to their return value logic having changed. Can you post a reference to the previous commits that I need to know for this?

**Comment by skyleo** [comment]
mob_use_skill has a typo in it's documentation btw.

**Comment by Kenpachi2k13** [comment]
> What confuses me a bit about this PR is that I see no commit that is purely dedicated to changing the return value logic.
> But there's commits that rename functions due to their return value logic having changed. Can you post a reference to the previous commits that I need to know for this?

Aye-aye, sir!
https://github.com/HerculesWS/Hercules/pull/2691/commits/452b603ae4812bac490b4591f08a6f08d1571515

> mob_use_skill has a typo in it's documentation btw.

Captain eagle eye. :laughing:
I'll fix it....

**Comment by skyleo** [comment]
@Kenpachi2k13 I think you have to set res = 1 in mobskill_event as well due to how the return values changed.

**Comment by Kenpachi2k13** [comment]
> @Kenpachi2k13 I think you have to set res = 1 in mobskill_event as well due to how the return values changed.

I did. :open_mouth:
https://github.com/HerculesWS/Hercules/pull/2887/commits/521ca008dee8d85f1617554a71dc95f126b64be2

But thanks to your comment I just realised that I forgot to separate the declaractions of `target_id` and `res`. 👍

**Review by skyleo — APPROVED** [review]

**Review by MishimaHaruna — APPROVED** [review]

**Pull request merged**
