### PR TITLE
Implementation of the Achievement system

### PR DESCRIPTION
**Pull request by marcosbucarte**
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

[//]: # (Note: Lines beginning with syntax such as this one, are comments and will not be visible in your report!)

### Pull Request Prelude

[//]: # (Thank you for working on improving Hercules!)

[//]: # (Please complete these steps and check the following boxes by putting an `x` inside the brackets _before_ filing your Pull Request.)

- [x] I have followed [proper Hercules code styling][code].
- [x] I have read and understood the [contribution guidelines][cont] before making this PR.
- [x] I am aware that this PR will be closed if the above-mentioned criteria are not fulfilled.

### Changes Proposed

This is a rebase and some fixes in the Achievement system of smokexyz

[//]: # (Describe at length, the changes that this pull request makes.)

**Affected Branches:** Master

### CODE REVIEW

**Comment by HerculesWSAPI** [comment]
This change is [Reviewable](https://reviewable.io/reviews/herculesws/hercules/2026)

**Comment by Jedzkie** [comment]
is Title system includes in this PR?

**Comment by marcosbucarte** [comment]
@Asheraf The rebase was done but I do not know what happened that pulled the merge when I solved the conflicts. 

What is missing ?

**Comment by Asheraf** [comment]
From the original pr comments `achievement_readdb_validate_criteria_itemtype` is using wrong mixed constants, also the converter needs support for handling buffs and there's some problems with display on some client versions which need to be fixed.

**Comment by marcosbucarte** [comment]
@Asheraf So it's to swap the IT enumeration by OBJ_IT enumeration and update the database to new type, is that it?

**Comment by EyesOfAHawk** [comment]
god speed marcosbucarte

**Comment by marcosbucarte** [comment]
After doing some tests I realized I need to write a lot of things yet.

Title system, scripts,... for this reason I will leave this to someone else who understands more about the system, sorry anything

**Pull request closed without merging**
