### PR TITLE
Fix various ShowWarning that doesn't tell the source of the error

### PR DESCRIPTION
**Pull request by AnnieRuru**
`return true;`
means its ok.

`return false;`
means the script will still run, nothing wrong, but it just report the source of the error

if want to halt the script, use `st->state = END;`

if want to report the source of error without using return false, use `script->reportsrc(st)`

### CODE REVIEW

**Comment by dastgir** [comment]
Seems good to be merged.
@4144

**Comment by 4144** [comment]
Why not add "return false" to other functions if error happend?
For example in strcharinfo.

**Comment by AnnieRuru** [comment]
`return false;` only shows the debug message of the source npc
it doesn't tell `Player not Attached!` error
only `script->rid2sd(st)` has the ShowError message on it, `map->id2sd(id)` don't

for `(strcharinfo)` case,
the `script->rid2sd(st)` already has `script->reportsrc(st);` inside the `*script_rid2sd` function
if change `if (!sd) return true;` into `return false;` the source npc will show twice

**Comment by AnnieRuru** [comment]
err ... bump ?

**Comment by MishimaHaruna** [comment]
Merged, thank you!

**Pull request closed without merging**
