### PR TITLE
Item Restrictions Updated to match info from kRO

### PR DESCRIPTION
**Pull request by dastgir**
Data from itemmoveinfov5.txt is been used as reference.
Thanks to Rytech for giving us the hint that the file is been put on client.
@MishimaHaruna @Streusel @malufett 
If anyone want to review it?
Else I will merge it in few days, if there's no problem with it.

### CODE REVIEW

**Comment by dastgir** [comment]
Do not merge till I commit a next fix

**Comment by dastgir** [comment]
Nodrop bug fixed.

**Comment by dastgir** [comment]
Following file is converted from data.grf
And there's one on rdata.grf(which is having some other restrictions than data.grf), but I think rdata keeps changing as its sakray and we should prefer one on main server.
Which should be so preferred? @Streusel @malufett @MishimaHaruna

**Comment by MishimaHaruna** [comment]
data.grf should be preferred, for sakray is an ever-changing beta-server, and not everything that is tested on sakray makes it to the main servers.

**Comment by dastgir** [comment]
Will wait for a day before merging, if ever someone wants to leave their thoughts.

**Comment by MishimaHaruna** [comment]
Please wait until someone can confirm that items like White_Slim_Potion, Old_Blue_Box, Old_Violet_Box, really can't be traded/dropped on official servers, while other items, such as the Brave/Valorous items, or even the wedding rings can. It looks very suspicious.

**Comment by dastgir** [comment]
@MishimaHaruna 
Ok I confirmed via client: http://i.imgur.com/WAhDrGp.jpg 
The Format mentioned in client is wrong(the header says CanDrop, but 1 = Cannot drop)
So All thing will be reversed.
will commit a fix soon.

**Comment by dastgir** [comment]
Now Its fine, I reversed the order in my tool(which is what was intended),
Just review it :)

**Comment by MishimaHaruna** [comment]
Yup, seems much more reasonable now. I can't possibly go through each and every item, but I checked a reasonably large sample, and the restrictions seem correct. I believe it's good enough to merge.

Is there anything like this for pre-renewal from any official servers, by the way?

**Comment by dastgir** [comment]
Its hard to get information from pre-re,
since we got this text file directly into client, so I guess pre-re should be untouched.

**Comment by MishimaHaruna** [comment]
I agree. Better to leave pre-renewal untouched, since we don't know whether some restrictions were added or changed afterwards.

**Pull request merged**
