### PR TITLE
change int to unsigned int in map iterators

### PR DESCRIPTION
**Pull request by madwof**
### Pull Request Prelude

- [x] I have followed [proper Hercules code styling][code].
- [x] I have read and understood the [contribution guidelines][cont] before making this PR.
- [x] I am aware that this PR may be closed if the above-mentioned criteria are not fulfilled.

### Changes Proposed

Change map iterators from **int** to **unsigned int**, to prevent receive negative numbers from (for example) **buildin_getunits** and broke iterations.

Debug in map_forcountinmap

**Issues addressed:** 

[cont]: https://github.com/HerculesWS/Hercules/blob/master/CONTRIBUTING.md
[code]: https://github.com/HerculesWS/Hercules/wiki/Coding-Style

### CODE REVIEW

**Comment by HerculesWSAPI** [comment]
This change is [Reviewable](https://reviewable.io/reviews/herculesws/hercules/2346)

**Comment by madwof** [comment]
@Helianthella @4144

**Comment by Asheraf** [comment]
@madwof I would refer you to a comment from @MishimaHaruna about the usage of unsigned variables, https://github.com/HerculesWS/Hercules/issues/959#issuecomment-167641947

If getunits can return a negative number then probably it's better to check for it and return 0 or w/e is needed.

**Comment by 4144** [comment]
can you show script example how you get -2?

**Comment by madwof** [comment]
@4144 
`.@count = getunits(BL_PC, .@units, false, "prontera");`

**Comment by madwof** [comment]
@Asheraf that's not a way, only way to fix that without editing iterators is change a **SCRIPT_MAX_ARRAYSIZE** const to **INT_MAX - 1**, but what's about other possible ways when some negative numbers comes here, iterators and limit can't be negative, so i think no problem with changing it

**Comment by Asheraf** [comment]
@madwof that is actually the plan, to change `SCRIPT_MAX_ARRAYSIZE` into a signed value, you can look at the branch [signed-array-index](https://github.com/HerculesWS/Hercules/commits/signed-array-index) for progress on that.

**Comment by AnnieRuru** [comment]
saw the chat in discord, leads me here
https://github.com/HerculesWS/Hercules/pull/2093 - weird, I thought its already INT_MAX - 1
```
prontera,155,185,5	script	kjfhkshf	1_F_MARIA,{
	.@count = getunits(BL_PC, .@units, false, "prontera");
	dispbottom .@count +"";
}
```
display the numbers correctly though

**Comment by madwof** [comment]
It's not actually only script engine issue, it can be happened in any place of code, problem with **buildin_getunits** is not an issue, it's a consequence.. iteration limits cant't be negative anyway ;)

**Comment by madwof** [comment]
Does this bug is not critical? Ofc it's very hard to reproduce the problem in real situations right now (except buildin_getunits), but it's still presents, if in some place of code some INT_MAX +1 or similar comes as the limit, it breaks iteration. Any comments from @4144 @MishimaHaruna @Helianthella?

**Comment by AnnieRuru** [comment]
I'm actually more interest to know how you get that message
I don't see any ShowDebug with map_forcountinmap function ....
means you have custom source code ... or plugin to display that message

**Comment by madwof** [comment]
@AnnieRuru can u write please your configuration and SCRIPT_MAX_ARRAYSIZE value please?

0xfffffffe : -2 on Int, always..

**Comment by AnnieRuru** [comment]
I don't understand what you are trying to achieve
its like you want to nitpick on the value that is not yet iterate

of course when any variable initialize in C, the numbers are random

**Comment by MishimaHaruna** [comment]
Closing this pull request, since I'm strongly against using unsigned values in any arithmetic operations

**Pull request closed without merging**
