### PR TITLE
Update item_db.conf

### PR DESCRIPTION
**Pull request by Emistry**
- remove extra usage of `getrefine()`.

---
This change is [Reviewable](https://reviewable.io/reviews/herculesws/hercules/1441)

### CODE REVIEW

**Comment by MishimaHaruna** [comment]
Could you clarify the point of this commit? Is there something wrong with `getrefine()`? As far as I'm aware, it's faster than setting a variable (and also more readable).

**Comment by Emistry** [comment]
hmm .. when the item calling several time `getrefine()` isnt it would affect performance?

Example:
```
if ( getrefine() > 5 ) {
  // bonus A
}
if ( getrefine() > 7) {
  // bonus B
}
if ( getrefine() > 10) {
  // bonus C
}
if ( getrefine() > 12) {
  // bonus D with another new getrefine() in parameter
}
```
total 5 times of `getrefine()` ...
so I think it's more efficient to save it into a variable and use it in later bonuses.

```
.@refine = getrefine();
if ( .@refine > 5 ) {
  // bonus A
}
if ( .@refine > 7) {
  // bonus B
}
if ( .@refine > 10) {
  // bonus C
}
if ( .@refine > 12) {
  // bonus D with .@refine in parameter
}
```

since I saw some of the itemdb are using stored variable like `.@rate` and `.@r` too in certain bonuses to avoid calling the script command or doing the operation multiple times.

**Comment by MishimaHaruna** [comment]
the getrefine command isn't much slower than setting/reading variables... From my tests, using a variable is only better if you have more than 6 or 7 getrefine() in the same item script... But considering there isn't a really big difference, and getrefine is more readable than playing with variables, I'd always use getrefine unless there are 10+ calls...

**Comment by MishimaHaruna** [comment]
This is what I used to test it by the way:

```
	freeloop(true);

	.@start = gettimetick(0);
	for (.@i = 0; .@i < 1000000; ++.@i) {
		if (getrefine() > 0 // 1 call
		 || getrefine() > 0 // 2 calls
		 || getrefine() > 0 // 3 calls
		 || getrefine() > 0 // 4 calls
		 || getrefine() > 0 // 5 calls
		 || getrefine() > 0 // 6 calls
		 || getrefine() > 0 // 7 calls
		 || getrefine() > 0 // 8 calls
		 || getrefine() > 0 // 9 calls
		 || getrefine() > 0 // 10 calls
		) {
			// No-op
		}
	}

	debugmes("getrefine(): " + (gettimetick(0) - .@start) + "ms");

	.@start = gettimetick(0);
	for (.@i = 0; .@i < 1000000; ++.@i) {
		.@refine = getrefine();
		if (.@refine > 0 // 1 call
		 || .@refine > 0 // 2 calls
		 || .@refine > 0 // 3 calls
		 || .@refine > 0 // 4 calls
		 || .@refine > 0 // 5 calls
		 || .@refine > 0 // 6 calls
		 || .@refine > 0 // 7 calls
		 || .@refine > 0 // 8 calls
		 || .@refine > 0 // 9 calls
		 || .@refine > 0 // 10 calls
		) {
			// No-op
		}
	}
	debugmes(".@refine: " + (gettimetick(0) - .@start) + "ms");
```

and here the results (actually, testing it again now that I cleaned up the script, getrefine is still better up to 12 calls...):

// 1 call:
[Debug]: script debug : 0 110000000 : getrefine(): 1680ms
[Debug]: script debug : 0 110000000 : .@refine: 1967ms

// 2 calls:
[Debug]: script debug : 0 110000000 : getrefine(): 1876ms
[Debug]: script debug : 0 110000000 : .@refine: 2212ms

// 3 calls:
[Debug]: script debug : 0 110000000 : getrefine(): 2128ms
[Debug]: script debug : 0 110000000 : .@refine: 2472ms

// 4 calls:
[Debug]: script debug : 0 110000000 : getrefine(): 2353ms
[Debug]: script debug : 0 110000000 : .@refine: 2630ms

// 5 calls:
[Debug]: script debug : 0 110000000 : getrefine(): 2567ms
[Debug]: script debug : 0 110000000 : .@refine: 2816ms

// 6 calls:
[Debug]: script debug : 0 110000000 : getrefine(): 2827ms
[Debug]: script debug : 0 110000000 : .@refine: 3018ms

// 7 calls:
[Debug]: script debug : 0 110000000 : getrefine(): 3079ms
[Debug]: script debug : 0 110000000 : .@refine: 3239ms

// 8 calls:
[Debug]: script debug : 0 110000000 : getrefine(): 3261ms
[Debug]: script debug : 0 110000000 : .@refine: 3421ms

// 9 calls:
[Debug]: script debug : 0 110000000 : getrefine(): 3476ms
[Debug]: script debug : 0 110000000 : .@refine: 3608ms

// 10 calls:
[Debug]: script debug : 0 110000000 : getrefine(): 3761ms
[Debug]: script debug : 0 110000000 : .@refine: 3868ms

// 11 calls:
[Debug]: script debug : 0 110000000 : getrefine(): 3979ms
[Debug]: script debug : 0 110000000 : .@refine: 3999ms

// 12 calls:
[Debug]: script debug : 0 110000000 : getrefine(): 4178ms
[Debug]: script debug : 0 110000000 : .@refine: 4212ms

// 13 calls:
[Debug]: script debug : 0 110000000 : getrefine(): 4400ms
[Debug]: script debug : 0 110000000 : .@refine: 4388ms

**Comment by Emistry** [comment]
oic... didnt aware of these ...
i guess the PR can be closed then :D

**Pull request closed without merging**
