### PR TITLE
Different rodex fixes

### PR DESCRIPTION
**Pull request by 4144**
### Pull Request Prelude

- [x] I have followed [proper Hercules code styling][code].
- [x] I have read and understood the [contribution guidelines][cont] before making this PR.
- [x] I am aware that this PR may be closed if the above-mentioned criteria are not fulfilled.

### Changes Proposed

Improve rodex attach handling.
Clean mail list on refresh rodex.

### CODE REVIEW

**Comment by HerculesWSAPI** [comment]
This change is [Reviewable](https://reviewable.io/reviews/herculesws/hercules/2437)

**Comment by tlacson7** [comment]
I hope this fix rare instances of lost item to rodex. I did disable the mail system due to this problem.
- player gets failed to attach then item is missing already.

**Comment by 4144** [comment]
@tlacson7 you sure on attach you can lost items?
probably it visually removed and if restart client, all items still in inventory? Can you explain steps how you get this issue?

**Comment by tlacson7** [comment]
@4144 i can't reproduce also the problem. It is lost even after closing client. I tra ed the uniqueid and it ends there -1 item on log. Cant find it anywhere in database. Its a rare case like 4 of them already.

**Pull request merged**
