### PR TITLE
Add bAddMaxWeight bonus for increasing player's max weight

### PR DESCRIPTION
**Pull request by AnnieRuru**
I'm so amazed that my bAddMaxWeight bonus has been added in rAthena long time ago,
https://github.com/rathena/rathena/commit/0b6c542
but nobody actually pull request here before

the reason is this
https://rathena.org/board/tracker/issue-8541-set-maxweight-item-script-error/

### CODE REVIEW

**Comment by dastgir** [comment]
Why this isn't merged yet?

**Comment by AnnieRuru** [comment]
don't ask me, ask one of the core developers
Ind has asked me to pull request anything that touch the source code,
until explicitly review by one of the core developer =/

**Comment by hemagx** [comment]
is it safe ? 
the bonus is temporary and player can lose it and then become over actual weight?

**Comment by AnnieRuru** [comment]
the idea is, having an item pouch as accessory to increase player maximum weight limit
and we have been doing `MaxWeight += 10000;` all this time,
until the bug report in rathena I linked to came out

yes its temporary
if the player unequip the item pouch having this bonus, they will become overweight
the idea is for the players who wants to increase their weight to spam more pots ...
yes this is custom ... already in rathena repo for a long time ...

**Comment by MishimaHaruna** [comment]
Thank you! merged as 478776d998e0fb48d87cd4c49229a1cf1b8cc203

**Pull request closed without merging**
