### PR TITLE
Removed Hard Coded data for SC_ALL_RIDING.

### PR DESCRIPTION
**Pull request by Jedzkie**

### CODE REVIEW

**Comment by 4144** [comment]
hm, may be split into two commits one with adding spaces, and second with actual removing hard coded data?

**Comment by AnnieRuru** [comment]
agree with 4144

Jedzkie has earn the title `Master of White Space Edit` !

**Comment by hemagx** [comment]
Fixing syntax should only be around the exact modified code, unless it's syntax fixing commit.
please separate them into two commits or fix your commit.

**Comment by Jedzkie** [comment]
@annieruru thats what im waiting for a long long time, my i get that title in forums? Hahahahahahhaha

**Comment by hemagx** [comment]
Mysterious it's your call

**Comment by AnnieRuru** [comment]
@Jedzkie 
on the forum
User CP -> Profile Settings -> Profile Information -> Member Title
you can do it yourself LOL XD

**Comment by Jedzkie** [comment]
done. @AnnieRuru xD

**Comment by dastgir** [comment]
@Jedzkie Split it into 2 commits... (Whitespace and Removing the Hardcoded value)

**Comment by Jedzkie** [comment]
@dastgir @AnnieRuru  Done. xD

**Pull request merged**
