### PR TITLE
Script cleanup

### PR DESCRIPTION
**Pull request by dastgir**
* [x] ItemID to Constants.

### CODE REVIEW

**Comment by dastgir** [comment]
Done, anyone want to review?

**Comment by AnnieRuru** [comment]
me me me !!
let me see ....

**Comment by AnnieRuru** [comment]
in `npc/custom/events/uneasy_cemetery.txt`
try change that `killmonsterall "prontera";` into `killmonster "Uneasy_Check::OnZombieDead";`
because if the players are having custom mob slave, they are killed as well
though its not your fault

**Comment by dastgir** [comment]
This PR was specifically for ItemID to Constants

**Comment by AnnieRuru** [comment]
https://github.com/HerculesWS/Hercules/blob/master/npc/other/poring_war.txt
read closely, the `callsub S_PoringVending,7515,4;` <-- that 7515 is Item ID
you didn't change them into constant

**Comment by dastgir** [comment]
I actually looked only onto some script command which have Id field...

**Comment by AnnieRuru** [comment]
and getitemname(x)

**Comment by AnnieRuru** [comment]
and lastly, 
https://github.com/HerculesWS/Hercules/blob/master/npc/re/quests/cupet.txt
```
	setarray .@tame_id[0],619,620,622,623,624,627,628,629,630;
	setarray .@tame_amount[0],3,3,3,3,3,3,3,3,3;
	setarray .@hunt_id[0],909,909,705,916,935,919,919,940,921;
	setarray .@hunt_amount[0],500,600,500,500,500,500,600,500,500;
	setarray .@mob_id[0],1002,1113,1063,1049,1011,1167,1107,1052,1014;
```
into constants
I'm sure there are more files having like this

**Comment by dastgir** [comment]
Converted all whatever you have mentioned.

**Comment by AnnieRuru** [comment]
there are MORE !
https://github.com/dastgir/Hercules/blob/25409474f725081b813fd079e2ddee67dc218057/npc/re/jobs/3-2/shadow_chaser.txt
```
-		if (.@i == 1) setarray .@i[1],6121,1,10,100000;
-		else if (.@i == 2) setarray .@i[1],6122,2,30,200000;
+		if (.@i == 1) setarray .@i[1],Makeover_Brush,1,10,100000;
+		else if (.@i == 2) setarray .@i[1],Paint_Brush,2,30,200000;
```
you only change once, there are 3 more

and also try search in files with `getitem getarg(`
there are a lot of them haven't fix yet
or wanna go another phase ?
since there are a lot

**Comment by dastgir** [comment]
I know there are more, I only targetted Direct ID in getitem in this PR,  I will update others as I get time..

**Comment by MishimaHaruna** [comment]
Is this ready to merge?

**Comment by dastgir** [comment]
Yes,
This PR only targets direct ID->constant
I will open new PR in few days for remaining id's that are saved in variable..

So this PR is ready.

**Comment by MishimaHaruna** [comment]
Merged, thank you very much!

**Pull request closed without merging**
