### PR TITLE
update colors to constants

### PR DESCRIPTION
**Pull request by Asheraf**
This change is [Reviewable](https://reviewable.io/reviews/herculesws/hercules/1413)

### CODE REVIEW

**Comment by hemagx** [comment]
@Asheraf please check the travis build issue.

**Comment by MishimaHaruna** [comment]
By the way, where are those fancy color names from? (Whats "Ribbon Blue"? "Tenn"? "Malibu"? Are those even colors?)

We should perhaps try and stick to standard color names, to avoid this blowing out of proportion and risking conflicts/confusion...

X11 color names are a good bet for example (but not all of them, they're way too many): https://en.wikipedia.org/wiki/X11_color_names
Or also the HTML color names https://en.wikipedia.org/wiki/Web_colors#X11_color_names

**Comment by Asheraf** [comment]
@MishimaHaruna the main issue that make me still unable to complete this pr is the color names ^^ im gonna check the ones you provided.

**Comment by Asheraf** [comment]
im gonna start this again in another pr.

**Pull request closed without merging**
