### PR TITLE
Hide area packets from hidden players/gms.

### PR DESCRIPTION
**Pull request by 4144**
This change is [Reviewable](https://reviewable.io/reviews/herculesws/hercules/1200)

### CODE REVIEW

**Comment by ZiriusPH** [comment]
will this allow players occupy the tile an invisible GM is using? sometimes a spectating GM can be a problem for players. would be a great addition.

**Comment by anacondaqq** [comment]
yes it is, thx a lot for fix, and that is very very very very strange, that noone fix it earlier.

**Comment by EPuncker** [comment]
:+1:

**Comment by AnisotropicDefixation** [comment]
If someone goes into @hiding on sight, this will leave the character's afterimage on the spot until refresh or map change.

**Comment by Smokexyz** [comment]
@4144 @hemagx this looks good, why is it kept on hold?

**Comment by Ridley8819** [comment]
'If someone goes into @hiding on sight, this will leave the character's afterimage on the spot until refresh or map change.'

**Comment by Smokexyz** [comment]
He pushed on March 15, 2016, assuming that a fix was added.

**Comment by Smokexyz** [comment]
Probable cause is that area packets are sent after `OPTION_INVISIBLE` is set.

**Comment by EyesOfAHawk** [comment]
bump

**Comment by EyesOfAHawk** [comment]
I found a simple, band-aid fix for this is to simply add `pc->setpos` to the hide() command.

At the very start of the command, save the characters current coordinates, then warp them to their savepoint (or somewhere random on the map).
```
ACMD(hide) {
+ unsigned short sd_map = sd->mapindex;
+ int x = sd->bl.x, y = sd->bl.y;
if (pc_isinvisible(sd)) {
```

Then after clif->changeoption
```
clif->changeoption(&sd->bl);
+ pc->setpos(sd, sd_map, x, y, CLR_TELEPORT);

return true;
```

It's a really bad fix for the after-image issue, but if you want to use this bit, it works well enough.

**Comment by mekolat** [comment]
@EyesOfAHawk yes this is exactly what we had to do [in tmwAthena](https://github.com/themanaworld/tmwa/blob/master/src/map/pc.cpp#L5217).
It needs to behave as if the player logged out

**Pull request merged**
