### PR TITLE
Cleaned up spirit charms implementation

### PR DESCRIPTION
**Pull request by MishimaHaruna**
Please do not merge (it's still a work in progress). I'm opening this just for discussion.

### CODE REVIEW

**Comment by rud0lp20** [comment]
:+1:

**Comment by MishimaHaruna** [comment]
I believe this is ready to merge, if anyone can review it.

I decided not to merge spirit balls and spirit charms implementations because of the different maximum amounts (and uncertainty as to whether it's officially possible to create a condition for a character to have both spirit balls and spirit charms at the same time).

**Comment by rud0lp20** [comment]
not yet merge to spiritball?
' (and uncertainty as to whether it's officially possible to create a condition for a character to have both spirit balls and spirit charms at the same time).' 
-yes it is possible...

**Comment by MishimaHaruna** [comment]
Then I think it's better to keep the implementation separated... if they were mutually exclusive, it'd make more sense to merge them and re-use the timers array. (or if you have a suggestion on an efficient way to merge them otherwise, I'd be happy to see it :3)

**Comment by rud0lp20** [comment]
ok then..let's merge this...

**Pull request merged**
