### PR TITLE
Check allowed range for "View" field in item_db for weapon items.

### PR DESCRIPTION
**Pull request by 4144**

### CODE REVIEW

**Comment by Lemongrass3110** [comment]
I could be mistaken, but does the look field not use the enum:
```
enum weapon_type {
	W_FIST,	//Bare hands
	W_DAGGER,	//1
	W_1HSWORD,	//2
	W_2HSWORD,	//3
	W_1HSPEAR,	//4
	W_2HSPEAR,	//5
	W_1HAXE,	//6
	W_2HAXE,	//7
	W_MACE,	//8
	W_2HMACE,	//9 (unused)
	W_STAFF,	//10
	W_BOW,	//11
	W_KNUCKLE,	//12
	W_MUSICAL,	//13
	W_WHIP,	//14
	W_BOOK,	//15
	W_KATAR,	//16
	W_REVOLVER,	//17
	W_RIFLE,	//18
	W_GATLING,	//19
	W_SHOTGUN,	//20
	W_GRENADE,	//21
	W_HUUMA,	//22
	W_2HSTAFF,	//23
	MAX_WEAPON_TYPE,
	// dual-wield constants
	W_DOUBLE_DD, // 2 daggers
	W_DOUBLE_SS, // 2 swords
	W_DOUBLE_AA, // 2 axes
	W_DOUBLE_DS, // dagger + sword
	W_DOUBLE_DA, // dagger + axe
	W_DOUBLE_SA, // sword + axe
};
```
Correct me if I'm wrong.

**Comment by Lemongrass3110** [comment]
Also see your CI test: https://travis-ci.org/HerculesWS/Hercules/jobs/114081901
It got flooded with the error messages I'm reffering to.

**Comment by MishimaHaruna** [comment]
Yup, the real problem this PR tries to solve is another -- arrays using a fixed size of 16, disregarding the max value of that enum. It'll be edited with the proper fix

**Comment by Lemongrass3110** [comment]
Sorry could not have known that from the first commit.

Although I still think this code is not complete. It still uses 0 instead of W_FIST and default to 1(W_DAGGER), which seems really odd?

All in all a nice cleanup of the hardcoded size though. :+1:

**Pull request merged**
