### PR TITLE
Fix getitem/getitem2 give stacked items when ForceSerial on

### PR DESCRIPTION
**Pull request by AnnieRuru**
#703

haiz ......

### CODE REVIEW

**Comment by MishimaHaruna** [comment]
I'm not sure we should handle it this way. With this patch, items with the force-serial option enabled, become non-stackable.

I believe there are some cases where we want them to stackable (please correct me if I'm wrong):
- Items with a serial can be merged (and have their serial removed), i.e. through the "Mergician" NPC (i.e. `mergeitem` script command)
- A `getitem` with `amount > 0` of a force-serial item should ideally generate a stack of items (with the same serial)

**Comment by AnnieRuru** [comment]
>A getitem with amount > 0 of a force-serial item should ideally generate a stack of items (with the same serial)

ehh ... ?
then you mean me and Jedzkie has misunderstood the behavior of force serial ?

if what you say there is right, then this patch is garbage
the original code from main branch is already correct

**Comment by hemagx** [comment]
if the item is stackable then it serialize the whole stack with same serial, if other stack came goes with another serial, it's how it works :)

**Comment by AnnieRuru** [comment]
close this one then, I'll identify the real threat

**Pull request closed without merging**
