### PR TITLE
Update the Mercenary item database.

### PR DESCRIPTION
**Pull request by Jedzkie**
Change Item ID and Mercenary ID to Constants.

### CODE REVIEW

**Comment by dastgir** [comment]
Haven't checked the source, but i doubt if mercenary name is saved as constants too

**Comment by AnnieRuru** [comment]
I tested this patch, I can summon loli ruri fine
https://github.com/AnnieRuru/customs/blob/master/screenshots/screenRuru_Server030.jpg
and isn't that mercenary is in `mob_db` database ?
```
{
	Id: 2349
	SpriteName: "MER_LOLI_RURI"
	Name: "Loli Ruri"
	Lv: 83
	Hp: 9815
	Sp: 234
	Exp: 0
	JExp: 0
	AttackRange: 2
	Attack: [1100, 200]
	Def: 60
	Mdef: 60
	Stats: {
		Str: 85
		Agi: 90
		Vit: 71
		Int: 43
		Dex: 85
		Luk: 105
	}
	ViewRange: 10
	ChaseRange: 12
	Size: 0
	Race: 6
	Element: (7, 2)
	Mode: {
		CanMove: true
		Aggressive: true
		CastSensorIdle: true
		Boss: true
		CanAttack: true
		Detector: true
		CastSensorChase: true
		ChangeChase: true
		ChangeTargetMelee: true
		ChangeTargetChase: true
	}
	MoveSpeed: 150
	AttackDelay: 1080
	AttackMotion: 780
	DamageMotion: 180
	MvpExp: 0
},
```

**Comment by Jedzkie** [comment]
@annieruru, maybe the cause of build error is the MER_ monsters are in mob_db.

**Comment by AnnieRuru** [comment]
no I already tested this patch, it works fine
.... and for those who doesn't know how to download patch from pull request
http://stackoverflow.com/questions/6188591/download-github-pull-request-as-unified-diff

@Jedzkie 
the build failed because we pull request when you push that bug commit
blame https://github.com/HerculesWS/Hercules/commit/718fc08805d6d91eb732b6a51472e8ae78aa1892
`[Error]: itemdb_read_combos(#1): Invalid format (Script column) in line 284 of "db/re/item_combo_db.txt", skipping.`
which has nothing related to this patch

I already did some minor edit to rebuild my other pull request

**Comment by Jedzkie** [comment]
@AnnieRuru so even travis failed, this is good to merge?

**Comment by AnnieRuru** [comment]
try do some white space edit
which you love to do it so much
it will rebuild again

**Comment by Jedzkie** [comment]
@AnnieRuru WAHAHAHAHHAHAHA.. Not really :)

**Comment by MishimaHaruna** [comment]
Merged as d6179ebd0c2f112bf8aa70a7dd5b59656c2649f2, thank you

**Pull request closed without merging**
