### PR TITLE
Add ability to show char servers list with colors based on players count.

### PR DESCRIPTION
**Pull request by 4144**
### Pull Request Prelude

- [x] I have followed [proper Hercules code styling][code].
- [x] I have read and understood the [contribution guidelines][cont] before making this PR.
- [x] I am aware that this PR will be closed if the above-mentioned criteria are not fulfilled.

### Changes Proposed

Add ability to show char servers list with colors based on players count.
Add missing functions from login.c into interface.

### CODE REVIEW

**Comment by HerculesWSAPI** [comment]
This change is [Reviewable](https://reviewable.io/reviews/herculesws/hercules/1891)

**Comment by MishimaHaruna** [comment]
Is there any way to display the user count as a number? I remember that with old clients it was a setting controlled by the langtype.

If it's still possible in the 2017 clients, we might want to add the ability to send the actual number instead of '4' when `send_user_count_description` is disabled.

**Comment by 4144** [comment]
look like no. new clients not show any numbers

**Comment by dastgir** [comment]
afaik, new clients doesn't show users (no matter the langtype)

**Comment by MishimaHaruna** [comment]
Ok, thank you for the confirmation. I'm merging this then

**Pull request merged**
