### PR TITLE
Add LGTM code quality badges

### PR DESCRIPTION
**Pull request by xcorail**
Hi there!

I thought you might be interested in adding these [code quality badges](https://lgtm.com/projects/g/HerculesWS/Hercules/ci/#badges) to your project. They will indicate a very high code quality to potential users and contributors.
You can also check the alerts discovered by [LGTM](https://lgtm.com/projects/g/HerculesWS/Hercules).

N.B.: I am on the team behind LGTM.com, I'd appreciate your feedback on this initiative, whether you're interested or not, if you find time to drop me a line. Thanks.

### CODE REVIEW

**Comment by HerculesWSAPI** [comment]
This change is [Reviewable](https://reviewable.io/reviews/herculesws/hercules/2202)

**Comment by xcorail** [comment]
Hi @dastgirp 
It's because by default, LGTM will detect automatically all languages present in your code, and it found some JS code ... I suspect this is just perhaps some HTML that is totally irrelevant to your project. 
This is just the default behaviour, you can exclude JavaScript in the configuration of your LGTM project if it doesn't make sense.

**Comment by Emistry** [comment]
it also highlight some area that could be fix to improve the quality.

**Comment by xcorail** [comment]
Hey there, 

I see that you fixed some LGTM alerts!

Just wanted to let you know that during 6 weeks, for each LGTM alert fixed, on your favourite projects, we'll make a donation to WWF. You can also win a free ticket to GitHub Universe, with travel and accommodation. Details here: https://competitions.lgtm.com/ghu-2018

**Pull request merged**
