### PR TITLE
Pain killer fix & Dragon breath fix

### PR DESCRIPTION
**Pull request by Nihadm89**
-Based off of rAthena
-Also help from
http://herc.ws/board/tracker/issue-8548-homunculus-sera-skill-pain-killer-does-not-buff-or-work-at-all/

Dragon breath fix
http://herc.ws/board/topic/10230-new-formula-for-dragon-breath/

http://herc.ws/board/tracker/issue-8543-rune-knight-skills-dragons-breath-and-dragons-water-breath-damage-not-being-boosted-by-ranged-damage-effects/

Both tested and confirmed. The flee part of dragon breath I do not have a fix for.

---
This change is [Reviewable](https://reviewable.io/reviews/herculesws/hercules/771)

### CODE REVIEW

**Comment by Nihadm89** [comment]
Am I missing anything in order to get these approved?

**Comment by AnisotropicDefixation** [comment]
Huh, it looks like I forgot something in my fix. Move to line 2662 and replace

if( sc->data[SC_LKCONCENTRATION] )

With:

if( sc->data[SC_LKCONCENTRATION] && (skill_id != RK_DRAGONBREATH || skill_id != RK_DRAGONBREATH_WATER))

As it isn't supposed to boost the damage.

**Comment by Nihadm89** [comment]
As far as I can tell, adding that bit of code doesn't change any damage output. I had other people test it too.

**Comment by MishimaHaruna** [comment]
The Dragon Breath commit also adds so many kludgy-looking special exceptions and workarounds, is there really no other way?

**Comment by Nihadm89** [comment]
As for Dragon Breath I would gladly welcome a better commit. My source editing skills are as good as a 5 yr olds. So unfortunately this is the best I can do, I can only base edits off of the work that others did. If anyone is willing to teach me I would welcome your help with open arms.

**Comment by AnisotropicDefixation** [comment]
To be honest the whole thing is wrong, md damage part of db is supposed to be removed and painkiller should always apply endure,

**Comment by Smokexyz** [comment]
This PR has conflicting files, should we close? or does the author want to update this?

**Comment by Ridley8819** [comment]
I looked at this several times. I can tell nihad won't update this. 
On the other hand there is a recent pr containing same fix

**Comment by Mysteries** [comment]
I say close it and use #1304

**Comment by Smokexyz** [comment]
Closed due to inactivity and conflicting files.

**Pull request closed without merging**
