### PR TITLE
Fix map-crash when floating npc use *npcspeed script command

### PR DESCRIPTION
**Pull request by Emistry**
### Pull Request Prelude

- [x] I have followed [proper Hercules code styling][code].
- [x] I have read and understood the [contribution guidelines][cont] before making this PR.
- [x] I am aware that this PR may be closed if the above-mentioned criteria are not fulfilled.

### Changes Proposed
Check for unit data `(nd->ud != NULL)` before adjust the NPC speed. 
Throw warnings if `nd->ud == NULL`.

**Issues addressed:** 
script command `npcspeed`, `npcwalkto`, `npcstop`, `unitwalk`, `unitwarp`, `unitstop` are not applicable for floating npc (without coordinate/location).
Fix map-crash due to unit_data `NULL`.

Sample NPC Script:
```
-	script	dummynpc	-1,{
	OnInit:
		debugmes "set speed to 100";
		npcspeed 100;
		debugmes "set speed done";
		end;
}
```
Result:
sample

After fixed:  throw warnings but didnt crash map-server
sample2

Related PR https://github.com/HerculesWS/Hercules/pull/1733

[cont]: https://github.com/HerculesWS/Hercules/blob/master/CONTRIBUTING.md
[code]: https://github.com/HerculesWS/Hercules/wiki/Coding-Style

### CODE REVIEW

**Comment by HerculesWSAPI** [comment]
This change is [Reviewable](https://reviewable.io/reviews/herculesws/hercules/2430)

**Comment by 4144** [comment]
@AnnieRuru  this code may not crash server but corrupt memory

probably better fix it in all functions

**Comment by AnnieRuru** [comment]
at least it doesn't cause memory leak ...
well, if just add in the same lines in those 2 script commands, simple I think

**Comment by Emistry** [comment]
the reason it doesn't crash are probably due to : 
`npcwalkto()` actually have the checking `if( ud == NULL) return 0;` added inside `unit_walktoxy()`
and
`npcstop()` actually have the checking `if(!ud ..... ) return 0;` added inside `unit_stop_walking()`

**Comment by AnnieRuru** [comment]
how about just adding 
```c
		if (nd->ud == NULL) {
			ShowWarning("buildin_npcwalkto: floating NPC don't have unit data.\n");
			return false;
		}
```
instead of let the script command fail silently ?

**Comment by hemagx** [comment]
Emistry, can you separate syntax fixing from the crash fixing? it's sort of impossible to review as it is right now.
separating each in it's respective commit would be a lot better.

**Comment by Emistry** [comment]
huh? like how? reset then redo to create 2 different commits? 
aren't at the end it still gonna end up become 1 commit that fix the same thing?
beside its not a huge commit to begin with, most of it just the `if (ud == NULL)` checking.

**Pull request merged**
