### PR TITLE
Changed all TBL_* to the appropriate structs

### PR DESCRIPTION
**Pull request by MishimaHaruna**
This merges / closes #1024, and removes a lot of explicit casts, replacing them with a safer (as in, more compile-time checks) macro (BL_CAST / BL_UCAST / BL_CCAST / BL_UCCAST). See the relative commits for more details.

This is ready for review, but please don't merge it yet (I want to rebase it first)

### CODE REVIEW

**Comment by MishimaHaruna** [comment]
Pull request ready for review/merge

**Comment by 4144** [comment]
look like commits in wrong order. one introduce function and one using it:
403f2488871614534165436fe1427f333814a7e5 Added const variants of BL_CAST/BL_UCAST: BL_CCAST/BL_UCCAST 
0f48d85da5cb5d7c096100bac01835605a9e0a8b Replaced some explicit casts with BL_UCAST/BL_UCCAST

**Comment by MishimaHaruna** [comment]
Umm, github might be showing them in wrong order because of the commit date (I inserted 403f248) after I already made 0f48d85... they are in the correct order in the history...

```
$ git log --decorate --oneline --graph bl_cast
* 192afc9 (HEAD -> bl_cast, upstream/pr/1034, upstream/bl_cast) Replaced the remaining explicit casts with BL_CAST/BL_UCAST
* e636ab3 Replaced some explicit casts with BL_UCAST
* 62a28e3 Moved status_get_homXXX macros to status.c
* f645d8c Replaced some map->id2sd calls with the proper map->id2XX function
* 30063eb Replaced some explicit casts with BL_UCAST/BL_UCCAST
* 0f48d85 Replaced some explicit casts with BL_UCAST/BL_UCCAST
* 403f248 Added const variants of BL_CAST/BL_UCAST: BL_CCAST/BL_UCCAST
* 960dd61 Introduced the BL_UCAST() macro as an alternative to explicit casts
* 93a40dd Change all TBL_NPC to struct npc_data as per style guidelines
* ba6c973 Change all TBL_ELEM to struct elemental_data as per style guidelines
* 7cdaf3d Change all TBL_PET to struct pet_data as per style guidelines
* 59cac05 Change all TBL_SKILL to struct skill_data as per style guidelines
* b3d282c Change all TBL_MER to struct mercenary_data as per style guidelines
* ec9a630 Change all TBL_HOM to struct homun_data as per style guidelines
* f342d8f Change all TBL_MOB to struct mob_data as per strly guidelines
* 9f2e737 Change all TBL_PC to struct map_session_data as per style guidelines
```

(I'm rebasing this on top of master anyways - I'll re-compile each commit just in case)

**Comment by MishimaHaruna** [comment]
Rebased and taken care of the issues pointed out.
Github is still showing commits out of order (I'll never understand why they decided to sort by date rather than by logical order, offering no way to customize that)

**Pull request merged**
