### PR TITLE
Update to last rA npc.

### PR DESCRIPTION
**Pull request by dastgir**
This PR would include all new rA npc merges.
This PR would also include some bug fixes which I observed and some from Bug Report..

DO NOT MERGE YET. WIP.

### CODE REVIEW

**Comment by EPuncker** [comment]
oh man, finally.

**Comment by dastgir** [comment]
@MishimaHaruna
If you want you can review it, I will follow up other changes in new PR,

**Comment by MishimaHaruna** [comment]
Reviewed/cleaned up/merged the following commits:

* 02b2171 Added missing 'end' in some scripts
* ea408ff Fix Issue in Dual Race.
* 7086fd4 Fix QuestID's for LostChild and Muff's Loan
* 4580df1 Fixed Several Bugs(Old GlastHeim)
* 9f45c59 Updated Buying Shops script
* 25e4b0c Added new NPC constants
* f841432 Fix Izlude In Shops Location and Direction
* 1bb2493 Added Ninja Shop
* 0b31cf5 Updated eden_iro.txt
* 93e1ba7 Removed some extra semi-colon
* 024d680 Added duplicates of Riding Creature Master
* 94266c9 Removed Blank Messages
* 19d6148 JobChanger Updated
* 08b30d8 Added and Optimized Halloween 2013
* 8126f24 Added Renewal quest items to Ayothaya Dungeon Entrance quest.
* b44a271 Updated Blacksmith job quest with some extra conditions.
* c0accec Fixed an issue in 'Message Delivery' quest blocking level 100+ characters.
* 873eb39 Added WoE Teleport Scroll, and fixes its typo
* 0d71a64 Fixes Still cutin.
* 1ba6128 monk_in should not have nosave.
* 9c5659c Updated RockPaperScissors

The rest still needs more work. I'll leave the PR open for more commits

**Comment by MishimaHaruna** [comment]
Merged:

* ce39818 Added 2013 Christmas Event
* 146247c Implemented 2012 Headgears Quest
* af40c64 Implemented Kagerou/Oboro Gear Enchants.

The GD_ITEMEMERGENCYCALL commit needs more work.

**Comment by MishimaHaruna** [comment]
What shall we do about this? GD_ITEMEMERGENCYCALL isn't acceptable in its current form

**Comment by dastgir** [comment]
Give tlme time of few days, and I will be back at this PR

**Comment by Jedzkie** [comment]
@dastgir, any news on this?

**Pull request closed without merging**
