### PR TITLE
Fixes #686. Blocks Vellum and Siege equips/potions usage on non WOE/PVP maps.

### LINKED ISSUE #686: WoE gear and consumable still work in instance
Vellum weapons
WoE / Siege armor sets
WoE potions (11547 11548 11549)

Shouldnt they disabled in instance ?

### PR DESCRIPTION
**Pull request by iRagno**
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

[//]: # (Note: Lines beginning with syntax such as this one, are comments and will not be visible in your report!)

### Pull Request Prelude

[//]: # (Thank you for working on improving Hercules!)

[//]: # (Please complete these steps and check the following boxes by putting an `x` inside the brackets _before_ filing your Pull Request.)

- [x] I have followed [proper Hercules code styling][code].
- [x] I have read and understood the [contribution guidelines][cont] before making this PR.
- [x] I am aware that this PR will be closed if the above-mentioned criteria are not fulfilled.

### Changes Proposed

[//]: # (Describe at length, the changes that this pull request makes.)

**Affected Branches:** `master`

[//]: # (Master? Slave?)

**Issues addressed:** #686 WoE gear and consumable still work in instance

[//]: # (Issue Tracker Number if any.)

### Known Issues and TODO List

- None

[//]: # (**NOTE** Enable the setting "[√] Allow edits from maintainers." when creating your pull request if you have not already enabled it.)

[cont]: https://github.com/HerculesWS/Hercules/blob/master/CONTRIBUTING.md
[code]: https://github.com/HerculesWS/Hercules/wiki/Coding-Style

---
This change is [Reviewable](https://reviewable.io/reviews/herculesws/hercules/1617)

### CODE REVIEW

**Comment by Asheraf** [comment]
you disabled it from BG maps as well is that official?

**Comment by iRagno** [comment]
Yes. Are disabled from all maps, excepts on zones where disable is false (gvg).

**Comment by iRagno** [comment]
Done. Maked it available on pvp too. Thanks @Asheraf.

**Comment by Mysteries** [comment]
Would we need to ? Only time PK will be enabled is if it normally is enabled by a GM.

**Comment by iRagno** [comment]
After think about it, if pk mode brings "pvp zone" effects to maps that aren't pvp, it indicates that pk zone inherits pvp zone, and may be missing an inherit function to it.

I don't know if exist any pk official server nowadays, however this needs to be merged asap because of Vellum Katzbalger (id 21002). That weapon reduces 8% of total hp of monster per hit, making instances like Endless Tower very easy to complete.

**Comment by dastgir** [comment]
PK is different than PvP Arena.
PK would not enable pvp zone(afaik), and would make these not affect those maps(which is good).
while enabling pvp by command(@pvpon) would still make the map as pvp zone, and these items wont be disabled

**Pull request merged**
