### PR TITLE
GPL Headers

### PR DESCRIPTION
**Pull request by MishimaHaruna**
This pull request standardizes the headers across source files, data files and script files through the entire project.

The new header contains proper copyright lines (including some that were lost during some find and replace that happened when eAthena was forked into rAthena, and again when rAthena was forked into Hercules), as well as a mention that the file is part of the Hercules project, and what license (GNU GPLv3) it's released under (as recommended by the FSF).

The other fields present in the script headers are also standardized, and a lot of useless chit-chat (changelogs can/should be found in the repository metadata) was removed, while preserving each author's name from the existing changelogs.

### CODE REVIEW

**Comment by AnnieRuru** [comment]
so ... if I want to update or fix the script, and my name isn't inside,
can I add a new line
`//= Copyright (C)  AnnieRuru`

**Comment by MishimaHaruna** [comment]
Yes, you may (but don't have to, since 'Hercules Dev Team' already includes you) add your line, and you should consider including the year or years:

```
//= Copyright (C) 2015  YourName
//= Copyright (C) 2012-2015  YourName
//= Copyright (C) 2009, 2011, 2013-2015  YourName
```
(there are two spaces before the name)
The first line says that you added one or more copyrighted contributions in 2015. The second line says that you added copyrighted contributions between (and including) 2012 and 2015. The third line says that you added copyrighted contributions in 2009, 2011 and in the period between 2013 and 2015.

You can put your line above all others (and, if possible, below the 'Hercules Dev Team' one, if you're committing code as an official Hercules developer). You may of course choose not to add anything, if/when you feel that 'Hercules Dev Team' is representative enough -- note that your name, just like mine and every other contributor's is (or at least is supposed to be) in the AUTHORS file in the repository, as well as in each of your commits.

Regardless of whether you add an explicit copyright statement, if your contribution is copyrightable, then it is covered by copyright (in most countries of the world).

Please note that minor edits and fixes aren't copyrightable. In order for an edit to be copyrightable it must be original and nontrivial. You can't claim copyrights on something you didn't do. You can't claim copyrights just because you renamed a variable or reformatted a paragraph.
The copyright notes I added are a bit all over the place, since there was no way (other than wasting several days on it) to tell whether a contribution was trivial or not (or even whether it's present in the file anymore, as some code might have been rewritten through the years). We decided to keep all the names that were stated in the script for consistency to avoid any issues. Future contributions should follow common sense and avoid claiming unwarranted copyrights.

This is an interesting read on the matter, if anyone is interested: http://softwarefreedom.org/resources/2012/ManagingCopyrightInformation.html

**Comment by AnnieRuru** [comment]
>Please note that minor edits and fixes aren't copyrightable. In order for an edit to be copyrightable it must be original and nontrivial

so I guess fixing stuffs can't add my name as copyright
because I'm just fixing stuffs, not alter the original content

noted

**Comment by TidusBR** [comment]
Unnecessary action, because if the objective is to respect the Copyright Original, the correct would be like this:

Copyright (C) 2003 ~ 2015  eAthena / rAthena / Hercules Dev Team

or

Copyright (C) 2003 ~ 2015  eA / rA / Herc Dev Team

I do not understand reinvigorate the copyright to Hercules and set portions for eAthena and rAthena, 90% of the script are based on eAthena and rAthena and only 10% Hercules.

Then the correct thing:

Copyright (C) 2003 ~ 2012 eAthena / rAthena  Dev Team
Portions Copyright (C) 2012 ~ 2015 Hercules Dev Team

**Comment by MishimaHaruna** [comment]
Thanks for mentioning that. The 'Portions' part was meant to be removed (as you may see from the last commits, where I didn't add it). I'll edit out the remaining ones.
The year was omitted on purpose, since the original file didn't contain that.
The order is strictly "last on top".

**Comment by MishimaHaruna** [comment]
Dropped the 'Portions' word from copyright lines

**Pull request merged**
