### PR TITLE
Split HULD translations to per NPC file instead of one large file

### PR DESCRIPTION
**Pull request by dastgirp**
### Pull Request Prelude

- [X] I have followed [proper Hercules code styling][code].
- [X] I have read and understood the [contribution guidelines][cont] before making this PR.
- [X] I am aware that this PR may be closed if the above-mentioned criteria are not fulfilled.

### Changes Proposed

Modified Haru's PR whose aim was to split HULD Translation files.
Fixed minor changes in this PR which resulted in failure to read translation files.

**Issues addressed:** 

[cont]: https://github.com/HerculesWS/Hercules/blob/master/CONTRIBUTING.md
[code]: https://github.com/HerculesWS/Hercules/wiki/Coding-Style

### CODE REVIEW

**Comment by HerculesWSAPI** [comment]
This change is [Reviewable](https://reviewable.io/reviews/herculesws/hercules/2492)

**Comment by dastgirp** [comment]
@M45T3Ryu please check

**Comment by M45T3Ryu** [comment]
Those are all the fixes that we mentioned before it is working for me

**Comment by dastgirp** [comment]
@4144 Fixed and rebased

**Pull request merged**
