### PR TITLE
Use a single solution file for MVSC

### PR DESCRIPTION
**Pull request by csnv**
### Pull Request Prelude

- [x] I have followed [proper Hercules code styling][code].
- [x] I have read and understood the [contribution guidelines][cont] before making this PR.
- [x] I am aware that this PR may be closed if the above-mentioned criteria are not fulfilled.

### Changes Proposed
Use a single solution file for MVSC

**Issues addressed:** 

[cont]: https://github.com/HerculesWS/Hercules/blob/master/CONTRIBUTING.md
[code]: https://github.com/HerculesWS/Hercules/wiki/Coding-Style

### CODE REVIEW

**Comment by dastgirp** [comment]
Debug folder is committed as well, I think that can be added in gitignore?

**Comment by csnv** [comment]
> Debug folder is committed as well, I think that can be added in gitignore?

Whoopsie. Fixed, thanks!

**Review by MishimaHaruna — APPROVED** [review]

**Comment by Asheraf** [comment]
@MishimaHaruna this seems to have deleted the following projects.. HPM cannot be built on windows now 
```
plugin-HPMHooking_api.vcxproj
plugin-HPMHooking_char.vcxproj
plugin-HPMHooking_login.vcxproj
plugin-HPMHooking_map.vcxproj
plugin-sample.vcxproj
```

**Comment by csnv** [comment]
> @MishimaHaruna this seems to have deleted the following projects.. HPM cannot be built on windows now
> 
> ```
> plugin-HPMHooking_api.vcxproj
> plugin-HPMHooking_char.vcxproj
> plugin-HPMHooking_login.vcxproj
> plugin-HPMHooking_map.vcxproj
> plugin-sample.vcxproj
> ```

My bad, I accidentally removed the backslash in .gitignore. Fixed in #3268

**Pull request merged**
