### PR TITLE
Add configurable steps for roulette

### PR DESCRIPTION
**Pull request by 4144**
### Pull Request Prelude

- [x] I have followed [proper Hercules code styling][code].
- [x] I have read and understood the [contribution guidelines][cont] before making this PR.
- [x] I am aware that this PR may be closed if the above-mentioned criteria are not fulfilled.

### Changes Proposed

Add configurable steps for roulette.

For change steps in client side need use one of this patches:
http://nemo.herc.ws/patches/ChangeRouletteBronzeLimit
http://nemo.herc.ws/patches/ChangeRouletteGoldLimit
http://nemo.herc.ws/patches/ChangeRouletteSilverLimit

### CODE REVIEW

**Comment by EPuncker** [comment]
Other than changing rou**ll**ette to rou**l**ette, everything else seems perfect

**Review by MishimaHaruna — CHANGES_REQUESTED** [review]
I agree - can you replace roullette with roulette as suggested (in filenames and flag/variable names)?

**Comment by 4144** [comment]
done

**Comment by 4144** [comment]
also rebased

**Review by MishimaHaruna — APPROVED** [review]

**Pull request merged**
