### PR TITLE
NPC Update:

### PR DESCRIPTION
**Pull request by Jedzkie**
Reference Picture:

For Guild Dealer

kRO:
screen ca oai000

iRO:
screenchaos000

### CODE REVIEW

**Comment by dastgir** [comment]
@MishimaHaruna
For this, should version and name should be added?
I find this change too trivial for version number change and copyright name..

**Comment by kisuka** [comment]
Can we please get rid of those stupid copyright things in the header? Saying the script is by someone for major versions is one thing, but outright saying a script is copyrighted by someone is just stupid.

**Comment by Jedzkie** [comment]
Okay ill remove that dont worry.

**Comment by MishimaHaruna** [comment]
Merged, thank you

**Pull request closed without merging**
