### PR TITLE
Script commands with optional parameter look for player will now ShowWarning

### PR DESCRIPTION
**Pull request by AnnieRuru**
@MishimaHaruna , I just finished bake your favorite chocolate pie :smile:
now script commands that optionally look for player char_id/account_id/name,
will ShowWarning on map-server if the player is not found

no longer promote bad scripting habit, like it ?

well the ingredient was actually taken from rathena script engine ...
https://github.com/rathena/rathena/blob/master/src/map/script.c#L120

### CODE REVIEW

**Comment by MishimaHaruna** [comment]
Looks good, I'll be reviewing (and hopefully merging) this today :)

I like how this standardizes the error messages through the code (although I'd still advise against using any commands that directly target a not-attached player - the reason is that the calling script won't know whether the command succeeded or not, and won't be able to act accordingly)

**Comment by MishimaHaruna** [comment]
`ispartneron` should be exempted from this, shouldn't it? (it's meant to check if the partner of the currently attached character is online, and shouldn't show a warning when it isn't). I'll edit that one out while merging.

**Comment by MishimaHaruna** [comment]
Merged, thank you!

**Comment by AnnieRuru** [comment]
> (although I'd still advise against using any commands that directly target a not-attached player - the reason is that the calling script won't know whether the command succeeded or not, and won't be able to act accordingly)

@MishimaHaruna , if you really want to make the script halt like `script->rid2sd` function do
just add `st->state = END;` inside those 3 functions, very easy :D
though, I still prefer to make it just ShowWarning without the END state
otherwise some live server event script broken

**Comment by MishimaHaruna** [comment]
No, I don't think I want it to END... The command would have no way to recover from that. It's better to have it continue with a warning. The reason why I advise using attachrid instead of this is that attachrid returns false if it fails to attach (so that the script will know that it failed, and can inform the user, or take any necessary action).
If a failure to execute the command isn't important, it's of course fine to use this method instead.

**Pull request closed without merging**
