### PR TITLE
Revamped Aegis style songs behavior. Fixes #835

### LINKED ISSUE #835: Songs
Original Topic: http://herc.ws/board/tracker/issue-8639-songs/?gopid=25023#entry25023

I've noticed something wrong with Clown/Gypsy songs (example Poem of Bragi) are not updated continuously.

Example: A Wizard casts a skill ( storm gust ) with Poem of Bragi effect inside Clown skill diameter. When the clown RECAST the song the wizard will stop after the 20 secs effect of the last casted Poem of Bragi. What should happen is.. it should be continuous the Wizard shouldn't have delays even after the song was re-casted.

Inshort:
In official if you are inside the area of Clown, it is impossible for you to run out of Poem of Bragi effect,. after 20 secs Poem of Bragi effect should just update again and again.

Bug Video:
https://youtu.be/R8mIAv_TRL8

### PR DESCRIPTION
**Pull request by csnv**
Now it will automatically update with new values (according to the
current song properties) when the status change is about to finish.

Thanks Kyeme for the necessary proofs and reminders!

### CODE REVIEW

**Comment by csnv** [comment]
This feature is complete as for the latest behavior proofs provided by @Kyeme 

No more commits will be pushed unless necessary.

**Comment by kyeme** [comment]
@csnv  thank you! I tested and it's working perfect!

@MishimaHaruna master <3

**Comment by MishimaHaruna** [comment]
I haven't tested this, but the code looks reasonable. It's fine to merge if @kyeme tested it.

**Comment by kyeme** [comment]
@MishimaHaruna i tested ingame and its working perfect.

**Comment by dastgir** [comment]
Merged. Thank you

**Pull request merged**
