### PR TITLE
Save near 200 places in arrays with size SC_MAX.

### PR DESCRIPTION
**Pull request by 4144**
SC_X conatants can be with any numbers.

### Pull Request Prelude

- [x] I have followed [proper Hercules code styling][code].
- [x] I have read and understood the [contribution guidelines][cont] before making this PR.
- [x] I am aware that this PR will be closed if the above-mentioned criteria are not fulfilled.

### Changes Proposed

Save near 200 places in arrays with size SC_MAX.

### CODE REVIEW

**Comment by HerculesWSAPI** [comment]
This change is [Reviewable](https://reviewable.io/reviews/herculesws/hercules/1817)

**Comment by guilherme-gm** [comment]
If I recall correctly SC_DAILYSENDCOUNT is used by client to show the amount of messages you can send in the current day, so it uses that fixed ID

**Comment by dastgir** [comment]
Afaik, SC doesn't depend on client, might be something else?

**Comment by guilherme-gm** [comment]
hmm SI does then? I thought the server sents sc ID to the client (and it would be a problem there: https://github.com/HerculesWS/Hercules/blob/master/src/map/rodex.c#L59 ) but seems to be fine, my bad

**Comment by dastgir** [comment]
I don't know how rodex works for that.
SI: Status Icon (the one displayed on right side)

**Comment by guilherme-gm** [comment]
Oh I see, didn't know that, thanks!

**Pull request merged**
