### PR TITLE
update private airship map list to match main kRO servers

### PR DESCRIPTION
**Pull request by Asheraf**
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

[//]: # (Note: Lines beginning with syntax such as this one, are comments and will not be visible in your report!)

### Pull Request Prelude

[//]: # (Thank you for working on improving Hercules!)

[//]: # (Please complete these steps and check the following boxes by putting an `x` inside the brackets _before_ filing your Pull Request.)

- [x] I have followed [proper Hercules code styling][code].
- [x] I have read and understood the [contribution guidelines][cont] before making this PR.
- [x] I am aware that this PR will be closed if the above-mentioned criteria are not fulfilled.

### Changes Proposed

updating the list to match main kRO server, no restrictions have been added to entering the maps.

### CODE REVIEW

**Comment by HerculesWSAPI** [comment]
This change is [Reviewable](https://reviewable.io/reviews/herculesws/hercules/2098)

**Comment by 4144** [comment]
look like something wrong with map names. travis failed

**Comment by Asheraf** [comment]
@4144 some maps are not added to hercules yet.

**Comment by 4144** [comment]
probably need also update packets? because now it works for RE clients only

**Pull request merged**
