### PR TITLE
Correct Castling skill to use cooldown

### PR DESCRIPTION
**Pull request by Asheraf**
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

[//]: # (Note: Lines beginning with syntax such as this one, are comments and will not be visible in your report!)

### Pull Request Prelude

[//]: # (Thank you for working on improving Hercules!)

[//]: # (Please complete these steps and check the following boxes by putting an `x` inside the brackets _before_ filing your Pull Request.)

- [x] I have followed [proper Hercules code styling][code].
- [x] I have read and understood the [contribution guidelines][cont] before making this PR.
- [x] I am aware that this PR will be closed if the above-mentioned criteria are not fulfilled.

### Changes Proposed

This pr corrects the homunculus skill `HAMI_CASTLE` based on test in kRO and [irowiki](http://irowiki.org/wiki/Castling) the skill has 1 sec cooldown.

[//]: # (Insert checklist here)
[//]: # (Syntax: - [ ] Checkbox)

[//]: # (**NOTE** Enable the setting "[√] Allow edits from maintainers." when creating your pull request if you have not already enabled it.)

[cont]: https://github.com/HerculesWS/Hercules/blob/master/CONTRIBUTING.md
[code]: https://github.com/HerculesWS/Hercules/wiki/Coding-Style

---
This change is [Reviewable](https://reviewable.io/reviews/herculesws/hercules/1638)

### CODE REVIEW

**Comment by MishimaHaruna** [comment]
Wow, this is a big reduction, from 129 to 1 second. Before merging this, can you confirm that based on your tests it is really spammable once every second?

**Comment by Asheraf** [comment]
Yes i'll record a video once im home.

**Comment by Asheraf** [comment]
@MishimaHaruna 
this is a video of test in kRO
https://drive.google.com/file/d/0B8s-sa51NSkgMnJQeUxSSnZydlU/view

also there is a video of AI that uses the skill for idle leveling in iRO
https://www.youtube.com/watch?v=rZjGXy4Cjf8

**Comment by MishimaHaruna** [comment]
Ok, merging, thank you

**Pull request merged**
