### PR TITLE
Spacing correction.

### PR DESCRIPTION
**Pull request by marky291**
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

[//]: # (Note: Lines beginning with syntax such as this one, are comments and will not be visible in your report!)

### Pull Request Prelude

[//]: # (Thank you for working on improving Hercules!)

[//]: # (Please complete these steps and check the following boxes by putting an `x` inside the brackets _before_ filing your Pull Request.)

- [x] I have followed [proper Hercules code styling][code].
- [x] I have read and understood the [contribution guidelines][cont] before making this PR.
- [x] I am aware that this PR will be closed if the above-mentioned criteria are not fulfilled.

### Changes Proposed

[//]: # (Describe at length, the changes that this pull request makes.)

**Affected Branches:** 

[//]: # (Master? Slave?)

**Issues addressed:**

[//]: # (Issue Tracker Number if any.)

### Known Issues and TODO List

[//]: # (Insert checklist here)
[//]: # (Syntax: - [ ] Checkbox)

[//]: # (**NOTE** Enable the setting "[√] Allow edits from maintainers." when creating your pull request if you have not already enabled it.)

[cont]: https://github.com/HerculesWS/Hercules/blob/master/CONTRIBUTING.md
[code]: https://github.com/HerculesWS/Hercules/wiki/Coding-Style

### CODE REVIEW

**Comment by HerculesWSAPI** [comment]
This change is [Reviewable](https://reviewable.io/reviews/herculesws/hercules/1728)

**Comment by Jedzkie** [comment]
LMAO.

**Comment by marky291** [comment]
What is funny, I just thought it was annoying when I was editing the config... not trying to impress anyone.

**Comment by dastgir** [comment]
Actually, not funny at all ...
Thanks for contribution :)

**Comment by marky291** [comment]
Thank you. @dastgir

**Comment by Jedzkie** [comment]
I'm a happy person. Actually I never noticed this too, that's why I laughed. But thanks for your contribution.

**Comment by marky291** [comment]
Oh my bad, I always had the impression of elitism with commits back in rAthena, look forward to future commits.

**Pull request merged**
